/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiError,
  Applicant,
  CreateJobApplicationsRequest,
  CreateOnboardingDocumentFilesRequest,
  GetEditPersonsStatus200Response,
  JobApplicationStatus,
  JobIdObject,
  ListApplicantsResponse,
  ListJobApplicationsResponse,
  ListPostsResponse,
  Post,
} from '../models/index';
import {
    ApiErrorFromJSON,
    ApiErrorToJSON,
    ApplicantFromJSON,
    ApplicantToJSON,
    CreateJobApplicationsRequestFromJSON,
    CreateJobApplicationsRequestToJSON,
    CreateOnboardingDocumentFilesRequestFromJSON,
    CreateOnboardingDocumentFilesRequestToJSON,
    GetEditPersonsStatus200ResponseFromJSON,
    GetEditPersonsStatus200ResponseToJSON,
    JobApplicationStatusFromJSON,
    JobApplicationStatusToJSON,
    JobIdObjectFromJSON,
    JobIdObjectToJSON,
    ListApplicantsResponseFromJSON,
    ListApplicantsResponseToJSON,
    ListJobApplicationsResponseFromJSON,
    ListJobApplicationsResponseToJSON,
    ListPostsResponseFromJSON,
    ListPostsResponseToJSON,
    PostFromJSON,
    PostToJSON,
} from '../models/index';

export interface CreateJobApplicationFilesRequest {
    contentType: string;
    fileName: string;
    id: string;
    url?: string;
    body?: Blob;
}

export interface CreateJobApplicationsOperationRequest {
    createJobApplicationsRequest?: CreateJobApplicationsRequest;
}

export interface GetApplicantRequest {
    uuid: string;
}

export interface GetEditJobApplicationsStatusRequest {
    jobId: string;
}

export interface GetPostRequest {
    uuid: string;
}

export interface ListApplicantsRequest {
    applicants?: Array<string>;
    statusFilter?: Array<JobApplicationStatus>;
    page?: number;
}

export interface ListJobApplicationsRequest {
    page?: number;
    posts?: Array<string>;
    statusFilter?: Array<JobApplicationStatus>;
}

export interface ListPostsRequest {
    onlyActive?: boolean;
}

/**
 * ApplicantManagementApi - interface
 * 
 * @export
 * @interface ApplicantManagementApiInterface
 */
export interface ApplicantManagementApiInterface {
    /**
     * Create a new file for a job application in HR WORKS by sending the binary data in body or an URL to download the file from.
     * @summary POST Job Application Files
     * @param {string} contentType The Mime-type of the file, e.g. \&#39;application/pdf\&#39;
     * @param {string} fileName The name of the file to display in HR WORKS.
     * @param {string} id The id of the job application that the uploaded file belongs to.
     * @param {string} [url] The url of the document (required if the file is not sent via the request body).
     * @param {Blob} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantManagementApiInterface
     */
    createJobApplicationFilesRaw(requestParameters: CreateJobApplicationFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>>;

    /**
     * Create a new file for a job application in HR WORKS by sending the binary data in body or an URL to download the file from.
     * POST Job Application Files
     */
    createJobApplicationFiles(requestParameters: CreateJobApplicationFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject>;

    /**
     * Create one or multiple job applications for applicant management
     * @summary POST Job Applications
     * @param {CreateJobApplicationsRequest} [createJobApplicationsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantManagementApiInterface
     */
    createJobApplicationsRaw(requestParameters: CreateJobApplicationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>>;

    /**
     * Create one or multiple job applications for applicant management
     * POST Job Applications
     */
    createJobApplications(requestParameters: CreateJobApplicationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject>;

    /**
     * Returns the data of one specific applicant.
     * @summary GET Single Applicant
     * @param {string} uuid The unique identifier of the person in HR WORKS. This identifier does not change, when the applicant is converted to an employee person.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantManagementApiInterface
     */
    getApplicantRaw(requestParameters: GetApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Applicant>>;

    /**
     * Returns the data of one specific applicant.
     * GET Single Applicant
     */
    getApplicant(requestParameters: GetApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Applicant>;

    /**
     * After a POST request to the /applicant-management/job-applications endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * @summary GET Job Applications Jobs
     * @param {string} jobId The job id of the previous write request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantManagementApiInterface
     */
    getEditJobApplicationsStatusRaw(requestParameters: GetEditJobApplicationsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEditPersonsStatus200Response>>;

    /**
     * After a POST request to the /applicant-management/job-applications endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * GET Job Applications Jobs
     */
    getEditJobApplicationsStatus(requestParameters: GetEditJobApplicationsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEditPersonsStatus200Response>;

    /**
     * Returns the data of a single post with the given id.
     * @summary GET Single Post
     * @param {string} uuid The uuid or id of the post in HR WORKS. The unique identifier cannot be changed. The passing of the id is deprecated.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantManagementApiInterface
     */
    getPostRaw(requestParameters: GetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>>;

    /**
     * Returns the data of a single post with the given id.
     * GET Single Post
     */
    getPost(requestParameters: GetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post>;

    /**
     * Returns a list of applicants. Only applicants with job applications are returned.
     * @summary GET Applicants
     * @param {Array<string>} [applicants] The UUIDs of the applicants to display data for.
     * @param {Array<JobApplicationStatus>} [statusFilter] If set, only applicants with a job application in the specified status will be returned.
     * @param {number} [page] Set this parameter to access a specific page of results. If the parameter is not set, the first page of results is returned. The API returns paging information via the Link header. The page size for this API call is 50.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantManagementApiInterface
     */
    listApplicantsRaw(requestParameters: ListApplicantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListApplicantsResponse>>;

    /**
     * Returns a list of applicants. Only applicants with job applications are returned.
     * GET Applicants
     */
    listApplicants(requestParameters: ListApplicantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListApplicantsResponse>;

    /**
     * List all job applications with the specified status and post.
     * @summary GET Job Applications
     * @param {number} [page] Set this parameter to access a specific page of results. If the parameter is not set, the first page of results is returned. The API returns paging information via the Link header. The page size for this API call is 50.
     * @param {Array<string>} [posts] The IDs of the posts for which to return job applications.
     * @param {Array<JobApplicationStatus>} [statusFilter] The status identifiers for which to return job applications.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantManagementApiInterface
     */
    listJobApplicationsRaw(requestParameters: ListJobApplicationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListJobApplicationsResponse>>;

    /**
     * List all job applications with the specified status and post.
     * GET Job Applications
     */
    listJobApplications(requestParameters: ListJobApplicationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListJobApplicationsResponse>;

    /**
     * List all posts of the company.
     * @summary GET Posts
     * @param {boolean} [onlyActive] Set this parameter to either return only active posts (true) or all posts (false). The default value is true
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantManagementApiInterface
     */
    listPostsRaw(requestParameters: ListPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPostsResponse>>;

    /**
     * List all posts of the company.
     * GET Posts
     */
    listPosts(requestParameters: ListPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPostsResponse>;

}

/**
 * 
 */
export class ApplicantManagementApi extends runtime.BaseAPI implements ApplicantManagementApiInterface {

    /**
     * Create a new file for a job application in HR WORKS by sending the binary data in body or an URL to download the file from.
     * POST Job Application Files
     */
    async createJobApplicationFilesRaw(requestParameters: CreateJobApplicationFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>> {
        if (requestParameters['contentType'] == null) {
            throw new runtime.RequiredError(
                'contentType',
                'Required parameter "contentType" was null or undefined when calling createJobApplicationFiles().'
            );
        }

        if (requestParameters['fileName'] == null) {
            throw new runtime.RequiredError(
                'fileName',
                'Required parameter "fileName" was null or undefined when calling createJobApplicationFiles().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createJobApplicationFiles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fileName'] != null) {
            queryParameters['fileName'] = requestParameters['fileName'];
        }

        if (requestParameters['url'] != null) {
            queryParameters['url'] = requestParameters['url'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/octet-stream';

        if (requestParameters['contentType'] != null) {
            headerParameters['content-type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/applicant-management/job-applications/{id}/files`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobIdObjectFromJSON(jsonValue));
    }

    /**
     * Create a new file for a job application in HR WORKS by sending the binary data in body or an URL to download the file from.
     * POST Job Application Files
     */
    async createJobApplicationFiles(requestParameters: CreateJobApplicationFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject> {
        const response = await this.createJobApplicationFilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create one or multiple job applications for applicant management
     * POST Job Applications
     */
    async createJobApplicationsRaw(requestParameters: CreateJobApplicationsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/applicant-management/job-applications`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateJobApplicationsRequestToJSON(requestParameters['createJobApplicationsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobIdObjectFromJSON(jsonValue));
    }

    /**
     * Create one or multiple job applications for applicant management
     * POST Job Applications
     */
    async createJobApplications(requestParameters: CreateJobApplicationsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject> {
        const response = await this.createJobApplicationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the data of one specific applicant.
     * GET Single Applicant
     */
    async getApplicantRaw(requestParameters: GetApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Applicant>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getApplicant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/applicant-management/applicants/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicantFromJSON(jsonValue));
    }

    /**
     * Returns the data of one specific applicant.
     * GET Single Applicant
     */
    async getApplicant(requestParameters: GetApplicantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Applicant> {
        const response = await this.getApplicantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * After a POST request to the /applicant-management/job-applications endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * GET Job Applications Jobs
     */
    async getEditJobApplicationsStatusRaw(requestParameters: GetEditJobApplicationsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEditPersonsStatus200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getEditJobApplicationsStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/applicant-management/job-applications/jobs/{jobId}`;
        urlPath = urlPath.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEditPersonsStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * After a POST request to the /applicant-management/job-applications endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * GET Job Applications Jobs
     */
    async getEditJobApplicationsStatus(requestParameters: GetEditJobApplicationsStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEditPersonsStatus200Response> {
        const response = await this.getEditJobApplicationsStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the data of a single post with the given id.
     * GET Single Post
     */
    async getPostRaw(requestParameters: GetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/applicant-management/posts/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostFromJSON(jsonValue));
    }

    /**
     * Returns the data of a single post with the given id.
     * GET Single Post
     */
    async getPost(requestParameters: GetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post> {
        const response = await this.getPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of applicants. Only applicants with job applications are returned.
     * GET Applicants
     */
    async listApplicantsRaw(requestParameters: ListApplicantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListApplicantsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['applicants'] != null) {
            queryParameters['applicants'] = requestParameters['applicants'];
        }

        if (requestParameters['statusFilter'] != null) {
            queryParameters['statusFilter'] = requestParameters['statusFilter'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/applicant-management/applicants`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListApplicantsResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of applicants. Only applicants with job applications are returned.
     * GET Applicants
     */
    async listApplicants(requestParameters: ListApplicantsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListApplicantsResponse> {
        const response = await this.listApplicantsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all job applications with the specified status and post.
     * GET Job Applications
     */
    async listJobApplicationsRaw(requestParameters: ListJobApplicationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListJobApplicationsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['posts'] != null) {
            queryParameters['posts'] = requestParameters['posts'];
        }

        if (requestParameters['statusFilter'] != null) {
            queryParameters['statusFilter'] = requestParameters['statusFilter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/applicant-management/job-applications`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListJobApplicationsResponseFromJSON(jsonValue));
    }

    /**
     * List all job applications with the specified status and post.
     * GET Job Applications
     */
    async listJobApplications(requestParameters: ListJobApplicationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListJobApplicationsResponse> {
        const response = await this.listJobApplicationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all posts of the company.
     * GET Posts
     */
    async listPostsRaw(requestParameters: ListPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPostsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['onlyActive'] != null) {
            queryParameters['onlyActive'] = requestParameters['onlyActive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/applicant-management/posts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPostsResponseFromJSON(jsonValue));
    }

    /**
     * List all posts of the company.
     * GET Posts
     */
    async listPosts(requestParameters: ListPostsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPostsResponse> {
        const response = await this.listPostsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
