/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccumulatedSickLeavesDateIntervalData,
  ApiError,
  CreateSickLeavesRequest,
  EditSickLeaveTypesRequest,
  EditSickLeavesRequest,
  GetEditAbsencesStatus200Response,
  Interval,
  JobIdObject,
  ListSickLeaveTypesResponse,
  MultiWriteRequestResponse,
  SickLeave,
  SickLeaveStatus,
  SickLeavesDateIntervalData,
} from '../models/index';
import {
    AccumulatedSickLeavesDateIntervalDataFromJSON,
    AccumulatedSickLeavesDateIntervalDataToJSON,
    ApiErrorFromJSON,
    ApiErrorToJSON,
    CreateSickLeavesRequestFromJSON,
    CreateSickLeavesRequestToJSON,
    EditSickLeaveTypesRequestFromJSON,
    EditSickLeaveTypesRequestToJSON,
    EditSickLeavesRequestFromJSON,
    EditSickLeavesRequestToJSON,
    GetEditAbsencesStatus200ResponseFromJSON,
    GetEditAbsencesStatus200ResponseToJSON,
    IntervalFromJSON,
    IntervalToJSON,
    JobIdObjectFromJSON,
    JobIdObjectToJSON,
    ListSickLeaveTypesResponseFromJSON,
    ListSickLeaveTypesResponseToJSON,
    MultiWriteRequestResponseFromJSON,
    MultiWriteRequestResponseToJSON,
    SickLeaveFromJSON,
    SickLeaveToJSON,
    SickLeaveStatusFromJSON,
    SickLeaveStatusToJSON,
    SickLeavesDateIntervalDataFromJSON,
    SickLeavesDateIntervalDataToJSON,
} from '../models/index';

export interface CreateSickLeaveTypesRequest {
    editSickLeaveTypesRequest?: EditSickLeaveTypesRequest;
}

export interface CreateSickLeavesOperationRequest {
    createSickLeavesRequest?: CreateSickLeavesRequest;
}

export interface DeleteSickLeaveRequest {
    number: string;
}

export interface DeleteSickLeavesRequest {
    numbers: Array<string>;
}

export interface EditSickLeavesOperationRequest {
    editSickLeavesRequest?: EditSickLeavesRequest;
}

export interface GetEditSickLeaveTypesStatusRequest {
    jobId: string;
}

export interface GetEditSickLeavesStatusRequest {
    jobId: string;
}

export interface GetSickLeaveRequest {
    number: string;
}

export interface ListSickLeaveTypesRequest {
    onlyActive?: boolean;
}

export interface ListSickLeavesRequest {
    beginDate: string;
    endDate: string;
    persons?: Array<string>;
    types?: Array<string>;
    count?: boolean;
    usePersonnelNumbers?: boolean;
    interval?: Interval;
    onlyActive?: boolean;
    page?: number;
    statusFilter?: Array<SickLeaveStatus>;
}

export interface ListSickLeavesAccumulatedRequest {
    beginDate: string;
    endDate: string;
    persons?: Array<string>;
    types?: Array<string>;
    usePersonnelNumbers?: boolean;
    interval?: Interval;
    page?: number;
    statusFilter?: Array<SickLeaveStatus>;
    onlyActive?: boolean;
}

/**
 * SickLeavesApi - interface
 * 
 * @export
 * @interface SickLeavesApiInterface
 */
export interface SickLeavesApiInterface {
    /**
     * Create new  sick leave type in HR WORKS. Refer to the data type SickLeaveType for a comprehensive list of attributes that can be set. Attributes that are not set/included in the create request are ignored (with the exception of mandatory attributes).
     * @summary POST Sick Leave Types
     * @param {EditSickLeaveTypesRequest} [editSickLeaveTypesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    createSickLeaveTypesRaw(requestParameters: CreateSickLeaveTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>>;

    /**
     * Create new  sick leave type in HR WORKS. Refer to the data type SickLeaveType for a comprehensive list of attributes that can be set. Attributes that are not set/included in the create request are ignored (with the exception of mandatory attributes).
     * POST Sick Leave Types
     */
    createSickLeaveTypes(requestParameters: CreateSickLeaveTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject>;

    /**
     * Create new sick leaves in HR WORKS. Refer to the data type SickLeaveData for a comprehensive list of attributes that can be set. Attributes that are not set/included in the create request are ignored (with the exception of mandatory attributes).
     * @summary POST Sick Leaves
     * @param {CreateSickLeavesRequest} [createSickLeavesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    createSickLeavesRaw(requestParameters: CreateSickLeavesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>>;

    /**
     * Create new sick leaves in HR WORKS. Refer to the data type SickLeaveData for a comprehensive list of attributes that can be set. Attributes that are not set/included in the create request are ignored (with the exception of mandatory attributes).
     * POST Sick Leaves
     */
    createSickLeaves(requestParameters: CreateSickLeavesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject>;

    /**
     * Delete a single sick leave by ID.
     * @summary DELETE Single Sick Leave
     * @param {string} number The number of the sick leave. Consists of the person\&#39;s license number before the underscore and the running sick leave number for the respective person after the underscore.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    deleteSickLeaveRaw(requestParameters: DeleteSickLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>>;

    /**
     * Delete a single sick leave by ID.
     * DELETE Single Sick Leave
     */
    deleteSickLeave(requestParameters: DeleteSickLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject>;

    /**
     * Delete multiple sick leaves in HR WORKS.
     * @summary DELETE Sick Leaves
     * @param {Array<string>} numbers List of sick leave numbers.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    deleteSickLeavesRaw(requestParameters: DeleteSickLeavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>>;

    /**
     * Delete multiple sick leaves in HR WORKS.
     * DELETE Sick Leaves
     */
    deleteSickLeaves(requestParameters: DeleteSickLeavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject>;

    /**
     * Edit sick leave objects in HR WORKS. Refer to the data type SickLeaveData for a comprehensive list of attributes that can be set. Attributes that are not set/included in the edit request are ignored (with the exception of mandatory attributes).
     * @summary PUT Sick Leaves
     * @param {EditSickLeavesRequest} [editSickLeavesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    editSickLeavesRaw(requestParameters: EditSickLeavesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>>;

    /**
     * Edit sick leave objects in HR WORKS. Refer to the data type SickLeaveData for a comprehensive list of attributes that can be set. Attributes that are not set/included in the edit request are ignored (with the exception of mandatory attributes).
     * PUT Sick Leaves
     */
    editSickLeaves(requestParameters: EditSickLeavesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject>;

    /**
     * After a POST or PUT request to the /sick-leaves/sick-leave-types endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * @summary GET Sick Leave Types Jobs
     * @param {string} jobId The job id of the previous write request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    getEditSickLeaveTypesStatusRaw(requestParameters: GetEditSickLeaveTypesStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MultiWriteRequestResponse>>;

    /**
     * After a POST or PUT request to the /sick-leaves/sick-leave-types endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * GET Sick Leave Types Jobs
     */
    getEditSickLeaveTypesStatus(requestParameters: GetEditSickLeaveTypesStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MultiWriteRequestResponse>;

    /**
     * After a POST or PUT request to the /sick-leaves endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * @summary GET Sick Leaves Jobs
     * @param {string} jobId The job id of the previous write request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    getEditSickLeavesStatusRaw(requestParameters: GetEditSickLeavesStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEditAbsencesStatus200Response>>;

    /**
     * After a POST or PUT request to the /sick-leaves endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * GET Sick Leaves Jobs
     */
    getEditSickLeavesStatus(requestParameters: GetEditSickLeavesStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEditAbsencesStatus200Response>;

    /**
     * Return the data of a specific sick leave by the given unique number.
     * @summary GET Single Sick Leave
     * @param {string} number The unique identifier of the sick leave. Consists of the person\&#39;s license number before the underscore and the running sick leave number for the respective person after the underscore.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    getSickLeaveRaw(requestParameters: GetSickLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SickLeave>>;

    /**
     * Return the data of a specific sick leave by the given unique number.
     * GET Single Sick Leave
     */
    getSickLeave(requestParameters: GetSickLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SickLeave>;

    /**
     * Lists all sick leave types defined for the caller\'s customer account in HR WORKS. The keys returned by this action can be used as filter values for other absence actions.
     * @summary GET Sick Leave Types
     * @param {boolean} [onlyActive] If set to false, the response also contains sick leaves types that are deactivated.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    listSickLeaveTypesRaw(requestParameters: ListSickLeaveTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSickLeaveTypesResponse>>;

    /**
     * Lists all sick leave types defined for the caller\'s customer account in HR WORKS. The keys returned by this action can be used as filter values for other absence actions.
     * GET Sick Leave Types
     */
    listSickLeaveTypes(requestParameters: ListSickLeaveTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSickLeaveTypesResponse>;

    /**
     * Returns a list of sick leaves for the specified persons in the specified date interval.
     * @summary GET Sick Leaves
     * @param {string} beginDate The starting date of the date interval. Note: The maximum date interval is one year.
     * @param {string} endDate The end date of the date interval. Note: The maximum date interval is one year.
     * @param {Array<string>} [persons] The HR WORKS usernames of the persons to display data for. Note: Using the optional parameter usePersonnelNumbers, HR WORKS personnel numbers can be passed instead of HR WORKS usernames.
     * @param {Array<string>} [types] This parameter can be used to apply a filter to the result by specifying a list of sickness type identifiers/keys. If set, only sick leaves matching one of those keys will be returned. Note: The sick leave type keys can be retrieved via the /sick-leaves/sick-leave-types endpoint.
     * @param {boolean} [count] If set to \&quot;true\&quot;, this action will return the cumulated working days count for each sick leave type instead of the sickness details. This impacts the structure of the API response.
     * @param {boolean} [usePersonnelNumbers] If set to true, the API will assume the strings in the persons parameter to represent personnel numbers instead of HR WORKS usernames.
     * @param {Interval} [interval] Indicates whether the date interval should be split into smaller intervals like weeks or months. If this parameter is not set, the interval will not be split. Setting this parameter to \&quot;days\&quot; will shorten the maximum allowed interval size to 31 days. Note: The API does not perform any date interval adjustments. E.g., even if \&quot;weeks\&quot; was specified for the interval parameter, if the date interval specified by beginDate and endDate spans only two days, the data will only be computed for this two-day span. However, if those two days happen to be Monday and Sunday of different weeks, the result will be split accordingly.
     * @param {boolean} [onlyActive] Set this parameter to false to return persons that have left the company and were set to gone in HR WORKS as well. Note: Deleted persons cannot be returned as the data was removed from HR WORKS. This parameter will be ignored if persons are specified directly via the persons parameter.
     * @param {number} [page] Set this parameter to access a specific page of results. If the parameter is not set, the first page of results is returned. The API returns paging information via the Link header. The page size for this API call is 50.
     * @param {Array<SickLeaveStatus>} [statusFilter] If specified, only values matching one of the selected status values will be returned.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    listSickLeavesRaw(requestParameters: ListSickLeavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<SickLeavesDateIntervalData>; }>>;

    /**
     * Returns a list of sick leaves for the specified persons in the specified date interval.
     * GET Sick Leaves
     */
    listSickLeaves(requestParameters: ListSickLeavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<SickLeavesDateIntervalData>; }>;

    /**
     * Returns a list of cumulated working days count for each sick leaves type for the specified persons in the specified date interval.
     * @summary GET Accumulated Sick Leaves
     * @param {string} beginDate The starting date of the date interval. Note: The maximum date interval is one year.
     * @param {string} endDate The end date of the date interval. Note: The maximum date interval is one year.
     * @param {Array<string>} [persons] The HR WORKS usernames of the persons to display data for. Note: Using the optional parameter usePersonnelNumbers, HR WORKS personnel numbers can be passed instead of HR WORKS usernames.
     * @param {Array<string>} [types] This parameter can be used to apply a filter to the result by specifying a list of sickness type identifiers/keys. If set, only sick leaves matching one of those keys will be returned. Note: The sick leave type keys can be retrieved via the /sick-leaves/sick-leave-types endpoint.
     * @param {boolean} [usePersonnelNumbers] If set to true, the API will assume the strings in the persons parameter to represent personnel numbers instead of HR WORKS usernames.
     * @param {Interval} [interval] Indicates whether the date interval should be split into smaller intervals like weeks or months. If this parameter is not set, the interval will not be split. Setting this parameter to \&quot;days\&quot; will shorten the maximum allowed interval size to 31 days. Note: The API does not perform any date interval adjustments. E.g., even if \&quot;weeks\&quot; was specified for the interval parameter, if the date interval specified by beginDate and endDate spans only two days, the data will only be computed for this two-day span. However, if those two days happen to be Monday and Sunday of different weeks, the result will be split accordingly.
     * @param {number} [page] Set this parameter to access a specific page of results. If the parameter is not set, the first page of results is returned. The API returns paging information via the Link header. The page size for this API call is 50.
     * @param {Array<SickLeaveStatus>} [statusFilter] If specified, only values matching one of the selected status values will be returned.
     * @param {boolean} [onlyActive] Set this parameter to false to return persons that have left the company and were set to gone in HR WORKS as well. Note: Deleted persons cannot be returned as the data was removed from HR WORKS. This parameter will be ignored if persons are specified directly via the persons parameter.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SickLeavesApiInterface
     */
    listSickLeavesAccumulatedRaw(requestParameters: ListSickLeavesAccumulatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<AccumulatedSickLeavesDateIntervalData>; }>>;

    /**
     * Returns a list of cumulated working days count for each sick leaves type for the specified persons in the specified date interval.
     * GET Accumulated Sick Leaves
     */
    listSickLeavesAccumulated(requestParameters: ListSickLeavesAccumulatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<AccumulatedSickLeavesDateIntervalData>; }>;

}

/**
 * 
 */
export class SickLeavesApi extends runtime.BaseAPI implements SickLeavesApiInterface {

    /**
     * Create new  sick leave type in HR WORKS. Refer to the data type SickLeaveType for a comprehensive list of attributes that can be set. Attributes that are not set/included in the create request are ignored (with the exception of mandatory attributes).
     * POST Sick Leave Types
     */
    async createSickLeaveTypesRaw(requestParameters: CreateSickLeaveTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves/sick-leave-types`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EditSickLeaveTypesRequestToJSON(requestParameters['editSickLeaveTypesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobIdObjectFromJSON(jsonValue));
    }

    /**
     * Create new  sick leave type in HR WORKS. Refer to the data type SickLeaveType for a comprehensive list of attributes that can be set. Attributes that are not set/included in the create request are ignored (with the exception of mandatory attributes).
     * POST Sick Leave Types
     */
    async createSickLeaveTypes(requestParameters: CreateSickLeaveTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject> {
        const response = await this.createSickLeaveTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create new sick leaves in HR WORKS. Refer to the data type SickLeaveData for a comprehensive list of attributes that can be set. Attributes that are not set/included in the create request are ignored (with the exception of mandatory attributes).
     * POST Sick Leaves
     */
    async createSickLeavesRaw(requestParameters: CreateSickLeavesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSickLeavesRequestToJSON(requestParameters['createSickLeavesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobIdObjectFromJSON(jsonValue));
    }

    /**
     * Create new sick leaves in HR WORKS. Refer to the data type SickLeaveData for a comprehensive list of attributes that can be set. Attributes that are not set/included in the create request are ignored (with the exception of mandatory attributes).
     * POST Sick Leaves
     */
    async createSickLeaves(requestParameters: CreateSickLeavesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject> {
        const response = await this.createSickLeavesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a single sick leave by ID.
     * DELETE Single Sick Leave
     */
    async deleteSickLeaveRaw(requestParameters: DeleteSickLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>> {
        if (requestParameters['number'] == null) {
            throw new runtime.RequiredError(
                'number',
                'Required parameter "number" was null or undefined when calling deleteSickLeave().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves/{number}`;
        urlPath = urlPath.replace(`{${"number"}}`, encodeURIComponent(String(requestParameters['number'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobIdObjectFromJSON(jsonValue));
    }

    /**
     * Delete a single sick leave by ID.
     * DELETE Single Sick Leave
     */
    async deleteSickLeave(requestParameters: DeleteSickLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject> {
        const response = await this.deleteSickLeaveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete multiple sick leaves in HR WORKS.
     * DELETE Sick Leaves
     */
    async deleteSickLeavesRaw(requestParameters: DeleteSickLeavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>> {
        if (requestParameters['numbers'] == null) {
            throw new runtime.RequiredError(
                'numbers',
                'Required parameter "numbers" was null or undefined when calling deleteSickLeaves().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['numbers'] != null) {
            queryParameters['numbers'] = requestParameters['numbers'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobIdObjectFromJSON(jsonValue));
    }

    /**
     * Delete multiple sick leaves in HR WORKS.
     * DELETE Sick Leaves
     */
    async deleteSickLeaves(requestParameters: DeleteSickLeavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject> {
        const response = await this.deleteSickLeavesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Edit sick leave objects in HR WORKS. Refer to the data type SickLeaveData for a comprehensive list of attributes that can be set. Attributes that are not set/included in the edit request are ignored (with the exception of mandatory attributes).
     * PUT Sick Leaves
     */
    async editSickLeavesRaw(requestParameters: EditSickLeavesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobIdObject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EditSickLeavesRequestToJSON(requestParameters['editSickLeavesRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobIdObjectFromJSON(jsonValue));
    }

    /**
     * Edit sick leave objects in HR WORKS. Refer to the data type SickLeaveData for a comprehensive list of attributes that can be set. Attributes that are not set/included in the edit request are ignored (with the exception of mandatory attributes).
     * PUT Sick Leaves
     */
    async editSickLeaves(requestParameters: EditSickLeavesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobIdObject> {
        const response = await this.editSickLeavesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * After a POST or PUT request to the /sick-leaves/sick-leave-types endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * GET Sick Leave Types Jobs
     */
    async getEditSickLeaveTypesStatusRaw(requestParameters: GetEditSickLeaveTypesStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MultiWriteRequestResponse>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getEditSickLeaveTypesStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves/sick-leave-types/jobs/{jobId}`;
        urlPath = urlPath.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MultiWriteRequestResponseFromJSON(jsonValue));
    }

    /**
     * After a POST or PUT request to the /sick-leaves/sick-leave-types endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * GET Sick Leave Types Jobs
     */
    async getEditSickLeaveTypesStatus(requestParameters: GetEditSickLeaveTypesStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MultiWriteRequestResponse> {
        const response = await this.getEditSickLeaveTypesStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * After a POST or PUT request to the /sick-leaves endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * GET Sick Leaves Jobs
     */
    async getEditSickLeavesStatusRaw(requestParameters: GetEditSickLeavesStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEditAbsencesStatus200Response>> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getEditSickLeavesStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves/jobs/{jobId}`;
        urlPath = urlPath.replace(`{${"jobId"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEditAbsencesStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * After a POST or PUT request to the /sick-leaves endpoint was performed, the result can be fetched via the corresponding /jobs endpoint.
     * GET Sick Leaves Jobs
     */
    async getEditSickLeavesStatus(requestParameters: GetEditSickLeavesStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEditAbsencesStatus200Response> {
        const response = await this.getEditSickLeavesStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Return the data of a specific sick leave by the given unique number.
     * GET Single Sick Leave
     */
    async getSickLeaveRaw(requestParameters: GetSickLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SickLeave>> {
        if (requestParameters['number'] == null) {
            throw new runtime.RequiredError(
                'number',
                'Required parameter "number" was null or undefined when calling getSickLeave().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves/{number}`;
        urlPath = urlPath.replace(`{${"number"}}`, encodeURIComponent(String(requestParameters['number'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SickLeaveFromJSON(jsonValue));
    }

    /**
     * Return the data of a specific sick leave by the given unique number.
     * GET Single Sick Leave
     */
    async getSickLeave(requestParameters: GetSickLeaveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SickLeave> {
        const response = await this.getSickLeaveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists all sick leave types defined for the caller\'s customer account in HR WORKS. The keys returned by this action can be used as filter values for other absence actions.
     * GET Sick Leave Types
     */
    async listSickLeaveTypesRaw(requestParameters: ListSickLeaveTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSickLeaveTypesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['onlyActive'] != null) {
            queryParameters['onlyActive'] = requestParameters['onlyActive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves/sick-leave-types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSickLeaveTypesResponseFromJSON(jsonValue));
    }

    /**
     * Lists all sick leave types defined for the caller\'s customer account in HR WORKS. The keys returned by this action can be used as filter values for other absence actions.
     * GET Sick Leave Types
     */
    async listSickLeaveTypes(requestParameters: ListSickLeaveTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSickLeaveTypesResponse> {
        const response = await this.listSickLeaveTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of sick leaves for the specified persons in the specified date interval.
     * GET Sick Leaves
     */
    async listSickLeavesRaw(requestParameters: ListSickLeavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<SickLeavesDateIntervalData>; }>> {
        if (requestParameters['beginDate'] == null) {
            throw new runtime.RequiredError(
                'beginDate',
                'Required parameter "beginDate" was null or undefined when calling listSickLeaves().'
            );
        }

        if (requestParameters['endDate'] == null) {
            throw new runtime.RequiredError(
                'endDate',
                'Required parameter "endDate" was null or undefined when calling listSickLeaves().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['persons'] != null) {
            queryParameters['persons'] = requestParameters['persons'];
        }

        if (requestParameters['beginDate'] != null) {
            queryParameters['beginDate'] = requestParameters['beginDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        if (requestParameters['types'] != null) {
            queryParameters['types'] = requestParameters['types'];
        }

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        if (requestParameters['usePersonnelNumbers'] != null) {
            queryParameters['usePersonnelNumbers'] = requestParameters['usePersonnelNumbers'];
        }

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['onlyActive'] != null) {
            queryParameters['onlyActive'] = requestParameters['onlyActive'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['statusFilter'] != null) {
            queryParameters['statusFilter'] = requestParameters['statusFilter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns a list of sick leaves for the specified persons in the specified date interval.
     * GET Sick Leaves
     */
    async listSickLeaves(requestParameters: ListSickLeavesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<SickLeavesDateIntervalData>; }> {
        const response = await this.listSickLeavesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of cumulated working days count for each sick leaves type for the specified persons in the specified date interval.
     * GET Accumulated Sick Leaves
     */
    async listSickLeavesAccumulatedRaw(requestParameters: ListSickLeavesAccumulatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<AccumulatedSickLeavesDateIntervalData>; }>> {
        if (requestParameters['beginDate'] == null) {
            throw new runtime.RequiredError(
                'beginDate',
                'Required parameter "beginDate" was null or undefined when calling listSickLeavesAccumulated().'
            );
        }

        if (requestParameters['endDate'] == null) {
            throw new runtime.RequiredError(
                'endDate',
                'Required parameter "endDate" was null or undefined when calling listSickLeavesAccumulated().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['persons'] != null) {
            queryParameters['persons'] = requestParameters['persons'];
        }

        if (requestParameters['beginDate'] != null) {
            queryParameters['beginDate'] = requestParameters['beginDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = requestParameters['endDate'];
        }

        if (requestParameters['types'] != null) {
            queryParameters['types'] = requestParameters['types'];
        }

        if (requestParameters['usePersonnelNumbers'] != null) {
            queryParameters['usePersonnelNumbers'] = requestParameters['usePersonnelNumbers'];
        }

        if (requestParameters['interval'] != null) {
            queryParameters['interval'] = requestParameters['interval'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['statusFilter'] != null) {
            queryParameters['statusFilter'] = requestParameters['statusFilter'];
        }

        if (requestParameters['onlyActive'] != null) {
            queryParameters['onlyActive'] = requestParameters['onlyActive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v2/sick-leaves/accumulated-values`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns a list of cumulated working days count for each sick leaves type for the specified persons in the specified date interval.
     * GET Accumulated Sick Leaves
     */
    async listSickLeavesAccumulated(requestParameters: ListSickLeavesAccumulatedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<AccumulatedSickLeavesDateIntervalData>; }> {
        const response = await this.listSickLeavesAccumulatedRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
