// @ts-check

import {
  commentListFactory,
  commentListItemFactory,
} from '../../../../../shared/smartFaceComponentFactories/application/cd/commentListFactory.js';
import { cardFactory } from '../../../../../shared/smartFaceComponentFactories/core/cardFactory.js';
import { classicLayoutFactory } from '../../../../../shared/smartFaceComponentFactories/core/classicLayoutFactory.js';
import { fontAwesomeIconFactory } from '../../../../../shared/smartFaceComponentFactories/core/fontAwesomeIconFactory.js';
import { gridFactory, gridItemFactory } from '../../../../../shared/smartFaceComponentFactories/core/gridFactory.js';
import { pageFactory } from '../../../../../shared/smartFaceComponentFactories/core/pageFactory.js';
import { smartFaceFactory } from '../../../../../shared/smartFaceComponentFactories/core/smartFaceFactory.js';
import { generateLoremWords } from '../../../../../src/main/lib/stringGenerator/stringGenerator.js';
import { footer } from '../../shared/footer.js';
import { sidebar } from '../../shared/sidebar.js';

/**
 * @type { import('../../../../../src/types/shared/BackendResponseType/SmartFaceBackendDataType').SmartFaceBackendDataType }
 */
export const commentListPage = smartFaceFactory({
  sfComponents: [
    pageFactory({
      document: { head: { title: 'CommentList Page' } },
      componentChildren: [
        classicLayoutFactory({
          sidebar: sidebar('comment-list-page', ['cd-pages']),
          content: {
            componentChildren: [
              gridFactory({
                items: [
                  gridItemFactory({
                    componentChildren: [
                      cardFactory({
                        bodyChildren: [
                          commentListFactory(
                            {
                              textUrlMaxLength: 13,
                              items: [
                                commentListItemFactory(
                                  {
                                    timestamp: '29.01.2023',
                                    signature: 'n.moulgada@hrworks.de',
                                    text: generateLoremWords(12),
                                    toolbarChildren: [
                                      gridFactory({
                                        columnGap: 'small',
                                        items: [
                                          gridItemFactory({
                                            componentChildren: [fontAwesomeIconFactory({ name: 'pen' })],
                                          }),
                                          gridItemFactory({
                                            componentChildren: [fontAwesomeIconFactory({ name: 'trash' })],
                                          }),
                                          gridItemFactory({
                                            componentChildren: [fontAwesomeIconFactory({ name: 'ellipsis-vertical' })],
                                          }),
                                        ],
                                      }),
                                    ],
                                  },
                                  undefined,
                                  'data-guide-test',
                                ),
                                commentListItemFactory({
                                  timestamp:
                                    '29.01.202329.01.202329.01.202329.01.202329..202329.01.202329.01.202329.01.202329.01.202329.01.202329.01.202329.01.202329.01.202329.01.202329.01.202329.01.202329.01.202329.01.2023',
                                  signature:
                                    'n.moulgada@hrworks.den.moulgada@hrworks.@hr.den.moulgada@hrworks.den.moulgada@hrworks.den.moulgada@hrworks.den.moulgada@hrworks.den.moulgada@hrworks.den.moulgada@hrworks.den.moulgada@hrworks.de',
                                  text: `http://localhost-WithNotTopLevelDomain:3000/commentList   some text till next URL test test test test https://google.com/commentList  www.test.de ${generateLoremWords(
                                    8,
                                  )}`,
                                  toolbarChildren: [
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                    fontAwesomeIconFactory({ name: 'pen' }),
                                    fontAwesomeIconFactory({ name: 'ellipsis-vertical' }),
                                    fontAwesomeIconFactory({ name: 'trash' }),
                                  ],
                                }),
                                commentListItemFactory({
                                  timestamp: '01.01.1942 12:34 Uhr',
                                  signature: 'MANUALLY SET COMMENT LINK LENGTH 22',
                                  text: 'http://test.de AAA AAA AAA AAAA AAAAA  http://localhost-WithNotTopLevelDomain:3000/commentList  BBBB BBB BBBBBBBB BB https://google.com/commentList  www.test.de CCCCCCCCCCCCCCCCC CCCCCC http://withoutSecureConnection.de/commentList  DDDDDDDDD DD  http://LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL.de/commentList ',
                                }),
                                commentListItemFactory({
                                  timestamp: '01.01.1942 12:34 Uhr',
                                  text: '',
                                }),
                              ],
                            },
                            undefined,
                            'data-guide-test',
                          ),
                        ],
                      }),
                    ],
                  }),
                ],
              }),
            ],
          },
          footer,
        }),
      ],
    }),
  ],
});
