name: 'Build SmartFace'
description: 'Build SmartFace'

inputs:
  public-url:
    description: 'SmartFace PUBLIC_URL'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Use Bun 1.3.3
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.3

    - name: Restore and save bun cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-cache-v1.3-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-cache-v1.3

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Build
      shell: bash
      env:
        NODE_ENV: production
      run: bun run --cwd packages/smartface bunx cross-env PUBLIC_URL=${{ inputs.public-url }} bun smart-face-scripts/index.js build smartface-ui default

    - name: Move build folder
      shell: bash
      run: mv packages/smartface/build .
