export const WARNING_CODES = {
  INVALID_TREE_STATE: 'INVALID_TREE_STATE',
  FILE_MANAGER_MISSING_TARGET_SFIDS: 'FILE_MANAGER_MISSING_TARGET_SFIDS',
  UNKNOWN_DICTIONARY_ENTRY: 'UNKNOWN_DICTIONARY_ENTRY',
  UNKNOWN_SIDEEFFECT: 'UNKNOWN_SIDEEFFECT',
  INVALID_DATE: 'INVALID_DATE',
  CHART_MISSING_TARGET_SFID: 'CHART_MISSING_TARGET_SFID',
  UNSUPPORTED_FEATURE: 'UNSUPPORTED_FEATURE',
  INCOMPLETE_FEATURE: 'INCOMPLETE_FEATURE',
  ILLEGAL_PROPS: 'ILLEGAL_PROPS',
} as const;
