/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AbsenceStatus } from './AbsenceStatus';
import {
    AbsenceStatusFromJSON,
    AbsenceStatusFromJSONTyped,
    AbsenceStatusToJSON,
    AbsenceStatusToJSONTyped,
} from './AbsenceStatus';
import type { PersonBaseData } from './PersonBaseData';
import {
    PersonBaseDataFromJSON,
    PersonBaseDataFromJSONTyped,
    PersonBaseDataToJSON,
    PersonBaseDataToJSONTyped,
} from './PersonBaseData';

/**
 * 
 * @export
 * @interface Absence
 */
export interface Absence {
    /**
     * The short identifier of the absence's type, e.g. "AL" for Annual Leave. The identifiers can be configured in HR WORKS.
     * @type {string}
     * @memberof Absence
     */
    type?: string;
    /**
     * The start date of the absence. Date in YYYY-MM-DD format
     * @type {Date}
     * @memberof Absence
     */
    beginDate?: Date;
    /**
     * The end date of the absence. Date in YYYY-MM-DD format
     * @type {Date}
     * @memberof Absence
     */
    endDate?: Date;
    /**
     * Specifies whether the absence spans only the afternoon of the first day (or only the afternoon for one-day absences).
     * @type {boolean}
     * @memberof Absence
     */
    isBeginDateHalfDay?: boolean;
    /**
     * Specifies whether the absence spans only the forenoon of the last day (or only the forenoon for one-day absences).
     * @type {boolean}
     * @memberof Absence
     */
    isEndDateHalfDay?: boolean;
    /**
     * The full name of the absence type. Identical for all absences of the same type.
     * @type {string}
     * @memberof Absence
     */
    name?: string;
    /**
     * A unique identifier of the absence. Consists of the person's license number before the underscore and the running absence number for the respective person after the underscore.
     * @type {string}
     * @memberof Absence
     */
    number?: string;
    /**
     * The absence's status, e.g. "Checked, OK".
     * @type {string}
     * @memberof Absence
     */
    status?: string;
    /**
     * 
     * @type {AbsenceStatus}
     * @memberof Absence
     */
    statusIdentifier?: AbsenceStatus | null;
    /**
     * The number of working days that fall within the absence's date interval.
     * @type {number}
     * @memberof Absence
     */
    workingDays?: number;
    /**
     * The number of working days that fall within the absence's date interval and the date interval specified by the beginDate and endDate parameters.
     * @type {number}
     * @memberof Absence
     */
    workingDaysInDateInterval?: number;
    /**
     * The user-entered remark of the absence.
     * @type {string}
     * @memberof Absence
     */
    remark?: string;
    /**
     * The substitutes assigned to the absence.
     * @type {Array<PersonBaseData>}
     * @memberof Absence
     */
    substitutes?: Array<PersonBaseData>;
}



/**
 * Check if a given object implements the Absence interface.
 */
export function instanceOfAbsence(value: object): value is Absence {
    return true;
}

export function AbsenceFromJSON(json: any): Absence {
    return AbsenceFromJSONTyped(json, false);
}

export function AbsenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Absence {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'isBeginDateHalfDay': json['isBeginDateHalfDay'] == null ? undefined : json['isBeginDateHalfDay'],
        'isEndDateHalfDay': json['isEndDateHalfDay'] == null ? undefined : json['isEndDateHalfDay'],
        'name': json['name'] == null ? undefined : json['name'],
        'number': json['number'] == null ? undefined : json['number'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusIdentifier': json['statusIdentifier'] == null ? undefined : AbsenceStatusFromJSON(json['statusIdentifier']),
        'workingDays': json['workingDays'] == null ? undefined : json['workingDays'],
        'workingDaysInDateInterval': json['workingDaysInDateInterval'] == null ? undefined : json['workingDaysInDateInterval'],
        'remark': json['remark'] == null ? undefined : json['remark'],
        'substitutes': json['substitutes'] == null ? undefined : ((json['substitutes'] as Array<any>).map(PersonBaseDataFromJSON)),
    };
}

export function AbsenceToJSON(json: any): Absence {
    return AbsenceToJSONTyped(json, false);
}

export function AbsenceToJSONTyped(value?: Absence | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'isBeginDateHalfDay': value['isBeginDateHalfDay'],
        'isEndDateHalfDay': value['isEndDateHalfDay'],
        'name': value['name'],
        'number': value['number'],
        'status': value['status'],
        'statusIdentifier': AbsenceStatusToJSON(value['statusIdentifier']),
        'workingDays': value['workingDays'],
        'workingDaysInDateInterval': value['workingDaysInDateInterval'],
        'remark': value['remark'],
        'substitutes': value['substitutes'] == null ? undefined : ((value['substitutes'] as Array<any>).map(PersonBaseDataToJSON)),
    };
}

