/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information detailing an object that can be requested via the HR WORKS-API.
 * @export
 * @interface ApiResourceData
 */
export interface ApiResourceData {
    /**
     * The identifier of the object, with which it can be rquested via the HR WORKS-API.
     * @type {string}
     * @memberof ApiResourceData
     */
    id?: string;
    /**
     * The URL to request the object
     * @type {string}
     * @memberof ApiResourceData
     */
    resourceLocation?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiResourceData
     */
    additionalData?: object;
}

/**
 * Check if a given object implements the ApiResourceData interface.
 */
export function instanceOfApiResourceData(value: object): value is ApiResourceData {
    return true;
}

export function ApiResourceDataFromJSON(json: any): ApiResourceData {
    return ApiResourceDataFromJSONTyped(json, false);
}

export function ApiResourceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResourceData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'resourceLocation': json['resourceLocation'] == null ? undefined : json['resourceLocation'],
        'additionalData': json['additionalData'] == null ? undefined : json['additionalData'],
    };
}

export function ApiResourceDataToJSON(json: any): ApiResourceData {
    return ApiResourceDataToJSONTyped(json, false);
}

export function ApiResourceDataToJSONTyped(value?: ApiResourceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'resourceLocation': value['resourceLocation'],
        'additionalData': value['additionalData'],
    };
}

