/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes a bank account.
 * @export
 * @interface BankAccount
 */
export interface BankAccount {
    /**
     * The bank account's BIC.
     * @type {string}
     * @memberof BankAccount
     */
    bic?: string;
    /**
     * The bank account's IBAN.
     * @type {string}
     * @memberof BankAccount
     */
    iban?: string;
    /**
     * Can be used to set an alternate bank account holder if the account holder's name is not equal to the employee's name.
     * @type {string}
     * @memberof BankAccount
     */
    bankAccountHolder?: string;
}

/**
 * Check if a given object implements the BankAccount interface.
 */
export function instanceOfBankAccount(value: object): value is BankAccount {
    return true;
}

export function BankAccountFromJSON(json: any): BankAccount {
    return BankAccountFromJSONTyped(json, false);
}

export function BankAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'bic': json['bic'] == null ? undefined : json['bic'],
        'iban': json['iban'] == null ? undefined : json['iban'],
        'bankAccountHolder': json['bankAccountHolder'] == null ? undefined : json['bankAccountHolder'],
    };
}

export function BankAccountToJSON(json: any): BankAccount {
    return BankAccountToJSONTyped(json, false);
}

export function BankAccountToJSONTyped(value?: BankAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bic': value['bic'],
        'iban': value['iban'],
        'bankAccountHolder': value['bankAccountHolder'],
    };
}

