/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Time tracking project.
 * @export
 * @interface BaseTimeTrackingProject
 */
export interface BaseTimeTrackingProject {
    /**
     * The name of the time tracking project.
     * @type {string}
     * @memberof BaseTimeTrackingProject
     */
    name?: string;
    /**
     * The id of the project.
     * @type {string}
     * @memberof BaseTimeTrackingProject
     */
    id?: string;
    /**
     * The internal unique number of the project.
     * @type {number}
     * @memberof BaseTimeTrackingProject
     */
    number?: number;
}

/**
 * Check if a given object implements the BaseTimeTrackingProject interface.
 */
export function instanceOfBaseTimeTrackingProject(value: object): value is BaseTimeTrackingProject {
    return true;
}

export function BaseTimeTrackingProjectFromJSON(json: any): BaseTimeTrackingProject {
    return BaseTimeTrackingProjectFromJSONTyped(json, false);
}

export function BaseTimeTrackingProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseTimeTrackingProject {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
        'number': json['number'] == null ? undefined : json['number'],
    };
}

export function BaseTimeTrackingProjectToJSON(json: any): BaseTimeTrackingProject {
    return BaseTimeTrackingProjectToJSONTyped(json, false);
}

export function BaseTimeTrackingProjectToJSONTyped(value?: BaseTimeTrackingProject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'number': value['number'],
    };
}

