/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The representation of a border crossing. Only returned for austrian persons.
 * @export
 * @interface BorderCrossing
 */
export interface BorderCrossing {
    /**
     * The 3-letter country code of the country that was left.
     * @type {string}
     * @memberof BorderCrossing
     */
    originCountryCode?: string;
    /**
     * The 3-letter country code of the country that was entered.
     * @type {string}
     * @memberof BorderCrossing
     */
    destinationCountryCode?: string;
    /**
     * Travel date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof BorderCrossing
     */
    date?: Date;
    /**
     * The time of the border crossing. Time in hh:mm format.
     * @type {string}
     * @memberof BorderCrossing
     */
    time?: string;
}

/**
 * Check if a given object implements the BorderCrossing interface.
 */
export function instanceOfBorderCrossing(value: object): value is BorderCrossing {
    return true;
}

export function BorderCrossingFromJSON(json: any): BorderCrossing {
    return BorderCrossingFromJSONTyped(json, false);
}

export function BorderCrossingFromJSONTyped(json: any, ignoreDiscriminator: boolean): BorderCrossing {
    if (json == null) {
        return json;
    }
    return {
        
        'originCountryCode': json['originCountryCode'] == null ? undefined : json['originCountryCode'],
        'destinationCountryCode': json['destinationCountryCode'] == null ? undefined : json['destinationCountryCode'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'time': json['time'] == null ? undefined : json['time'],
    };
}

export function BorderCrossingToJSON(json: any): BorderCrossing {
    return BorderCrossingToJSONTyped(json, false);
}

export function BorderCrossingToJSONTyped(value?: BorderCrossing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'originCountryCode': value['originCountryCode'],
        'destinationCountryCode': value['destinationCountryCode'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'time': value['time'],
    };
}

