/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CareerLevelKey = {
    NotSpecified: 'notSpecified',
    ApprenticeOrWorkingStudent: 'apprenticeOrWorkingStudent',
    Executive: 'executive',
    Manager: 'manager',
    Professional: 'professional',
    SeniorExecutive: 'seniorExecutive',
    YoungProfessional: 'youngProfessional'
} as const;
export type CareerLevelKey = typeof CareerLevelKey[keyof typeof CareerLevelKey];


export function instanceOfCareerLevelKey(value: any): boolean {
    for (const key in CareerLevelKey) {
        if (Object.prototype.hasOwnProperty.call(CareerLevelKey, key)) {
            if (CareerLevelKey[key as keyof typeof CareerLevelKey] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CareerLevelKeyFromJSON(json: any): CareerLevelKey {
    return CareerLevelKeyFromJSONTyped(json, false);
}

export function CareerLevelKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareerLevelKey {
    return json as CareerLevelKey;
}

export function CareerLevelKeyToJSON(value?: CareerLevelKey | null): any {
    return value as any;
}

export function CareerLevelKeyToJSONTyped(value: any, ignoreDiscriminator: boolean): CareerLevelKey {
    return value as CareerLevelKey;
}

