/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Confession = {
    NoData: 'no data',
    Other: 'other',
    Jewish: 'jewish',
    OldCatholic: 'old catholic',
    Catholic: 'catholic',
    Protestant: 'protestant',
    NotSpecified: 'not specified'
} as const;
export type Confession = typeof Confession[keyof typeof Confession];


export function instanceOfConfession(value: any): boolean {
    for (const key in Confession) {
        if (Object.prototype.hasOwnProperty.call(Confession, key)) {
            if (Confession[key as keyof typeof Confession] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConfessionFromJSON(json: any): Confession {
    return ConfessionFromJSONTyped(json, false);
}

export function ConfessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Confession {
    return json as Confession;
}

export function ConfessionToJSON(value?: Confession | null): any {
    return value as any;
}

export function ConfessionToJSONTyped(value: any, ignoreDiscriminator: boolean): Confession {
    return value as Confession;
}

