/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An assignment of a cost center to either a person or an organization unit.
 * @export
 * @interface CostCenterAssignment
 */
export interface CostCenterAssignment {
    /**
     * The number (identifier) of the cost center.
     * @type {string}
     * @memberof CostCenterAssignment
     */
    number?: string;
    /**
     * Required for person assignments. The identifier of the person to whom the cost center is to be assigned. Use personIdentifierType to specify what type the value is.
     * @type {string}
     * @memberof CostCenterAssignment
     */
    personIdentifier?: string;
    /**
     * Deprecated - use personIdentifier instead. The personnel number of the person to whom the cost center is to be assigned.
     * @type {string}
     * @memberof CostCenterAssignment
     */
    personnelNumber?: string;
    /**
     * Required for organization unit assignments. The number of the organization unit that the cost center is assigned to.
     * @type {string}
     * @memberof CostCenterAssignment
     */
    organizationUnitNumber?: string;
}

/**
 * Check if a given object implements the CostCenterAssignment interface.
 */
export function instanceOfCostCenterAssignment(value: object): value is CostCenterAssignment {
    return true;
}

export function CostCenterAssignmentFromJSON(json: any): CostCenterAssignment {
    return CostCenterAssignmentFromJSONTyped(json, false);
}

export function CostCenterAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CostCenterAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'personIdentifier': json['personIdentifier'] == null ? undefined : json['personIdentifier'],
        'personnelNumber': json['personnelNumber'] == null ? undefined : json['personnelNumber'],
        'organizationUnitNumber': json['organizationUnitNumber'] == null ? undefined : json['organizationUnitNumber'],
    };
}

export function CostCenterAssignmentToJSON(json: any): CostCenterAssignment {
    return CostCenterAssignmentToJSONTyped(json, false);
}

export function CostCenterAssignmentToJSONTyped(value?: CostCenterAssignment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'personIdentifier': value['personIdentifier'],
        'personnelNumber': value['personnelNumber'],
        'organizationUnitNumber': value['organizationUnitNumber'],
    };
}

