/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateSickLeaveData } from './CreateSickLeaveData';
import {
    CreateSickLeaveDataFromJSON,
    CreateSickLeaveDataFromJSONTyped,
    CreateSickLeaveDataToJSON,
    CreateSickLeaveDataToJSONTyped,
} from './CreateSickLeaveData';

/**
 * 
 * @export
 * @interface CreateSickLeavesRequest
 */
export interface CreateSickLeavesRequest {
    /**
     * 
     * @type {Array<CreateSickLeaveData>}
     * @memberof CreateSickLeavesRequest
     */
    data?: Array<CreateSickLeaveData>;
}

/**
 * Check if a given object implements the CreateSickLeavesRequest interface.
 */
export function instanceOfCreateSickLeavesRequest(value: object): value is CreateSickLeavesRequest {
    return true;
}

export function CreateSickLeavesRequestFromJSON(json: any): CreateSickLeavesRequest {
    return CreateSickLeavesRequestFromJSONTyped(json, false);
}

export function CreateSickLeavesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSickLeavesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CreateSickLeaveDataFromJSON)),
    };
}

export function CreateSickLeavesRequestToJSON(json: any): CreateSickLeavesRequest {
    return CreateSickLeavesRequestToJSONTyped(json, false);
}

export function CreateSickLeavesRequestToJSONTyped(value?: CreateSickLeavesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CreateSickLeaveDataToJSON)),
    };
}

