/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookData } from './WebhookData';
import {
    WebhookDataFromJSON,
    WebhookDataFromJSONTyped,
    WebhookDataToJSON,
    WebhookDataToJSONTyped,
} from './WebhookData';

/**
 * 
 * @export
 * @interface CreateWebhooksRequest
 */
export interface CreateWebhooksRequest {
    /**
     * 
     * @type {Array<WebhookData>}
     * @memberof CreateWebhooksRequest
     */
    data?: Array<WebhookData>;
}

/**
 * Check if a given object implements the CreateWebhooksRequest interface.
 */
export function instanceOfCreateWebhooksRequest(value: object): value is CreateWebhooksRequest {
    return true;
}

export function CreateWebhooksRequestFromJSON(json: any): CreateWebhooksRequest {
    return CreateWebhooksRequestFromJSONTyped(json, false);
}

export function CreateWebhooksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhooksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(WebhookDataFromJSON)),
    };
}

export function CreateWebhooksRequestToJSON(json: any): CreateWebhooksRequest {
    return CreateWebhooksRequestToJSONTyped(json, false);
}

export function CreateWebhooksRequestToJSONTyped(value?: CreateWebhooksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(WebhookDataToJSON)),
    };
}

