/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobApplicationData } from './JobApplicationData';
import {
    JobApplicationDataFromJSON,
    JobApplicationDataFromJSONTyped,
    JobApplicationDataToJSON,
    JobApplicationDataToJSONTyped,
} from './JobApplicationData';

/**
 * 
 * @export
 * @interface CreateJobApplicationsRequest
 */
export interface CreateJobApplicationsRequest {
    /**
     * 
     * @type {Array<JobApplicationData>}
     * @memberof CreateJobApplicationsRequest
     */
    data?: Array<JobApplicationData>;
}

/**
 * Check if a given object implements the CreateJobApplicationsRequest interface.
 */
export function instanceOfCreateJobApplicationsRequest(value: object): value is CreateJobApplicationsRequest {
    return true;
}

export function CreateJobApplicationsRequestFromJSON(json: any): CreateJobApplicationsRequest {
    return CreateJobApplicationsRequestFromJSONTyped(json, false);
}

export function CreateJobApplicationsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJobApplicationsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(JobApplicationDataFromJSON)),
    };
}

export function CreateJobApplicationsRequestToJSON(json: any): CreateJobApplicationsRequest {
    return CreateJobApplicationsRequestToJSONTyped(json, false);
}

export function CreateJobApplicationsRequestToJSONTyped(value?: CreateJobApplicationsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(JobApplicationDataToJSON)),
    };
}

