/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookConfiguration } from './WebhookConfiguration';
import {
    WebhookConfigurationFromJSON,
    WebhookConfigurationFromJSONTyped,
    WebhookConfigurationToJSON,
    WebhookConfigurationToJSONTyped,
} from './WebhookConfiguration';

/**
 * 
 * @export
 * @interface CreateOnboardingDocumentFilesRequest
 */
export interface CreateOnboardingDocumentFilesRequest {
    /**
     * 
     * @type {WebhookConfiguration}
     * @memberof CreateOnboardingDocumentFilesRequest
     */
    webhook?: WebhookConfiguration;
}

/**
 * Check if a given object implements the CreateOnboardingDocumentFilesRequest interface.
 */
export function instanceOfCreateOnboardingDocumentFilesRequest(value: object): value is CreateOnboardingDocumentFilesRequest {
    return true;
}

export function CreateOnboardingDocumentFilesRequestFromJSON(json: any): CreateOnboardingDocumentFilesRequest {
    return CreateOnboardingDocumentFilesRequestFromJSONTyped(json, false);
}

export function CreateOnboardingDocumentFilesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOnboardingDocumentFilesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'webhook': json['webhook'] == null ? undefined : WebhookConfigurationFromJSON(json['webhook']),
    };
}

export function CreateOnboardingDocumentFilesRequestToJSON(json: any): CreateOnboardingDocumentFilesRequest {
    return CreateOnboardingDocumentFilesRequestToJSONTyped(json, false);
}

export function CreateOnboardingDocumentFilesRequestToJSONTyped(value?: CreateOnboardingDocumentFilesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhook': WebhookConfigurationToJSON(value['webhook']),
    };
}

