/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AbsenceStatus } from './AbsenceStatus';
import {
    AbsenceStatusFromJSON,
    AbsenceStatusFromJSONTyped,
    AbsenceStatusToJSON,
    AbsenceStatusToJSONTyped,
} from './AbsenceStatus';

/**
 * 
 * @export
 * @interface CreateAbsenceData
 */
export interface CreateAbsenceData {
    /**
     * The short identifier of the absence's type, e.g. "AL" for Annual Leave. The identifiers can be configured in HR WORKS.
     * @type {string}
     * @memberof CreateAbsenceData
     */
    type: string;
    /**
     * The start date of the absence. Date in YYYY-MM-DD format
     * @type {Date}
     * @memberof CreateAbsenceData
     */
    beginDate: Date;
    /**
     * The end date of the absence. Date in YYYY-MM-DD format
     * @type {Date}
     * @memberof CreateAbsenceData
     */
    endDate: Date;
    /**
     * Specifies whether the absence spans only the afternoon of the first day (or only the afternoon for one-day absences).
     * @type {boolean}
     * @memberof CreateAbsenceData
     */
    isBeginDateHalfDay?: boolean;
    /**
     * Specifies whether the absence spans only the forenoon of the last day (or only the forenoon for one-day absences).
     * @type {boolean}
     * @memberof CreateAbsenceData
     */
    isEndDateHalfDay?: boolean;
    /**
     * 
     * @type {AbsenceStatus}
     * @memberof CreateAbsenceData
     */
    status: AbsenceStatus | null;
    /**
     * The personnel numbers of all persons assigned as substitutes for the absence.
     * @type {Array<string>}
     * @memberof CreateAbsenceData
     */
    substitutes?: Array<string>;
    /**
     * The user-entered remark of the absence.
     * @type {string}
     * @memberof CreateAbsenceData
     */
    remark?: string;
    /**
     * The HR WORKS personnel number of the person that the absence should be assigned to.
     * @type {string}
     * @memberof CreateAbsenceData
     */
    personnelNumber: string;
}



/**
 * Check if a given object implements the CreateAbsenceData interface.
 */
export function instanceOfCreateAbsenceData(value: object): value is CreateAbsenceData {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('beginDate' in value) || value['beginDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('personnelNumber' in value) || value['personnelNumber'] === undefined) return false;
    return true;
}

export function CreateAbsenceDataFromJSON(json: any): CreateAbsenceData {
    return CreateAbsenceDataFromJSONTyped(json, false);
}

export function CreateAbsenceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAbsenceData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'beginDate': (new Date(json['beginDate'])),
        'endDate': (new Date(json['endDate'])),
        'isBeginDateHalfDay': json['isBeginDateHalfDay'] == null ? undefined : json['isBeginDateHalfDay'],
        'isEndDateHalfDay': json['isEndDateHalfDay'] == null ? undefined : json['isEndDateHalfDay'],
        'status': AbsenceStatusFromJSON(json['status']),
        'substitutes': json['substitutes'] == null ? undefined : json['substitutes'],
        'remark': json['remark'] == null ? undefined : json['remark'],
        'personnelNumber': json['personnelNumber'],
    };
}

export function CreateAbsenceDataToJSON(json: any): CreateAbsenceData {
    return CreateAbsenceDataToJSONTyped(json, false);
}

export function CreateAbsenceDataToJSONTyped(value?: CreateAbsenceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'beginDate': value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'].toISOString().substring(0,10),
        'isBeginDateHalfDay': value['isBeginDateHalfDay'],
        'isEndDateHalfDay': value['isEndDateHalfDay'],
        'status': AbsenceStatusToJSON(value['status']),
        'substitutes': value['substitutes'],
        'remark': value['remark'],
        'personnelNumber': value['personnelNumber'],
    };
}

