/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CostCenter } from './CostCenter';
import {
    CostCenterFromJSON,
    CostCenterFromJSONTyped,
    CostCenterToJSON,
    CostCenterToJSONTyped,
} from './CostCenter';

/**
 * 
 * @export
 * @interface CreateCostCentersRequest
 */
export interface CreateCostCentersRequest {
    /**
     * 
     * @type {Array<CostCenter>}
     * @memberof CreateCostCentersRequest
     */
    data?: Array<CostCenter>;
}

/**
 * Check if a given object implements the CreateCostCentersRequest interface.
 */
export function instanceOfCreateCostCentersRequest(value: object): value is CreateCostCentersRequest {
    return true;
}

export function CreateCostCentersRequestFromJSON(json: any): CreateCostCentersRequest {
    return CreateCostCentersRequestFromJSONTyped(json, false);
}

export function CreateCostCentersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCostCentersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CostCenterFromJSON)),
    };
}

export function CreateCostCentersRequestToJSON(json: any): CreateCostCentersRequest {
    return CreateCostCentersRequestToJSONTyped(json, false);
}

export function CreateCostCentersRequestToJSONTyped(value?: CreateCostCentersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CostCenterToJSON)),
    };
}

