/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CostCenterAssignment } from './CostCenterAssignment';
import {
    CostCenterAssignmentFromJSON,
    CostCenterAssignmentFromJSONTyped,
    CostCenterAssignmentToJSON,
    CostCenterAssignmentToJSONTyped,
} from './CostCenterAssignment';

/**
 * 
 * @export
 * @interface CreateCostCenterAssignmentsRequest
 */
export interface CreateCostCenterAssignmentsRequest {
    /**
     * 
     * @type {Array<CostCenterAssignment>}
     * @memberof CreateCostCenterAssignmentsRequest
     */
    data?: Array<CostCenterAssignment>;
}

/**
 * Check if a given object implements the CreateCostCenterAssignmentsRequest interface.
 */
export function instanceOfCreateCostCenterAssignmentsRequest(value: object): value is CreateCostCenterAssignmentsRequest {
    return true;
}

export function CreateCostCenterAssignmentsRequestFromJSON(json: any): CreateCostCenterAssignmentsRequest {
    return CreateCostCenterAssignmentsRequestFromJSONTyped(json, false);
}

export function CreateCostCenterAssignmentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCostCenterAssignmentsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CostCenterAssignmentFromJSON)),
    };
}

export function CreateCostCenterAssignmentsRequestToJSON(json: any): CreateCostCenterAssignmentsRequest {
    return CreateCostCenterAssignmentsRequestToJSONTyped(json, false);
}

export function CreateCostCenterAssignmentsRequestToJSONTyped(value?: CreateCostCenterAssignmentsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CostCenterAssignmentToJSON)),
    };
}

