/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateAbsenceData } from './CreateAbsenceData';
import {
    CreateAbsenceDataFromJSON,
    CreateAbsenceDataFromJSONTyped,
    CreateAbsenceDataToJSON,
    CreateAbsenceDataToJSONTyped,
} from './CreateAbsenceData';

/**
 * 
 * @export
 * @interface CreateAbsencesRequest
 */
export interface CreateAbsencesRequest {
    /**
     * 
     * @type {Array<CreateAbsenceData>}
     * @memberof CreateAbsencesRequest
     */
    data?: Array<CreateAbsenceData>;
}

/**
 * Check if a given object implements the CreateAbsencesRequest interface.
 */
export function instanceOfCreateAbsencesRequest(value: object): value is CreateAbsencesRequest {
    return true;
}

export function CreateAbsencesRequestFromJSON(json: any): CreateAbsencesRequest {
    return CreateAbsencesRequestFromJSONTyped(json, false);
}

export function CreateAbsencesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAbsencesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CreateAbsenceDataFromJSON)),
    };
}

export function CreateAbsencesRequestToJSON(json: any): CreateAbsencesRequest {
    return CreateAbsencesRequestToJSONTyped(json, false);
}

export function CreateAbsencesRequestToJSONTyped(value?: CreateAbsencesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CreateAbsenceDataToJSON)),
    };
}

