/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeTrackingProjectData } from './TimeTrackingProjectData';
import {
    TimeTrackingProjectDataFromJSON,
    TimeTrackingProjectDataFromJSONTyped,
    TimeTrackingProjectDataToJSON,
    TimeTrackingProjectDataToJSONTyped,
} from './TimeTrackingProjectData';

/**
 * 
 * @export
 * @interface CreateTimeTrackingProjectsRequest
 */
export interface CreateTimeTrackingProjectsRequest {
    /**
     * 
     * @type {Array<TimeTrackingProjectData>}
     * @memberof CreateTimeTrackingProjectsRequest
     */
    data?: Array<TimeTrackingProjectData>;
}

/**
 * Check if a given object implements the CreateTimeTrackingProjectsRequest interface.
 */
export function instanceOfCreateTimeTrackingProjectsRequest(value: object): value is CreateTimeTrackingProjectsRequest {
    return true;
}

export function CreateTimeTrackingProjectsRequestFromJSON(json: any): CreateTimeTrackingProjectsRequest {
    return CreateTimeTrackingProjectsRequestFromJSONTyped(json, false);
}

export function CreateTimeTrackingProjectsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTimeTrackingProjectsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TimeTrackingProjectDataFromJSON)),
    };
}

export function CreateTimeTrackingProjectsRequestToJSON(json: any): CreateTimeTrackingProjectsRequest {
    return CreateTimeTrackingProjectsRequestToJSONTyped(json, false);
}

export function CreateTimeTrackingProjectsRequestToJSONTyped(value?: CreateTimeTrackingProjectsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TimeTrackingProjectDataToJSON)),
    };
}

