/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonData } from './PersonData';
import {
    PersonDataFromJSON,
    PersonDataFromJSONTyped,
    PersonDataToJSON,
    PersonDataToJSONTyped,
} from './PersonData';

/**
 * 
 * @export
 * @interface EditPersonsRequest
 */
export interface EditPersonsRequest {
    /**
     * 
     * @type {Array<PersonData>}
     * @memberof EditPersonsRequest
     */
    data?: Array<PersonData>;
}

/**
 * Check if a given object implements the EditPersonsRequest interface.
 */
export function instanceOfEditPersonsRequest(value: object): value is EditPersonsRequest {
    return true;
}

export function EditPersonsRequestFromJSON(json: any): EditPersonsRequest {
    return EditPersonsRequestFromJSONTyped(json, false);
}

export function EditPersonsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditPersonsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PersonDataFromJSON)),
    };
}

export function EditPersonsRequestToJSON(json: any): EditPersonsRequest {
    return EditPersonsRequestToJSONTyped(json, false);
}

export function EditPersonsRequestToJSONTyped(value?: EditPersonsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PersonDataToJSON)),
    };
}

