/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SickLeaveType } from './SickLeaveType';
import {
    SickLeaveTypeFromJSON,
    SickLeaveTypeFromJSONTyped,
    SickLeaveTypeToJSON,
    SickLeaveTypeToJSONTyped,
} from './SickLeaveType';

/**
 * 
 * @export
 * @interface EditSickLeaveTypesRequest
 */
export interface EditSickLeaveTypesRequest {
    /**
     * 
     * @type {Array<SickLeaveType>}
     * @memberof EditSickLeaveTypesRequest
     */
    data?: Array<SickLeaveType>;
}

/**
 * Check if a given object implements the EditSickLeaveTypesRequest interface.
 */
export function instanceOfEditSickLeaveTypesRequest(value: object): value is EditSickLeaveTypesRequest {
    return true;
}

export function EditSickLeaveTypesRequestFromJSON(json: any): EditSickLeaveTypesRequest {
    return EditSickLeaveTypesRequestFromJSONTyped(json, false);
}

export function EditSickLeaveTypesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditSickLeaveTypesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SickLeaveTypeFromJSON)),
    };
}

export function EditSickLeaveTypesRequestToJSON(json: any): EditSickLeaveTypesRequest {
    return EditSickLeaveTypesRequestToJSONTyped(json, false);
}

export function EditSickLeaveTypesRequestToJSONTyped(value?: EditSickLeaveTypesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SickLeaveTypeToJSON)),
    };
}

