/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AbsenceType } from './AbsenceType';
import {
    AbsenceTypeFromJSON,
    AbsenceTypeFromJSONTyped,
    AbsenceTypeToJSON,
    AbsenceTypeToJSONTyped,
} from './AbsenceType';

/**
 * 
 * @export
 * @interface EditAbsenceTypesRequest
 */
export interface EditAbsenceTypesRequest {
    /**
     * 
     * @type {Array<AbsenceType>}
     * @memberof EditAbsenceTypesRequest
     */
    data?: Array<AbsenceType>;
}

/**
 * Check if a given object implements the EditAbsenceTypesRequest interface.
 */
export function instanceOfEditAbsenceTypesRequest(value: object): value is EditAbsenceTypesRequest {
    return true;
}

export function EditAbsenceTypesRequestFromJSON(json: any): EditAbsenceTypesRequest {
    return EditAbsenceTypesRequestFromJSONTyped(json, false);
}

export function EditAbsenceTypesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditAbsenceTypesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AbsenceTypeFromJSON)),
    };
}

export function EditAbsenceTypesRequestToJSON(json: any): EditAbsenceTypesRequest {
    return EditAbsenceTypesRequestToJSONTyped(json, false);
}

export function EditAbsenceTypesRequestToJSONTyped(value?: EditAbsenceTypesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AbsenceTypeToJSON)),
    };
}

