/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EditRemoteWorkData } from './EditRemoteWorkData';
import {
    EditRemoteWorkDataFromJSON,
    EditRemoteWorkDataFromJSONTyped,
    EditRemoteWorkDataToJSON,
    EditRemoteWorkDataToJSONTyped,
} from './EditRemoteWorkData';

/**
 * 
 * @export
 * @interface EditRemoteWorkRequest
 */
export interface EditRemoteWorkRequest {
    /**
     * 
     * @type {Array<EditRemoteWorkData>}
     * @memberof EditRemoteWorkRequest
     */
    data?: Array<EditRemoteWorkData>;
}

/**
 * Check if a given object implements the EditRemoteWorkRequest interface.
 */
export function instanceOfEditRemoteWorkRequest(value: object): value is EditRemoteWorkRequest {
    return true;
}

export function EditRemoteWorkRequestFromJSON(json: any): EditRemoteWorkRequest {
    return EditRemoteWorkRequestFromJSONTyped(json, false);
}

export function EditRemoteWorkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditRemoteWorkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EditRemoteWorkDataFromJSON)),
    };
}

export function EditRemoteWorkRequestToJSON(json: any): EditRemoteWorkRequest {
    return EditRemoteWorkRequestToJSONTyped(json, false);
}

export function EditRemoteWorkRequestToJSONTyped(value?: EditRemoteWorkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EditRemoteWorkDataToJSON)),
    };
}

