/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AbsenceStatus } from './AbsenceStatus';
import {
    AbsenceStatusFromJSON,
    AbsenceStatusFromJSONTyped,
    AbsenceStatusToJSON,
    AbsenceStatusToJSONTyped,
} from './AbsenceStatus';

/**
 * 
 * @export
 * @interface EditAbsenceData
 */
export interface EditAbsenceData {
    /**
     * The short identifier of the absence's type, e.g. "AL" for Annual Leave. The identifiers can be configured in HR WORKS.
     * @type {string}
     * @memberof EditAbsenceData
     */
    type?: string;
    /**
     * The start date of the absence. Date in YYYY-MM-DD format
     * @type {Date}
     * @memberof EditAbsenceData
     */
    beginDate?: Date;
    /**
     * The end date of the absence. Date in YYYY-MM-DD format
     * @type {Date}
     * @memberof EditAbsenceData
     */
    endDate?: Date;
    /**
     * Specifies whether the absence spans only the afternoon of the first day (or only the afternoon for one-day absences).
     * @type {boolean}
     * @memberof EditAbsenceData
     */
    isBeginDateHalfDay?: boolean;
    /**
     * Specifies whether the absence spans only the forenoon of the last day (or only the forenoon for one-day absences).
     * @type {boolean}
     * @memberof EditAbsenceData
     */
    isEndDateHalfDay?: boolean;
    /**
     * 
     * @type {AbsenceStatus}
     * @memberof EditAbsenceData
     */
    status?: AbsenceStatus | null;
    /**
     * The personnel numbers of all persons assigned as substitutes for the absence.
     * @type {Array<string>}
     * @memberof EditAbsenceData
     */
    substitutes?: Array<string>;
    /**
     * The user-entered remark of the absence.
     * @type {string}
     * @memberof EditAbsenceData
     */
    remark?: string;
    /**
     * A unique identifier of the absence. Consists of the person's license number before the underscore and the running absence number for the respective person after the underscore.
     * @type {string}
     * @memberof EditAbsenceData
     */
    number: string;
}



/**
 * Check if a given object implements the EditAbsenceData interface.
 */
export function instanceOfEditAbsenceData(value: object): value is EditAbsenceData {
    if (!('number' in value) || value['number'] === undefined) return false;
    return true;
}

export function EditAbsenceDataFromJSON(json: any): EditAbsenceData {
    return EditAbsenceDataFromJSONTyped(json, false);
}

export function EditAbsenceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditAbsenceData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'isBeginDateHalfDay': json['isBeginDateHalfDay'] == null ? undefined : json['isBeginDateHalfDay'],
        'isEndDateHalfDay': json['isEndDateHalfDay'] == null ? undefined : json['isEndDateHalfDay'],
        'status': json['status'] == null ? undefined : AbsenceStatusFromJSON(json['status']),
        'substitutes': json['substitutes'] == null ? undefined : json['substitutes'],
        'remark': json['remark'] == null ? undefined : json['remark'],
        'number': json['number'],
    };
}

export function EditAbsenceDataToJSON(json: any): EditAbsenceData {
    return EditAbsenceDataToJSONTyped(json, false);
}

export function EditAbsenceDataToJSONTyped(value?: EditAbsenceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'isBeginDateHalfDay': value['isBeginDateHalfDay'],
        'isEndDateHalfDay': value['isEndDateHalfDay'],
        'status': AbsenceStatusToJSON(value['status']),
        'substitutes': value['substitutes'],
        'remark': value['remark'],
        'number': value['number'],
    };
}

