/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpenseReportMileagesInner } from './ExpenseReportMileagesInner';
import {
    ExpenseReportMileagesInnerFromJSON,
    ExpenseReportMileagesInnerFromJSONTyped,
    ExpenseReportMileagesInnerToJSON,
    ExpenseReportMileagesInnerToJSONTyped,
} from './ExpenseReportMileagesInner';
import type { CostObjective } from './CostObjective';
import {
    CostObjectiveFromJSON,
    CostObjectiveFromJSONTyped,
    CostObjectiveToJSON,
    CostObjectiveToJSONTyped,
} from './CostObjective';
import type { ExpenseReportDay } from './ExpenseReportDay';
import {
    ExpenseReportDayFromJSON,
    ExpenseReportDayFromJSONTyped,
    ExpenseReportDayToJSON,
    ExpenseReportDayToJSONTyped,
} from './ExpenseReportDay';
import type { Receipt } from './Receipt';
import {
    ReceiptFromJSON,
    ReceiptFromJSONTyped,
    ReceiptToJSON,
    ReceiptToJSONTyped,
} from './Receipt';
import type { CostCenter } from './CostCenter';
import {
    CostCenterFromJSON,
    CostCenterFromJSONTyped,
    CostCenterToJSON,
    CostCenterToJSONTyped,
} from './CostCenter';
import type { BorderCrossing } from './BorderCrossing';
import {
    BorderCrossingFromJSON,
    BorderCrossingFromJSONTyped,
    BorderCrossingToJSON,
    BorderCrossingToJSONTyped,
} from './BorderCrossing';
import type { CurrencyValue } from './CurrencyValue';
import {
    CurrencyValueFromJSON,
    CurrencyValueFromJSONTyped,
    CurrencyValueToJSON,
    CurrencyValueToJSONTyped,
} from './CurrencyValue';
import type { ExpenseReportStatus } from './ExpenseReportStatus';
import {
    ExpenseReportStatusFromJSON,
    ExpenseReportStatusFromJSONTyped,
    ExpenseReportStatusToJSON,
    ExpenseReportStatusToJSONTyped,
} from './ExpenseReportStatus';
import type { PersonBaseData } from './PersonBaseData';
import {
    PersonBaseDataFromJSON,
    PersonBaseDataFromJSONTyped,
    PersonBaseDataToJSON,
    PersonBaseDataToJSONTyped,
} from './PersonBaseData';

/**
 * 
 * @export
 * @interface ExpenseReport
 */
export interface ExpenseReport {
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReport
     */
    advancesSum?: CurrencyValue;
    /**
     * The start date of the expense report. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof ExpenseReport
     */
    beginDate?: Date;
    /**
     * The start time of the expense report. Time in hh:mm format.
     * @type {string}
     * @memberof ExpenseReport
     */
    beginTime?: string;
    /**
     * 
     * @type {CostCenter}
     * @memberof ExpenseReport
     */
    costCenter?: CostCenter;
    /**
     * 
     * @type {CostObjective}
     * @memberof ExpenseReport
     */
    costObjective?: CostObjective;
    /**
     * 
     * @type {Array<ExpenseReportDay>}
     * @memberof ExpenseReport
     */
    days?: Array<ExpenseReportDay>;
    /**
     * The default payment type for the trip. Used for mileages and per diems. Receipts may have differing payment types.
     * @type {string}
     * @memberof ExpenseReport
     */
    defaultPaymentType?: string;
    /**
     * The travelling destination of the business trip.
     * @type {string}
     * @memberof ExpenseReport
     */
    destination?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExpenseReport
     */
    receiptDocuments?: Array<string>;
    /**
     * The end date of the expense report. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof ExpenseReport
     */
    endDate?: Date;
    /**
     * The end time of the expense report. Time in hh:mm format.
     * @type {string}
     * @memberof ExpenseReport
     */
    endTime?: string;
    /**
     * Boolean denoting whether the object is a collection of receipts (true) oder a full expense report for an actual trip (false).
     * @type {boolean}
     * @memberof ExpenseReport
     */
    isExpenseReport?: boolean;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReport
     */
    lodgingPerDiemsSum?: CurrencyValue;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReport
     */
    mealsDeductionSum?: CurrencyValue;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReport
     */
    mealsPerDiemsSum?: CurrencyValue;
    /**
     * Data detailing distances traveled by car or other vehicles during the business trip.
     * @type {Array<ExpenseReportMileagesInner>}
     * @memberof ExpenseReport
     */
    mileages?: Array<ExpenseReportMileagesInner>;
    /**
     * The title of the expense report.
     * @type {string}
     * @memberof ExpenseReport
     */
    name?: string;
    /**
     * A unique identifier of the expense report. Consists of the personnel number of the person associated with the expense report and the running per-person expense report number.
     * @type {string}
     * @memberof ExpenseReport
     */
    number?: string;
    /**
     * Boolean denoting whether the expense report includes an overnight stay after the first day of travelling. Only returned for German expense reports.
     * @type {boolean}
     * @memberof ExpenseReport
     */
    overnightStayAfterFirstDay?: boolean;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReport
     */
    paymentSum?: CurrencyValue;
    /**
     * 
     * @type {PersonBaseData}
     * @memberof ExpenseReport
     */
    person?: PersonBaseData;
    /**
     * 
     * @type {Array<Receipt>}
     * @memberof ExpenseReport
     */
    receipts?: Array<Receipt>;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReport
     */
    receiptSum?: CurrencyValue;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReport
     */
    reducedPaymentValueSum?: CurrencyValue;
    /**
     * A number that can be set during the travel expenses export in HR WORKS as the head number (number per account) or position number (number per trip).
     * @type {number}
     * @memberof ExpenseReport
     */
    reference?: number;
    /**
     * The location where the business trip started.
     * @type {string}
     * @memberof ExpenseReport
     */
    startLocation?: string;
    /**
     * The status of the expense report, e.g. Checked, OK.
     * @type {string}
     * @memberof ExpenseReport
     */
    status?: string;
    /**
     * 
     * @type {ExpenseReportStatus}
     * @memberof ExpenseReport
     */
    statusIdentifier?: ExpenseReportStatus | null;
    /**
     * Comma-separated names of stopovers
     * @type {string}
     * @memberof ExpenseReport
     */
    stopovers?: string;
    /**
     * Boolean denoting whether the three-month rule is active for the expense report. Only returned for German expense reports.
     * @type {boolean}
     * @memberof ExpenseReport
     */
    threeMonthsRuleActive?: boolean;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReport
     */
    totalSum?: CurrencyValue;
    /**
     * Boolean denoting whether the expense report is assigned to a client. Only returned if the Ingentis InTime integration is active.
     * @type {boolean}
     * @memberof ExpenseReport
     */
    clientRelatedTrip?: boolean;
    /**
     * Order number for DATEV EO. Only returned if the Ingentis InTime integration is active.
     * @type {string}
     * @memberof ExpenseReport
     */
    orderNumberDatevEO?: string;
    /**
     * Only returned for Austrian persons. A collection of all inter-country travels during the business trip.
     * @type {Array<BorderCrossing>}
     * @memberof ExpenseReport
     */
    borderCrossings?: Array<BorderCrossing>;
}



/**
 * Check if a given object implements the ExpenseReport interface.
 */
export function instanceOfExpenseReport(value: object): value is ExpenseReport {
    return true;
}

export function ExpenseReportFromJSON(json: any): ExpenseReport {
    return ExpenseReportFromJSONTyped(json, false);
}

export function ExpenseReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseReport {
    if (json == null) {
        return json;
    }
    return {
        
        'advancesSum': json['advancesSum'] == null ? undefined : CurrencyValueFromJSON(json['advancesSum']),
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'beginTime': json['beginTime'] == null ? undefined : json['beginTime'],
        'costCenter': json['costCenter'] == null ? undefined : CostCenterFromJSON(json['costCenter']),
        'costObjective': json['costObjective'] == null ? undefined : CostObjectiveFromJSON(json['costObjective']),
        'days': json['days'] == null ? undefined : ((json['days'] as Array<any>).map(ExpenseReportDayFromJSON)),
        'defaultPaymentType': json['defaultPaymentType'] == null ? undefined : json['defaultPaymentType'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'receiptDocuments': json['receiptDocuments'] == null ? undefined : json['receiptDocuments'],
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'isExpenseReport': json['isExpenseReport'] == null ? undefined : json['isExpenseReport'],
        'lodgingPerDiemsSum': json['lodgingPerDiemsSum'] == null ? undefined : CurrencyValueFromJSON(json['lodgingPerDiemsSum']),
        'mealsDeductionSum': json['mealsDeductionSum'] == null ? undefined : CurrencyValueFromJSON(json['mealsDeductionSum']),
        'mealsPerDiemsSum': json['mealsPerDiemsSum'] == null ? undefined : CurrencyValueFromJSON(json['mealsPerDiemsSum']),
        'mileages': json['mileages'] == null ? undefined : ((json['mileages'] as Array<any>).map(ExpenseReportMileagesInnerFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'number': json['number'] == null ? undefined : json['number'],
        'overnightStayAfterFirstDay': json['overnightStayAfterFirstDay'] == null ? undefined : json['overnightStayAfterFirstDay'],
        'paymentSum': json['paymentSum'] == null ? undefined : CurrencyValueFromJSON(json['paymentSum']),
        'person': json['person'] == null ? undefined : PersonBaseDataFromJSON(json['person']),
        'receipts': json['receipts'] == null ? undefined : ((json['receipts'] as Array<any>).map(ReceiptFromJSON)),
        'receiptSum': json['receiptSum'] == null ? undefined : CurrencyValueFromJSON(json['receiptSum']),
        'reducedPaymentValueSum': json['reducedPaymentValueSum'] == null ? undefined : CurrencyValueFromJSON(json['reducedPaymentValueSum']),
        'reference': json['reference'] == null ? undefined : json['reference'],
        'startLocation': json['startLocation'] == null ? undefined : json['startLocation'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusIdentifier': json['statusIdentifier'] == null ? undefined : ExpenseReportStatusFromJSON(json['statusIdentifier']),
        'stopovers': json['stopovers'] == null ? undefined : json['stopovers'],
        'threeMonthsRuleActive': json['threeMonthsRuleActive'] == null ? undefined : json['threeMonthsRuleActive'],
        'totalSum': json['totalSum'] == null ? undefined : CurrencyValueFromJSON(json['totalSum']),
        'clientRelatedTrip': json['clientRelatedTrip'] == null ? undefined : json['clientRelatedTrip'],
        'orderNumberDatevEO': json['orderNumberDatevEO'] == null ? undefined : json['orderNumberDatevEO'],
        'borderCrossings': json['borderCrossings'] == null ? undefined : ((json['borderCrossings'] as Array<any>).map(BorderCrossingFromJSON)),
    };
}

export function ExpenseReportToJSON(json: any): ExpenseReport {
    return ExpenseReportToJSONTyped(json, false);
}

export function ExpenseReportToJSONTyped(value?: ExpenseReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advancesSum': CurrencyValueToJSON(value['advancesSum']),
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'beginTime': value['beginTime'],
        'costCenter': CostCenterToJSON(value['costCenter']),
        'costObjective': CostObjectiveToJSON(value['costObjective']),
        'days': value['days'] == null ? undefined : ((value['days'] as Array<any>).map(ExpenseReportDayToJSON)),
        'defaultPaymentType': value['defaultPaymentType'],
        'destination': value['destination'],
        'receiptDocuments': value['receiptDocuments'],
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'endTime': value['endTime'],
        'isExpenseReport': value['isExpenseReport'],
        'lodgingPerDiemsSum': CurrencyValueToJSON(value['lodgingPerDiemsSum']),
        'mealsDeductionSum': CurrencyValueToJSON(value['mealsDeductionSum']),
        'mealsPerDiemsSum': CurrencyValueToJSON(value['mealsPerDiemsSum']),
        'mileages': value['mileages'] == null ? undefined : ((value['mileages'] as Array<any>).map(ExpenseReportMileagesInnerToJSON)),
        'name': value['name'],
        'number': value['number'],
        'overnightStayAfterFirstDay': value['overnightStayAfterFirstDay'],
        'paymentSum': CurrencyValueToJSON(value['paymentSum']),
        'person': PersonBaseDataToJSON(value['person']),
        'receipts': value['receipts'] == null ? undefined : ((value['receipts'] as Array<any>).map(ReceiptToJSON)),
        'receiptSum': CurrencyValueToJSON(value['receiptSum']),
        'reducedPaymentValueSum': CurrencyValueToJSON(value['reducedPaymentValueSum']),
        'reference': value['reference'],
        'startLocation': value['startLocation'],
        'status': value['status'],
        'statusIdentifier': ExpenseReportStatusToJSON(value['statusIdentifier']),
        'stopovers': value['stopovers'],
        'threeMonthsRuleActive': value['threeMonthsRuleActive'],
        'totalSum': CurrencyValueToJSON(value['totalSum']),
        'clientRelatedTrip': value['clientRelatedTrip'],
        'orderNumberDatevEO': value['orderNumberDatevEO'],
        'borderCrossings': value['borderCrossings'] == null ? undefined : ((value['borderCrossings'] as Array<any>).map(BorderCrossingToJSON)),
    };
}

