/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrencyValue } from './CurrencyValue';
import {
    CurrencyValueFromJSON,
    CurrencyValueFromJSONTyped,
    CurrencyValueToJSON,
    CurrencyValueToJSONTyped,
} from './CurrencyValue';
import type { CostObjectPercentage } from './CostObjectPercentage';
import {
    CostObjectPercentageFromJSON,
    CostObjectPercentageFromJSONTyped,
    CostObjectPercentageToJSON,
    CostObjectPercentageToJSONTyped,
} from './CostObjectPercentage';

/**
 * 
 * @export
 * @interface ExpenseReportDay
 */
export interface ExpenseReportDay {
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReportDay
     */
    breakfastDeduction?: CurrencyValue;
    /**
     * Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof ExpenseReportDay
     */
    date?: Date;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReportDay
     */
    dinnerDeduction?: CurrencyValue;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReportDay
     */
    lodgingPerDiems?: CurrencyValue;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReportDay
     */
    lunchDeduction?: CurrencyValue;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReportDay
     */
    mealsDeductionSum?: CurrencyValue;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReportDay
     */
    mealsPerDiems?: CurrencyValue;
    /**
     * The 3-digit country code corresponding to the country the day was spent in.
     * @type {string}
     * @memberof ExpenseReportDay
     */
    countryCode?: string;
    /**
     * The 3-digit country code corresponding to the overnight stay country.
     * @type {string}
     * @memberof ExpenseReportDay
     */
    overnightStayCountryCode?: string;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReportDay
     */
    paymentSum?: CurrencyValue;
    /**
     * The percentage allocation of the day for the defined cost objectives and cost centres.
     * @type {Array<CostObjectPercentage>}
     * @memberof ExpenseReportDay
     */
    percentageAllocation?: Array<CostObjectPercentage>;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof ExpenseReportDay
     */
    benefitsInKindSum?: CurrencyValue;
}

/**
 * Check if a given object implements the ExpenseReportDay interface.
 */
export function instanceOfExpenseReportDay(value: object): value is ExpenseReportDay {
    return true;
}

export function ExpenseReportDayFromJSON(json: any): ExpenseReportDay {
    return ExpenseReportDayFromJSONTyped(json, false);
}

export function ExpenseReportDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseReportDay {
    if (json == null) {
        return json;
    }
    return {
        
        'breakfastDeduction': json['breakfastDeduction'] == null ? undefined : CurrencyValueFromJSON(json['breakfastDeduction']),
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'dinnerDeduction': json['dinnerDeduction'] == null ? undefined : CurrencyValueFromJSON(json['dinnerDeduction']),
        'lodgingPerDiems': json['lodgingPerDiems'] == null ? undefined : CurrencyValueFromJSON(json['lodgingPerDiems']),
        'lunchDeduction': json['lunchDeduction'] == null ? undefined : CurrencyValueFromJSON(json['lunchDeduction']),
        'mealsDeductionSum': json['mealsDeductionSum'] == null ? undefined : CurrencyValueFromJSON(json['mealsDeductionSum']),
        'mealsPerDiems': json['mealsPerDiems'] == null ? undefined : CurrencyValueFromJSON(json['mealsPerDiems']),
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'overnightStayCountryCode': json['overnightStayCountryCode'] == null ? undefined : json['overnightStayCountryCode'],
        'paymentSum': json['paymentSum'] == null ? undefined : CurrencyValueFromJSON(json['paymentSum']),
        'percentageAllocation': json['percentageAllocation'] == null ? undefined : ((json['percentageAllocation'] as Array<any>).map(CostObjectPercentageFromJSON)),
        'benefitsInKindSum': json['benefitsInKindSum'] == null ? undefined : CurrencyValueFromJSON(json['benefitsInKindSum']),
    };
}

export function ExpenseReportDayToJSON(json: any): ExpenseReportDay {
    return ExpenseReportDayToJSONTyped(json, false);
}

export function ExpenseReportDayToJSONTyped(value?: ExpenseReportDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'breakfastDeduction': CurrencyValueToJSON(value['breakfastDeduction']),
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'dinnerDeduction': CurrencyValueToJSON(value['dinnerDeduction']),
        'lodgingPerDiems': CurrencyValueToJSON(value['lodgingPerDiems']),
        'lunchDeduction': CurrencyValueToJSON(value['lunchDeduction']),
        'mealsDeductionSum': CurrencyValueToJSON(value['mealsDeductionSum']),
        'mealsPerDiems': CurrencyValueToJSON(value['mealsPerDiems']),
        'countryCode': value['countryCode'],
        'overnightStayCountryCode': value['overnightStayCountryCode'],
        'paymentSum': CurrencyValueToJSON(value['paymentSum']),
        'percentageAllocation': value['percentageAllocation'] == null ? undefined : ((value['percentageAllocation'] as Array<any>).map(CostObjectPercentageToJSON)),
        'benefitsInKindSum': CurrencyValueToJSON(value['benefitsInKindSum']),
    };
}

