/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An expenses group for travel expenses accounting.
 * @export
 * @interface ExpensesGroup
 */
export interface ExpensesGroup {
    /**
     * The unique identifier of the expenses group.
     * @type {string}
     * @memberof ExpensesGroup
     */
    key?: string;
    /**
     * The name of the expenses group.
     * @type {string}
     * @memberof ExpensesGroup
     */
    name?: string;
    /**
     * The country associated with the expenses group. Given as a 3-digit country code.
     * @type {string}
     * @memberof ExpensesGroup
     */
    internationalCountryCode?: string;
}

/**
 * Check if a given object implements the ExpensesGroup interface.
 */
export function instanceOfExpensesGroup(value: object): value is ExpensesGroup {
    return true;
}

export function ExpensesGroupFromJSON(json: any): ExpensesGroup {
    return ExpensesGroupFromJSONTyped(json, false);
}

export function ExpensesGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpensesGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
        'internationalCountryCode': json['internationalCountryCode'] == null ? undefined : json['internationalCountryCode'],
    };
}

export function ExpensesGroupToJSON(json: any): ExpensesGroup {
    return ExpensesGroupToJSONTyped(json, false);
}

export function ExpensesGroupToJSONTyped(value?: ExpensesGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'name': value['name'],
        'internationalCountryCode': value['internationalCountryCode'],
    };
}

