/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpenseReport } from './ExpenseReport';
import {
    ExpenseReportFromJSON,
    ExpenseReportFromJSONTyped,
    ExpenseReportToJSON,
    ExpenseReportToJSONTyped,
} from './ExpenseReport';

/**
 * JSON object representing a date interval with the associated expense reports.
 * @export
 * @interface ExpenseReportsDateIntervalData
 */
export interface ExpenseReportsDateIntervalData {
    /**
     * 
     * @type {Date}
     * @memberof ExpenseReportsDateIntervalData
     */
    beginDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ExpenseReportsDateIntervalData
     */
    endDate?: Date;
    /**
     * 
     * @type {Array<ExpenseReport>}
     * @memberof ExpenseReportsDateIntervalData
     */
    expenseReports?: Array<ExpenseReport>;
}

/**
 * Check if a given object implements the ExpenseReportsDateIntervalData interface.
 */
export function instanceOfExpenseReportsDateIntervalData(value: object): value is ExpenseReportsDateIntervalData {
    return true;
}

export function ExpenseReportsDateIntervalDataFromJSON(json: any): ExpenseReportsDateIntervalData {
    return ExpenseReportsDateIntervalDataFromJSONTyped(json, false);
}

export function ExpenseReportsDateIntervalDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseReportsDateIntervalData {
    if (json == null) {
        return json;
    }
    return {
        
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'expenseReports': json['expenseReports'] == null ? undefined : ((json['expenseReports'] as Array<any>).map(ExpenseReportFromJSON)),
    };
}

export function ExpenseReportsDateIntervalDataToJSON(json: any): ExpenseReportsDateIntervalData {
    return ExpenseReportsDateIntervalDataToJSONTyped(json, false);
}

export function ExpenseReportsDateIntervalDataToJSONTyped(value?: ExpenseReportsDateIntervalData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'expenseReports': value['expenseReports'] == null ? undefined : ((value['expenseReports'] as Array<any>).map(ExpenseReportToJSON)),
    };
}

