/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlatRateType
 */
export interface FlatRateType {
    /**
     * The number of the account assigned to the flat rate type.
     * @type {string}
     * @memberof FlatRateType
     */
    accountNumber?: string;
    /**
     * The name/short description of the flat rate type.
     * @type {string}
     * @memberof FlatRateType
     */
    description?: string;
}

/**
 * Check if a given object implements the FlatRateType interface.
 */
export function instanceOfFlatRateType(value: object): value is FlatRateType {
    return true;
}

export function FlatRateTypeFromJSON(json: any): FlatRateType {
    return FlatRateTypeFromJSONTyped(json, false);
}

export function FlatRateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlatRateType {
    if (json == null) {
        return json;
    }
    return {
        
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function FlatRateTypeToJSON(json: any): FlatRateType {
    return FlatRateTypeToJSONTyped(json, false);
}

export function FlatRateTypeToJSONTyped(value?: FlatRateType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountNumber': value['accountNumber'],
        'description': value['description'],
    };
}

