/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FileUploadRequestResponse } from './FileUploadRequestResponse';
import {
    instanceOfFileUploadRequestResponse,
    FileUploadRequestResponseFromJSON,
    FileUploadRequestResponseFromJSONTyped,
    FileUploadRequestResponseToJSON,
} from './FileUploadRequestResponse';
import type { MultiWriteRequestResponse } from './MultiWriteRequestResponse';
import {
    instanceOfMultiWriteRequestResponse,
    MultiWriteRequestResponseFromJSON,
    MultiWriteRequestResponseFromJSONTyped,
    MultiWriteRequestResponseToJSON,
} from './MultiWriteRequestResponse';

/**
 * @type GetEditPersonsStatus200Response
 * 
 * @export
 */
export type GetEditPersonsStatus200Response = ;

export function GetEditPersonsStatus200ResponseFromJSON(json: any): GetEditPersonsStatus200Response {
    return GetEditPersonsStatus200ResponseFromJSONTyped(json, false);
}

export function GetEditPersonsStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEditPersonsStatus200Response {
    if (json == null) {
        return json;
    }
    switch (json['responseType']) {
        default:
            return json;
    }
}

export function GetEditPersonsStatus200ResponseToJSON(json: any): any {
    return GetEditPersonsStatus200ResponseToJSONTyped(json, false);
}

export function GetEditPersonsStatus200ResponseToJSONTyped(value?: GetEditPersonsStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['responseType']) {
        default:
            return value;
    }
}

