/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MultiDeleteRequestResponse } from './MultiDeleteRequestResponse';
import {
    instanceOfMultiDeleteRequestResponse,
    MultiDeleteRequestResponseFromJSON,
    MultiDeleteRequestResponseFromJSONTyped,
    MultiDeleteRequestResponseToJSON,
} from './MultiDeleteRequestResponse';
import type { MultiWriteRequestResponse } from './MultiWriteRequestResponse';
import {
    instanceOfMultiWriteRequestResponse,
    MultiWriteRequestResponseFromJSON,
    MultiWriteRequestResponseFromJSONTyped,
    MultiWriteRequestResponseToJSON,
} from './MultiWriteRequestResponse';
import type { SingleDeleteRequestResponse } from './SingleDeleteRequestResponse';
import {
    instanceOfSingleDeleteRequestResponse,
    SingleDeleteRequestResponseFromJSON,
    SingleDeleteRequestResponseFromJSONTyped,
    SingleDeleteRequestResponseToJSON,
} from './SingleDeleteRequestResponse';

/**
 * @type GetEditAbsencesStatus200Response
 * 
 * @export
 */
export type GetEditAbsencesStatus200Response = ;

export function GetEditAbsencesStatus200ResponseFromJSON(json: any): GetEditAbsencesStatus200Response {
    return GetEditAbsencesStatus200ResponseFromJSONTyped(json, false);
}

export function GetEditAbsencesStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEditAbsencesStatus200Response {
    if (json == null) {
        return json;
    }
    switch (json['responseType']) {
        default:
            return json;
    }
}

export function GetEditAbsencesStatus200ResponseToJSON(json: any): any {
    return GetEditAbsencesStatus200ResponseToJSONTyped(json, false);
}

export function GetEditAbsencesStatus200ResponseToJSONTyped(value?: GetEditAbsencesStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['responseType']) {
        default:
            return value;
    }
}

