/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Person } from './Person';
import {
    PersonFromJSON,
    PersonFromJSONTyped,
    PersonToJSON,
    PersonToJSONTyped,
} from './Person';

/**
 * 
 * @export
 * @interface GetPersonMasterDataResponse
 */
export interface GetPersonMasterDataResponse {
    /**
     * 
     * @type {Array<Person>}
     * @memberof GetPersonMasterDataResponse
     */
    persons?: Array<Person>;
}

/**
 * Check if a given object implements the GetPersonMasterDataResponse interface.
 */
export function instanceOfGetPersonMasterDataResponse(value: object): value is GetPersonMasterDataResponse {
    return true;
}

export function GetPersonMasterDataResponseFromJSON(json: any): GetPersonMasterDataResponse {
    return GetPersonMasterDataResponseFromJSONTyped(json, false);
}

export function GetPersonMasterDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPersonMasterDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'persons': json['persons'] == null ? undefined : ((json['persons'] as Array<any>).map(PersonFromJSON)),
    };
}

export function GetPersonMasterDataResponseToJSON(json: any): GetPersonMasterDataResponse {
    return GetPersonMasterDataResponseToJSONTyped(json, false);
}

export function GetPersonMasterDataResponseToJSONTyped(value?: GetPersonMasterDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'persons': value['persons'] == null ? undefined : ((value['persons'] as Array<any>).map(PersonToJSON)),
    };
}

