/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeTrackingProjectCustomer } from './TimeTrackingProjectCustomer';
import {
    TimeTrackingProjectCustomerFromJSON,
    TimeTrackingProjectCustomerFromJSONTyped,
    TimeTrackingProjectCustomerToJSON,
    TimeTrackingProjectCustomerToJSONTyped,
} from './TimeTrackingProjectCustomer';

/**
 * 
 * @export
 * @interface GetTimeTrackingProjectCustomersResponse
 */
export interface GetTimeTrackingProjectCustomersResponse {
    /**
     * 
     * @type {Array<TimeTrackingProjectCustomer>}
     * @memberof GetTimeTrackingProjectCustomersResponse
     */
    customers?: Array<TimeTrackingProjectCustomer>;
}

/**
 * Check if a given object implements the GetTimeTrackingProjectCustomersResponse interface.
 */
export function instanceOfGetTimeTrackingProjectCustomersResponse(value: object): value is GetTimeTrackingProjectCustomersResponse {
    return true;
}

export function GetTimeTrackingProjectCustomersResponseFromJSON(json: any): GetTimeTrackingProjectCustomersResponse {
    return GetTimeTrackingProjectCustomersResponseFromJSONTyped(json, false);
}

export function GetTimeTrackingProjectCustomersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTimeTrackingProjectCustomersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'customers': json['customers'] == null ? undefined : ((json['customers'] as Array<any>).map(TimeTrackingProjectCustomerFromJSON)),
    };
}

export function GetTimeTrackingProjectCustomersResponseToJSON(json: any): GetTimeTrackingProjectCustomersResponse {
    return GetTimeTrackingProjectCustomersResponseToJSONTyped(json, false);
}

export function GetTimeTrackingProjectCustomersResponseToJSONTyped(value?: GetTimeTrackingProjectCustomersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customers': value['customers'] == null ? undefined : ((value['customers'] as Array<any>).map(TimeTrackingProjectCustomerToJSON)),
    };
}

