/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Holiday } from './Holiday';
import {
    HolidayFromJSON,
    HolidayFromJSONTyped,
    HolidayToJSON,
    HolidayToJSONTyped,
} from './Holiday';

/**
 * 
 * @export
 * @interface HolidaysByCountryWrapper
 */
export interface HolidaysByCountryWrapper {
    /**
     * 
     * @type {{ [key: string]: Array<Holiday>; }}
     * @memberof HolidaysByCountryWrapper
     */
    permanentEstablishmentHolidays?: { [key: string]: Array<Holiday>; };
    /**
     * 
     * @type {{ [key: string]: Array<Holiday>; }}
     * @memberof HolidaysByCountryWrapper
     */
    stateHolidays?: { [key: string]: Array<Holiday>; };
    /**
     * 
     * @type {Array<Holiday>}
     * @memberof HolidaysByCountryWrapper
     */
    generalHolidays?: Array<Holiday>;
}

/**
 * Check if a given object implements the HolidaysByCountryWrapper interface.
 */
export function instanceOfHolidaysByCountryWrapper(value: object): value is HolidaysByCountryWrapper {
    return true;
}

export function HolidaysByCountryWrapperFromJSON(json: any): HolidaysByCountryWrapper {
    return HolidaysByCountryWrapperFromJSONTyped(json, false);
}

export function HolidaysByCountryWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): HolidaysByCountryWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'permanentEstablishmentHolidays': json['permanentEstablishmentHolidays'] == null ? undefined : json['permanentEstablishmentHolidays'],
        'stateHolidays': json['stateHolidays'] == null ? undefined : json['stateHolidays'],
        'generalHolidays': json['generalHolidays'] == null ? undefined : ((json['generalHolidays'] as Array<any>).map(HolidayFromJSON)),
    };
}

export function HolidaysByCountryWrapperToJSON(json: any): HolidaysByCountryWrapper {
    return HolidaysByCountryWrapperToJSONTyped(json, false);
}

export function HolidaysByCountryWrapperToJSONTyped(value?: HolidaysByCountryWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permanentEstablishmentHolidays': value['permanentEstablishmentHolidays'],
        'stateHolidays': value['stateHolidays'],
        'generalHolidays': value['generalHolidays'] == null ? undefined : ((value['generalHolidays'] as Array<any>).map(HolidayToJSON)),
    };
}

