/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const IncludeDataForPersonsDayRequest = {
    WorkingTimes: 'workingTimes',
    RemoteWork: 'remoteWork',
    TravelRequests: 'travelRequests',
    ExpenseReports: 'expenseReports'
} as const;
export type IncludeDataForPersonsDayRequest = typeof IncludeDataForPersonsDayRequest[keyof typeof IncludeDataForPersonsDayRequest];


export function instanceOfIncludeDataForPersonsDayRequest(value: any): boolean {
    for (const key in IncludeDataForPersonsDayRequest) {
        if (Object.prototype.hasOwnProperty.call(IncludeDataForPersonsDayRequest, key)) {
            if (IncludeDataForPersonsDayRequest[key as keyof typeof IncludeDataForPersonsDayRequest] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IncludeDataForPersonsDayRequestFromJSON(json: any): IncludeDataForPersonsDayRequest {
    return IncludeDataForPersonsDayRequestFromJSONTyped(json, false);
}

export function IncludeDataForPersonsDayRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncludeDataForPersonsDayRequest {
    return json as IncludeDataForPersonsDayRequest;
}

export function IncludeDataForPersonsDayRequestToJSON(value?: IncludeDataForPersonsDayRequest | null): any {
    return value as any;
}

export function IncludeDataForPersonsDayRequestToJSONTyped(value: any, ignoreDiscriminator: boolean): IncludeDataForPersonsDayRequest {
    return value as IncludeDataForPersonsDayRequest;
}

