/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Interval = {
    Days: 'days',
    Weeks: 'weeks',
    Months: 'months'
} as const;
export type Interval = typeof Interval[keyof typeof Interval];


export function instanceOfInterval(value: any): boolean {
    for (const key in Interval) {
        if (Object.prototype.hasOwnProperty.call(Interval, key)) {
            if (Interval[key as keyof typeof Interval] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IntervalFromJSON(json: any): Interval {
    return IntervalFromJSONTyped(json, false);
}

export function IntervalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Interval {
    return json as Interval;
}

export function IntervalToJSON(value?: Interval | null): any {
    return value as any;
}

export function IntervalToJSONTyped(value: any, ignoreDiscriminator: boolean): Interval {
    return value as Interval;
}

