/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Write requests to the API are handled asynchronously. The initial call returns a job ID on success.
 * @export
 * @interface JobIdObject
 */
export interface JobIdObject {
    /**
     * A GUID referencing the write request. Can be used for calls to the respective /jobs endpoint.
     * @type {string}
     * @memberof JobIdObject
     */
    jobId?: string;
}

/**
 * Check if a given object implements the JobIdObject interface.
 */
export function instanceOfJobIdObject(value: object): value is JobIdObject {
    return true;
}

export function JobIdObjectFromJSON(json: any): JobIdObject {
    return JobIdObjectFromJSONTyped(json, false);
}

export function JobIdObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobIdObject {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
    };
}

export function JobIdObjectToJSON(json: any): JobIdObject {
    return JobIdObjectToJSONTyped(json, false);
}

export function JobIdObjectToJSONTyped(value?: JobIdObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
    };
}

