/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReceiptType } from './ReceiptType';
import {
    ReceiptTypeFromJSON,
    ReceiptTypeFromJSONTyped,
    ReceiptTypeToJSON,
    ReceiptTypeToJSONTyped,
} from './ReceiptType';

/**
 * 
 * @export
 * @interface ListReceiptTypesResponse
 */
export interface ListReceiptTypesResponse {
    /**
     * Contains the 3 letter country codes as keys and the respective receipt types as values.
     * @type {{ [key: string]: Array<ReceiptType>; }}
     * @memberof ListReceiptTypesResponse
     */
    receiptTypes?: { [key: string]: Array<ReceiptType>; };
}

/**
 * Check if a given object implements the ListReceiptTypesResponse interface.
 */
export function instanceOfListReceiptTypesResponse(value: object): value is ListReceiptTypesResponse {
    return true;
}

export function ListReceiptTypesResponseFromJSON(json: any): ListReceiptTypesResponse {
    return ListReceiptTypesResponseFromJSONTyped(json, false);
}

export function ListReceiptTypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListReceiptTypesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'receiptTypes': json['receiptTypes'] == null ? undefined : json['receiptTypes'],
    };
}

export function ListReceiptTypesResponseToJSON(json: any): ListReceiptTypesResponse {
    return ListReceiptTypesResponseToJSONTyped(json, false);
}

export function ListReceiptTypesResponseToJSONTyped(value?: ListReceiptTypesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'receiptTypes': value['receiptTypes'],
    };
}

