/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Post } from './Post';
import {
    PostFromJSON,
    PostFromJSONTyped,
    PostToJSON,
    PostToJSONTyped,
} from './Post';

/**
 * 
 * @export
 * @interface ListPostsResponse
 */
export interface ListPostsResponse {
    /**
     * 
     * @type {Array<Post>}
     * @memberof ListPostsResponse
     */
    posts?: Array<Post>;
}

/**
 * Check if a given object implements the ListPostsResponse interface.
 */
export function instanceOfListPostsResponse(value: object): value is ListPostsResponse {
    return true;
}

export function ListPostsResponseFromJSON(json: any): ListPostsResponse {
    return ListPostsResponseFromJSONTyped(json, false);
}

export function ListPostsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPostsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(PostFromJSON)),
    };
}

export function ListPostsResponseToJSON(json: any): ListPostsResponse {
    return ListPostsResponseToJSONTyped(json, false);
}

export function ListPostsResponseToJSONTyped(value?: ListPostsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(PostToJSON)),
    };
}

