/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermanentEstablishment } from './PermanentEstablishment';
import {
    PermanentEstablishmentFromJSON,
    PermanentEstablishmentFromJSONTyped,
    PermanentEstablishmentToJSON,
    PermanentEstablishmentToJSONTyped,
} from './PermanentEstablishment';

/**
 * 
 * @export
 * @interface ListPermanentEstablishmentsResponse
 */
export interface ListPermanentEstablishmentsResponse {
    /**
     * 
     * @type {Array<PermanentEstablishment>}
     * @memberof ListPermanentEstablishmentsResponse
     */
    permanentEstablishments?: Array<PermanentEstablishment>;
}

/**
 * Check if a given object implements the ListPermanentEstablishmentsResponse interface.
 */
export function instanceOfListPermanentEstablishmentsResponse(value: object): value is ListPermanentEstablishmentsResponse {
    return true;
}

export function ListPermanentEstablishmentsResponseFromJSON(json: any): ListPermanentEstablishmentsResponse {
    return ListPermanentEstablishmentsResponseFromJSONTyped(json, false);
}

export function ListPermanentEstablishmentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPermanentEstablishmentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'permanentEstablishments': json['permanentEstablishments'] == null ? undefined : ((json['permanentEstablishments'] as Array<any>).map(PermanentEstablishmentFromJSON)),
    };
}

export function ListPermanentEstablishmentsResponseToJSON(json: any): ListPermanentEstablishmentsResponse {
    return ListPermanentEstablishmentsResponseToJSONTyped(json, false);
}

export function ListPermanentEstablishmentsResponseToJSONTyped(value?: ListPermanentEstablishmentsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permanentEstablishments': value['permanentEstablishments'] == null ? undefined : ((value['permanentEstablishments'] as Array<any>).map(PermanentEstablishmentToJSON)),
    };
}

