/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CostCenter } from './CostCenter';
import {
    CostCenterFromJSON,
    CostCenterFromJSONTyped,
    CostCenterToJSON,
    CostCenterToJSONTyped,
} from './CostCenter';

/**
 * 
 * @export
 * @interface ListCostCentersResponse
 */
export interface ListCostCentersResponse {
    /**
     * 
     * @type {Array<CostCenter>}
     * @memberof ListCostCentersResponse
     */
    costCenters?: Array<CostCenter>;
}

/**
 * Check if a given object implements the ListCostCentersResponse interface.
 */
export function instanceOfListCostCentersResponse(value: object): value is ListCostCentersResponse {
    return true;
}

export function ListCostCentersResponseFromJSON(json: any): ListCostCentersResponse {
    return ListCostCentersResponseFromJSONTyped(json, false);
}

export function ListCostCentersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCostCentersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'costCenters': json['costCenters'] == null ? undefined : ((json['costCenters'] as Array<any>).map(CostCenterFromJSON)),
    };
}

export function ListCostCentersResponseToJSON(json: any): ListCostCentersResponse {
    return ListCostCentersResponseToJSONTyped(json, false);
}

export function ListCostCentersResponseToJSONTyped(value?: ListCostCentersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'costCenters': value['costCenters'] == null ? undefined : ((value['costCenters'] as Array<any>).map(CostCenterToJSON)),
    };
}

