/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkingTimeKiosk } from './WorkingTimeKiosk';
import {
    WorkingTimeKioskFromJSON,
    WorkingTimeKioskFromJSONTyped,
    WorkingTimeKioskToJSON,
    WorkingTimeKioskToJSONTyped,
} from './WorkingTimeKiosk';

/**
 * 
 * @export
 * @interface ListWorkingTimeKiosksResponse
 */
export interface ListWorkingTimeKiosksResponse {
    /**
     * 
     * @type {Array<WorkingTimeKiosk>}
     * @memberof ListWorkingTimeKiosksResponse
     */
    kiosks?: Array<WorkingTimeKiosk>;
}

/**
 * Check if a given object implements the ListWorkingTimeKiosksResponse interface.
 */
export function instanceOfListWorkingTimeKiosksResponse(value: object): value is ListWorkingTimeKiosksResponse {
    return true;
}

export function ListWorkingTimeKiosksResponseFromJSON(json: any): ListWorkingTimeKiosksResponse {
    return ListWorkingTimeKiosksResponseFromJSONTyped(json, false);
}

export function ListWorkingTimeKiosksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkingTimeKiosksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'kiosks': json['kiosks'] == null ? undefined : ((json['kiosks'] as Array<any>).map(WorkingTimeKioskFromJSON)),
    };
}

export function ListWorkingTimeKiosksResponseToJSON(json: any): ListWorkingTimeKiosksResponse {
    return ListWorkingTimeKiosksResponseToJSONTyped(json, false);
}

export function ListWorkingTimeKiosksResponseToJSONTyped(value?: ListWorkingTimeKiosksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kiosks': value['kiosks'] == null ? undefined : ((value['kiosks'] as Array<any>).map(WorkingTimeKioskToJSON)),
    };
}

