/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnboardingDocument } from './OnboardingDocument';
import {
    OnboardingDocumentFromJSON,
    OnboardingDocumentFromJSONTyped,
    OnboardingDocumentToJSON,
    OnboardingDocumentToJSONTyped,
} from './OnboardingDocument';

/**
 * 
 * @export
 * @interface ListOnboardingDocumentsResponse
 */
export interface ListOnboardingDocumentsResponse {
    /**
     * 
     * @type {Array<OnboardingDocument>}
     * @memberof ListOnboardingDocumentsResponse
     */
    onboardingDocuments?: Array<OnboardingDocument>;
}

/**
 * Check if a given object implements the ListOnboardingDocumentsResponse interface.
 */
export function instanceOfListOnboardingDocumentsResponse(value: object): value is ListOnboardingDocumentsResponse {
    return true;
}

export function ListOnboardingDocumentsResponseFromJSON(json: any): ListOnboardingDocumentsResponse {
    return ListOnboardingDocumentsResponseFromJSONTyped(json, false);
}

export function ListOnboardingDocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOnboardingDocumentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'onboardingDocuments': json['onboardingDocuments'] == null ? undefined : ((json['onboardingDocuments'] as Array<any>).map(OnboardingDocumentFromJSON)),
    };
}

export function ListOnboardingDocumentsResponseToJSON(json: any): ListOnboardingDocumentsResponse {
    return ListOnboardingDocumentsResponseToJSONTyped(json, false);
}

export function ListOnboardingDocumentsResponseToJSONTyped(value?: ListOnboardingDocumentsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'onboardingDocuments': value['onboardingDocuments'] == null ? undefined : ((value['onboardingDocuments'] as Array<any>).map(OnboardingDocumentToJSON)),
    };
}

