/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AbsenceType } from './AbsenceType';
import {
    AbsenceTypeFromJSON,
    AbsenceTypeFromJSONTyped,
    AbsenceTypeToJSON,
    AbsenceTypeToJSONTyped,
} from './AbsenceType';

/**
 * 
 * @export
 * @interface ListAbsenceTypesResponse
 */
export interface ListAbsenceTypesResponse {
    /**
     * 
     * @type {Array<AbsenceType>}
     * @memberof ListAbsenceTypesResponse
     */
    absenceTypes?: Array<AbsenceType>;
}

/**
 * Check if a given object implements the ListAbsenceTypesResponse interface.
 */
export function instanceOfListAbsenceTypesResponse(value: object): value is ListAbsenceTypesResponse {
    return true;
}

export function ListAbsenceTypesResponseFromJSON(json: any): ListAbsenceTypesResponse {
    return ListAbsenceTypesResponseFromJSONTyped(json, false);
}

export function ListAbsenceTypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAbsenceTypesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'absenceTypes': json['absenceTypes'] == null ? undefined : ((json['absenceTypes'] as Array<any>).map(AbsenceTypeFromJSON)),
    };
}

export function ListAbsenceTypesResponseToJSON(json: any): ListAbsenceTypesResponse {
    return ListAbsenceTypesResponseToJSONTyped(json, false);
}

export function ListAbsenceTypesResponseToJSONTyped(value?: ListAbsenceTypesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'absenceTypes': value['absenceTypes'] == null ? undefined : ((value['absenceTypes'] as Array<any>).map(AbsenceTypeToJSON)),
    };
}

