/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MaritalStatus = {
    Married: 'married',
    Widowed: 'widowed',
    Separated: 'separated',
    Divorced: 'divorced',
    Single: 'single',
    NotSpecified: 'not specified'
} as const;
export type MaritalStatus = typeof MaritalStatus[keyof typeof MaritalStatus];


export function instanceOfMaritalStatus(value: any): boolean {
    for (const key in MaritalStatus) {
        if (Object.prototype.hasOwnProperty.call(MaritalStatus, key)) {
            if (MaritalStatus[key as keyof typeof MaritalStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MaritalStatusFromJSON(json: any): MaritalStatus {
    return MaritalStatusFromJSONTyped(json, false);
}

export function MaritalStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaritalStatus {
    return json as MaritalStatus;
}

export function MaritalStatusToJSON(value?: MaritalStatus | null): any {
    return value as any;
}

export function MaritalStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): MaritalStatus {
    return value as MaritalStatus;
}

