/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Vehicle } from './Vehicle';
import {
    VehicleFromJSON,
    VehicleFromJSONTyped,
    VehicleToJSON,
    VehicleToJSONTyped,
} from './Vehicle';
import type { CostObjective } from './CostObjective';
import {
    CostObjectiveFromJSON,
    CostObjectiveFromJSONTyped,
    CostObjectiveToJSON,
    CostObjectiveToJSONTyped,
} from './CostObjective';
import type { CostCenter } from './CostCenter';
import {
    CostCenterFromJSON,
    CostCenterFromJSONTyped,
    CostCenterToJSON,
    CostCenterToJSONTyped,
} from './CostCenter';
import type { MileageFlatRate } from './MileageFlatRate';
import {
    MileageFlatRateFromJSON,
    MileageFlatRateFromJSONTyped,
    MileageFlatRateToJSON,
    MileageFlatRateToJSONTyped,
} from './MileageFlatRate';
import type { UnitValueTuple } from './UnitValueTuple';
import {
    UnitValueTupleFromJSON,
    UnitValueTupleFromJSONTyped,
    UnitValueTupleToJSON,
    UnitValueTupleToJSONTyped,
} from './UnitValueTuple';

/**
 * 
 * @export
 * @interface MileageMultiDate
 */
export interface MileageMultiDate {
    /**
     * 
     * @type {CostCenter}
     * @memberof MileageMultiDate
     */
    costCenter?: CostCenter;
    /**
     * 
     * @type {CostObjective}
     * @memberof MileageMultiDate
     */
    costObjective?: CostObjective;
    /**
     * Text containing additional information about the trip as provided by the user.
     * @type {string}
     * @memberof MileageMultiDate
     */
    description?: string;
    /**
     * The destination of the trip.
     * @type {string}
     * @memberof MileageMultiDate
     */
    destination?: string;
    /**
     * 
     * @type {UnitValueTuple}
     * @memberof MileageMultiDate
     */
    distance?: UnitValueTuple;
    /**
     * 
     * @type {MileageFlatRate}
     * @memberof MileageMultiDate
     */
    flatRate?: MileageFlatRate;
    /**
     * The location where the trip was started.
     * @type {string}
     * @memberof MileageMultiDate
     */
    startLocation?: string;
    /**
     * 
     * @type {Vehicle}
     * @memberof MileageMultiDate
     */
    vehicle?: Vehicle;
    /**
     * The arrival date of the vehicle trip in YYYY-MM-DD format. Only returned for austrian persons.
     * @type {Date}
     * @memberof MileageMultiDate
     */
    arrivalDate?: Date;
    /**
     * The arrival time of the vehicle trip in HH:MM format. Only returned for austrian persons.
     * @type {string}
     * @memberof MileageMultiDate
     */
    arrivalTime?: string;
    /**
     * The departure date of the vehicle trip in YYYY-MM-DD format. Only returned for austrian persons.
     * @type {Date}
     * @memberof MileageMultiDate
     */
    departureDate?: Date;
    /**
     * The departure time of the vehicle trip in HH:MM format. Only returned for austrian persons.
     * @type {string}
     * @memberof MileageMultiDate
     */
    departureTime?: string;
}

/**
 * Check if a given object implements the MileageMultiDate interface.
 */
export function instanceOfMileageMultiDate(value: object): value is MileageMultiDate {
    return true;
}

export function MileageMultiDateFromJSON(json: any): MileageMultiDate {
    return MileageMultiDateFromJSONTyped(json, false);
}

export function MileageMultiDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MileageMultiDate {
    if (json == null) {
        return json;
    }
    return {
        
        'costCenter': json['costCenter'] == null ? undefined : CostCenterFromJSON(json['costCenter']),
        'costObjective': json['costObjective'] == null ? undefined : CostObjectiveFromJSON(json['costObjective']),
        'description': json['description'] == null ? undefined : json['description'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'distance': json['distance'] == null ? undefined : UnitValueTupleFromJSON(json['distance']),
        'flatRate': json['flatRate'] == null ? undefined : MileageFlatRateFromJSON(json['flatRate']),
        'startLocation': json['startLocation'] == null ? undefined : json['startLocation'],
        'vehicle': json['vehicle'] == null ? undefined : VehicleFromJSON(json['vehicle']),
        'arrivalDate': json['arrivalDate'] == null ? undefined : (new Date(json['arrivalDate'])),
        'arrivalTime': json['arrivalTime'] == null ? undefined : json['arrivalTime'],
        'departureDate': json['departureDate'] == null ? undefined : (new Date(json['departureDate'])),
        'departureTime': json['departureTime'] == null ? undefined : json['departureTime'],
    };
}

export function MileageMultiDateToJSON(json: any): MileageMultiDate {
    return MileageMultiDateToJSONTyped(json, false);
}

export function MileageMultiDateToJSONTyped(value?: MileageMultiDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'costCenter': CostCenterToJSON(value['costCenter']),
        'costObjective': CostObjectiveToJSON(value['costObjective']),
        'description': value['description'],
        'destination': value['destination'],
        'distance': UnitValueTupleToJSON(value['distance']),
        'flatRate': MileageFlatRateToJSON(value['flatRate']),
        'startLocation': value['startLocation'],
        'vehicle': VehicleToJSON(value['vehicle']),
        'arrivalDate': value['arrivalDate'] == null ? value['arrivalDate'] : value['arrivalDate'].toISOString().substring(0,10),
        'arrivalTime': value['arrivalTime'],
        'departureDate': value['departureDate'] == null ? value['departureDate'] : value['departureDate'].toISOString().substring(0,10),
        'departureTime': value['departureTime'],
    };
}

