/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SingleResult } from './SingleResult';
import {
    SingleResultFromJSON,
    SingleResultFromJSONTyped,
    SingleResultToJSON,
    SingleResultToJSONTyped,
} from './SingleResult';
import type { DataError } from './DataError';
import {
    DataErrorFromJSON,
    DataErrorFromJSONTyped,
    DataErrorToJSON,
    DataErrorToJSONTyped,
} from './DataError';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * 
 * @export
 * @interface MultiWriteRequestResult
 */
export interface MultiWriteRequestResult {
    /**
     * A collection of all general errors that occurred during the write request. Not included if no errors occurred.
     * @type {Array<ApiError>}
     * @memberof MultiWriteRequestResult
     */
    generalErrors?: Array<ApiError>;
    /**
     * A collection of all object-specific errors that occurred during the write request. A write request is aborted as soon as an error occurs, so this error collection may be incomplete. Each error contains a recordId that allows matching the errors to input data.
     * @type {Array<DataError>}
     * @memberof MultiWriteRequestResult
     */
    dataErrors?: Array<DataError>;
    /**
     * 
     * @type {string}
     * @memberof MultiWriteRequestResult
     */
    status?: string;
    /**
     * A JSON representation of the objects that were manipulated or created via the API request. May only contain an abridged version of the data. This property is an array with the same order as the input data. Each object can be identified via the recordId attribute that matches the order of the input data. RecordId counts start at 1, not 0! Only included if NO errors occurred during the processing of the request.
     * @type {Array<SingleResult>}
     * @memberof MultiWriteRequestResult
     */
    result?: Array<SingleResult>;
}

/**
 * Check if a given object implements the MultiWriteRequestResult interface.
 */
export function instanceOfMultiWriteRequestResult(value: object): value is MultiWriteRequestResult {
    return true;
}

export function MultiWriteRequestResultFromJSON(json: any): MultiWriteRequestResult {
    return MultiWriteRequestResultFromJSONTyped(json, false);
}

export function MultiWriteRequestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiWriteRequestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'generalErrors': json['generalErrors'] == null ? undefined : ((json['generalErrors'] as Array<any>).map(ApiErrorFromJSON)),
        'dataErrors': json['dataErrors'] == null ? undefined : ((json['dataErrors'] as Array<any>).map(DataErrorFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(SingleResultFromJSON)),
    };
}

export function MultiWriteRequestResultToJSON(json: any): MultiWriteRequestResult {
    return MultiWriteRequestResultToJSONTyped(json, false);
}

export function MultiWriteRequestResultToJSONTyped(value?: MultiWriteRequestResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generalErrors': value['generalErrors'] == null ? undefined : ((value['generalErrors'] as Array<any>).map(ApiErrorToJSON)),
        'dataErrors': value['dataErrors'] == null ? undefined : ((value['dataErrors'] as Array<any>).map(DataErrorToJSON)),
        'status': value['status'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(SingleResultToJSON)),
    };
}

