/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An error or warning that occurred while creating, deleting or editing an object via the API.
 * @export
 * @interface ObjectManipulationNotification
 */
export interface ObjectManipulationNotification {
    /**
     * A description text detailing what went wrong.
     * @type {string}
     * @memberof ObjectManipulationNotification
     */
    text?: string;
    /**
     * An error number that is referenced internally in HR WORKS.
     * @type {number}
     * @memberof ObjectManipulationNotification
     */
    number?: number;
}

/**
 * Check if a given object implements the ObjectManipulationNotification interface.
 */
export function instanceOfObjectManipulationNotification(value: object): value is ObjectManipulationNotification {
    return true;
}

export function ObjectManipulationNotificationFromJSON(json: any): ObjectManipulationNotification {
    return ObjectManipulationNotificationFromJSONTyped(json, false);
}

export function ObjectManipulationNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectManipulationNotification {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'number': json['number'] == null ? undefined : json['number'],
    };
}

export function ObjectManipulationNotificationToJSON(json: any): ObjectManipulationNotification {
    return ObjectManipulationNotificationToJSONTyped(json, false);
}

export function ObjectManipulationNotificationToJSONTyped(value?: ObjectManipulationNotification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'number': value['number'],
    };
}

