/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaritalStatus } from './MaritalStatus';
import {
    MaritalStatusFromJSON,
    MaritalStatusFromJSONTyped,
    MaritalStatusToJSON,
    MaritalStatusToJSONTyped,
} from './MaritalStatus';
import type { Confession } from './Confession';
import {
    ConfessionFromJSON,
    ConfessionFromJSONTyped,
    ConfessionToJSON,
    ConfessionToJSONTyped,
} from './Confession';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { OrganizationUnit } from './OrganizationUnit';
import {
    OrganizationUnitFromJSON,
    OrganizationUnitFromJSONTyped,
    OrganizationUnitToJSON,
    OrganizationUnitToJSONTyped,
} from './OrganizationUnit';
import type { BankAccount } from './BankAccount';
import {
    BankAccountFromJSON,
    BankAccountFromJSONTyped,
    BankAccountToJSON,
    BankAccountToJSONTyped,
} from './BankAccount';
import type { EmergencyContactDegreeOfKinship } from './EmergencyContactDegreeOfKinship';
import {
    EmergencyContactDegreeOfKinshipFromJSON,
    EmergencyContactDegreeOfKinshipFromJSONTyped,
    EmergencyContactDegreeOfKinshipToJSON,
    EmergencyContactDegreeOfKinshipToJSONTyped,
} from './EmergencyContactDegreeOfKinship';
import type { Gender } from './Gender';
import {
    GenderFromJSON,
    GenderFromJSONTyped,
    GenderToJSON,
    GenderToJSONTyped,
} from './Gender';
import type { HealthInsuranceType } from './HealthInsuranceType';
import {
    HealthInsuranceTypeFromJSON,
    HealthInsuranceTypeFromJSONTyped,
    HealthInsuranceTypeToJSON,
    HealthInsuranceTypeToJSONTyped,
} from './HealthInsuranceType';
import type { OnboardingStatus } from './OnboardingStatus';
import {
    OnboardingStatusFromJSON,
    OnboardingStatusFromJSONTyped,
    OnboardingStatusToJSON,
    OnboardingStatusToJSONTyped,
} from './OnboardingStatus';
import type { PersonBaseData } from './PersonBaseData';
import {
    PersonBaseDataFromJSON,
    PersonBaseDataFromJSONTyped,
    PersonBaseDataToJSON,
    PersonBaseDataToJSONTyped,
} from './PersonBaseData';

/**
 * Describes onboarding documents that exist in the company.
 * @export
 * @interface OnboardingDocument
 */
export interface OnboardingDocument {
    /**
     * 
     * @type {Address}
     * @memberof OnboardingDocument
     */
    address?: Address;
    /**
     * 
     * @type {BankAccount}
     * @memberof OnboardingDocument
     */
    bankAccount?: BankAccount;
    /**
     * The new employee's birthday. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof OnboardingDocument
     */
    birthday?: Date;
    /**
     * The birth name of the new employee.
     * @type {string}
     * @memberof OnboardingDocument
     */
    birthName?: string;
    /**
     * 
     * @type {Confession}
     * @memberof OnboardingDocument
     */
    confession?: Confession | null;
    /**
     * The country where the new employee was born.
     * @type {string}
     * @memberof OnboardingDocument
     */
    countryOfBirth?: string;
    /**
     * Only applicable for onboarding documents for German persons. The child allowance category of the person.
     * @type {string}
     * @memberof OnboardingDocument
     */
    childAllowanceCategory?: string;
    /**
     * 
     * @type {EmergencyContactDegreeOfKinship}
     * @memberof OnboardingDocument
     */
    emergencyContactDegreeOfKinship?: EmergencyContactDegreeOfKinship | null;
    /**
     * The name of the person's emergency contact.
     * @type {string}
     * @memberof OnboardingDocument
     */
    emergencyContactName?: string;
    /**
     * The person's emergency contact phone number.
     * @type {string}
     * @memberof OnboardingDocument
     */
    emergencyContactPhone?: string;
    /**
     * The given name of the new employee.
     * @type {string}
     * @memberof OnboardingDocument
     */
    firstName?: string;
    /**
     * 
     * @type {Gender}
     * @memberof OnboardingDocument
     */
    gender?: Gender | null;
    /**
     * Only applicable for onboarding documents for German persons. Indicates whether the person has a secondary employment.
     * @type {boolean}
     * @memberof OnboardingDocument
     */
    hasSecondaryEmployment?: boolean;
    /**
     * 
     * @type {HealthInsuranceType}
     * @memberof OnboardingDocument
     */
    healthInsuranceType?: HealthInsuranceType | null;
    /**
     * The unique identifier of the onboarding document.
     * @type {string}
     * @memberof OnboardingDocument
     */
    id?: string;
    /**
     * Only applicable for onboarding documents for German persons. Indicates whether this is the persons main activity.
     * @type {boolean}
     * @memberof OnboardingDocument
     */
    isMainActivity?: boolean;
    /**
     * The date of the person's first working day in the company. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof OnboardingDocument
     */
    joinDate?: Date;
    /**
     * The language code of the new employee. Determines the GUI language of the onboarding tool. Defaults to the language code of the assigned organization unit.
     * @type {string}
     * @memberof OnboardingDocument
     */
    languageCode?: string;
    /**
     * The surname of the new employee.
     * @type {string}
     * @memberof OnboardingDocument
     */
    lastName?: string;
    /**
     * 
     * @type {MaritalStatus}
     * @memberof OnboardingDocument
     */
    maritalStatus?: MaritalStatus | null;
    /**
     * The locale-specific name of the nationality of the new employee, e.g. Germany.
     * @type {string}
     * @memberof OnboardingDocument
     */
    nationality?: string;
    /**
     * A note that will be displayed for the onboarding administrator in HR WORKS.
     * @type {string}
     * @memberof OnboardingDocument
     */
    noteForOnboardingAdministrator?: string;
    /**
     * A note that will be displayed for the new employee.
     * @type {string}
     * @memberof OnboardingDocument
     */
    noteForOnboardingPerson?: string;
    /**
     * 
     * @type {OrganizationUnit}
     * @memberof OnboardingDocument
     */
    organizationUnit?: OrganizationUnit;
    /**
     * The private phone number of the new employee.
     * @type {string}
     * @memberof OnboardingDocument
     */
    privateMobilePhoneNumber?: string;
    /**
     * The city/location where the new employee was born.
     * @type {string}
     * @memberof OnboardingDocument
     */
    placeOfBirth?: string;
    /**
     * The private email address of the new employee.
     * @type {string}
     * @memberof OnboardingDocument
     */
    privateEmail?: string;
    /**
     * The expiry date of the residence permit of the new employee. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof OnboardingDocument
     */
    residencePermitExpiryDate?: Date;
    /**
     * The form of address of the new employee.
     * @type {string}
     * @memberof OnboardingDocument
     */
    salutation?: string;
    /**
     * 
     * @type {PersonBaseData}
     * @memberof OnboardingDocument
     */
    superior?: PersonBaseData;
    /**
     * Specifies if the employee is severely disabled.
     * @type {boolean}
     * @memberof OnboardingDocument
     */
    severeDisability?: boolean;
    /**
     * Only applicable for onboarding documents for German persons. The begin date of the person's secondary employment. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof OnboardingDocument
     */
    secondaryEmploymentBeginDate?: Date;
    /**
     * Returned for German persons only. The person's social security number.
     * @type {string}
     * @memberof OnboardingDocument
     */
    socialSecurityNumber?: string;
    /**
     * 
     * @type {OnboardingStatus}
     * @memberof OnboardingDocument
     */
    statusIdentifier?: OnboardingStatus | null;
    /**
     * The locale-specific name of the onboarding document's status.
     * @type {string}
     * @memberof OnboardingDocument
     */
    status?: string;
    /**
     * The given title of the new employee.
     * @type {string}
     * @memberof OnboardingDocument
     */
    title?: string;
    /**
     * Only applicable for onboarding documents for German persons. The tax category of the person.
     * @type {string}
     * @memberof OnboardingDocument
     */
    taxCategory?: string;
    /**
     * The expiry date of the work permit of the new employee. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof OnboardingDocument
     */
    workPermitExpiryDate?: Date;
    /**
     * The unique identifier of the organization unit this onboarding document belongs to.
     * @type {string}
     * @memberof OnboardingDocument
     */
    organizationUnitUuid?: string;
}



/**
 * Check if a given object implements the OnboardingDocument interface.
 */
export function instanceOfOnboardingDocument(value: object): value is OnboardingDocument {
    return true;
}

export function OnboardingDocumentFromJSON(json: any): OnboardingDocument {
    return OnboardingDocumentFromJSONTyped(json, false);
}

export function OnboardingDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'bankAccount': json['bankAccount'] == null ? undefined : BankAccountFromJSON(json['bankAccount']),
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'birthName': json['birthName'] == null ? undefined : json['birthName'],
        'confession': json['confession'] == null ? undefined : ConfessionFromJSON(json['confession']),
        'countryOfBirth': json['countryOfBirth'] == null ? undefined : json['countryOfBirth'],
        'childAllowanceCategory': json['childAllowanceCategory'] == null ? undefined : json['childAllowanceCategory'],
        'emergencyContactDegreeOfKinship': json['emergencyContactDegreeOfKinship'] == null ? undefined : EmergencyContactDegreeOfKinshipFromJSON(json['emergencyContactDegreeOfKinship']),
        'emergencyContactName': json['emergencyContactName'] == null ? undefined : json['emergencyContactName'],
        'emergencyContactPhone': json['emergencyContactPhone'] == null ? undefined : json['emergencyContactPhone'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'gender': json['gender'] == null ? undefined : GenderFromJSON(json['gender']),
        'hasSecondaryEmployment': json['hasSecondaryEmployment'] == null ? undefined : json['hasSecondaryEmployment'],
        'healthInsuranceType': json['healthInsuranceType'] == null ? undefined : HealthInsuranceTypeFromJSON(json['healthInsuranceType']),
        'id': json['id'] == null ? undefined : json['id'],
        'isMainActivity': json['isMainActivity'] == null ? undefined : json['isMainActivity'],
        'joinDate': json['joinDate'] == null ? undefined : (new Date(json['joinDate'])),
        'languageCode': json['languageCode'] == null ? undefined : json['languageCode'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'maritalStatus': json['maritalStatus'] == null ? undefined : MaritalStatusFromJSON(json['maritalStatus']),
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'noteForOnboardingAdministrator': json['noteForOnboardingAdministrator'] == null ? undefined : json['noteForOnboardingAdministrator'],
        'noteForOnboardingPerson': json['noteForOnboardingPerson'] == null ? undefined : json['noteForOnboardingPerson'],
        'organizationUnit': json['organizationUnit'] == null ? undefined : OrganizationUnitFromJSON(json['organizationUnit']),
        'privateMobilePhoneNumber': json['privateMobilePhoneNumber'] == null ? undefined : json['privateMobilePhoneNumber'],
        'placeOfBirth': json['placeOfBirth'] == null ? undefined : json['placeOfBirth'],
        'privateEmail': json['privateEmail'] == null ? undefined : json['privateEmail'],
        'residencePermitExpiryDate': json['residencePermitExpiryDate'] == null ? undefined : (new Date(json['residencePermitExpiryDate'])),
        'salutation': json['salutation'] == null ? undefined : json['salutation'],
        'superior': json['superior'] == null ? undefined : PersonBaseDataFromJSON(json['superior']),
        'severeDisability': json['severeDisability'] == null ? undefined : json['severeDisability'],
        'secondaryEmploymentBeginDate': json['secondaryEmploymentBeginDate'] == null ? undefined : (new Date(json['secondaryEmploymentBeginDate'])),
        'socialSecurityNumber': json['socialSecurityNumber'] == null ? undefined : json['socialSecurityNumber'],
        'statusIdentifier': json['statusIdentifier'] == null ? undefined : OnboardingStatusFromJSON(json['statusIdentifier']),
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'] == null ? undefined : json['title'],
        'taxCategory': json['taxCategory'] == null ? undefined : json['taxCategory'],
        'workPermitExpiryDate': json['workPermitExpiryDate'] == null ? undefined : (new Date(json['workPermitExpiryDate'])),
        'organizationUnitUuid': json['organizationUnitUuid'] == null ? undefined : json['organizationUnitUuid'],
    };
}

export function OnboardingDocumentToJSON(json: any): OnboardingDocument {
    return OnboardingDocumentToJSONTyped(json, false);
}

export function OnboardingDocumentToJSONTyped(value?: OnboardingDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': AddressToJSON(value['address']),
        'bankAccount': BankAccountToJSON(value['bankAccount']),
        'birthday': value['birthday'] == null ? value['birthday'] : value['birthday'].toISOString().substring(0,10),
        'birthName': value['birthName'],
        'confession': ConfessionToJSON(value['confession']),
        'countryOfBirth': value['countryOfBirth'],
        'childAllowanceCategory': value['childAllowanceCategory'],
        'emergencyContactDegreeOfKinship': EmergencyContactDegreeOfKinshipToJSON(value['emergencyContactDegreeOfKinship']),
        'emergencyContactName': value['emergencyContactName'],
        'emergencyContactPhone': value['emergencyContactPhone'],
        'firstName': value['firstName'],
        'gender': GenderToJSON(value['gender']),
        'hasSecondaryEmployment': value['hasSecondaryEmployment'],
        'healthInsuranceType': HealthInsuranceTypeToJSON(value['healthInsuranceType']),
        'id': value['id'],
        'isMainActivity': value['isMainActivity'],
        'joinDate': value['joinDate'] == null ? value['joinDate'] : value['joinDate'].toISOString().substring(0,10),
        'languageCode': value['languageCode'],
        'lastName': value['lastName'],
        'maritalStatus': MaritalStatusToJSON(value['maritalStatus']),
        'nationality': value['nationality'],
        'noteForOnboardingAdministrator': value['noteForOnboardingAdministrator'],
        'noteForOnboardingPerson': value['noteForOnboardingPerson'],
        'organizationUnit': OrganizationUnitToJSON(value['organizationUnit']),
        'privateMobilePhoneNumber': value['privateMobilePhoneNumber'],
        'placeOfBirth': value['placeOfBirth'],
        'privateEmail': value['privateEmail'],
        'residencePermitExpiryDate': value['residencePermitExpiryDate'] == null ? value['residencePermitExpiryDate'] : value['residencePermitExpiryDate'].toISOString().substring(0,10),
        'salutation': value['salutation'],
        'superior': PersonBaseDataToJSON(value['superior']),
        'severeDisability': value['severeDisability'],
        'secondaryEmploymentBeginDate': value['secondaryEmploymentBeginDate'] == null ? value['secondaryEmploymentBeginDate'] : value['secondaryEmploymentBeginDate'].toISOString().substring(0,10),
        'socialSecurityNumber': value['socialSecurityNumber'],
        'statusIdentifier': OnboardingStatusToJSON(value['statusIdentifier']),
        'status': value['status'],
        'title': value['title'],
        'taxCategory': value['taxCategory'],
        'workPermitExpiryDate': value['workPermitExpiryDate'] == null ? value['workPermitExpiryDate'] : value['workPermitExpiryDate'].toISOString().substring(0,10),
        'organizationUnitUuid': value['organizationUnitUuid'],
    };
}

