/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MaritalStatus } from './MaritalStatus';
import {
    MaritalStatusFromJSON,
    MaritalStatusFromJSONTyped,
    MaritalStatusToJSON,
    MaritalStatusToJSONTyped,
} from './MaritalStatus';
import type { Confession } from './Confession';
import {
    ConfessionFromJSON,
    ConfessionFromJSONTyped,
    ConfessionToJSON,
    ConfessionToJSONTyped,
} from './Confession';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { BankAccount } from './BankAccount';
import {
    BankAccountFromJSON,
    BankAccountFromJSONTyped,
    BankAccountToJSON,
    BankAccountToJSONTyped,
} from './BankAccount';
import type { EmergencyContactDegreeOfKinship } from './EmergencyContactDegreeOfKinship';
import {
    EmergencyContactDegreeOfKinshipFromJSON,
    EmergencyContactDegreeOfKinshipFromJSONTyped,
    EmergencyContactDegreeOfKinshipToJSON,
    EmergencyContactDegreeOfKinshipToJSONTyped,
} from './EmergencyContactDegreeOfKinship';
import type { Gender } from './Gender';
import {
    GenderFromJSON,
    GenderFromJSONTyped,
    GenderToJSON,
    GenderToJSONTyped,
} from './Gender';
import type { HealthInsuranceType } from './HealthInsuranceType';
import {
    HealthInsuranceTypeFromJSON,
    HealthInsuranceTypeFromJSONTyped,
    HealthInsuranceTypeToJSON,
    HealthInsuranceTypeToJSONTyped,
} from './HealthInsuranceType';

/**
 * Input data for creating a new onboarding document.
 * @export
 * @interface OnboardingDocumentData
 */
export interface OnboardingDocumentData {
    /**
     * The given name of the new employee.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    firstName: string;
    /**
     * The surname of the new employee.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    lastName: string;
    /**
     * The number of the organization unit that the new employee will be assigned to. Determines the assigned country of the employee.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    organizationUnitNumber: string;
    /**
     * The private email address of the new employee.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    privateEmail: string;
    /**
     * The date of the person's first working day in the company. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof OnboardingDocumentData
     */
    joinDate: Date;
    /**
     * 
     * @type {Address}
     * @memberof OnboardingDocumentData
     */
    address?: Address;
    /**
     * 
     * @type {BankAccount}
     * @memberof OnboardingDocumentData
     */
    bankAccount?: BankAccount;
    /**
     * The new employee's birthday. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof OnboardingDocumentData
     */
    birthday?: Date;
    /**
     * The nationality of the new employee. A three-letter country code.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    nationality?: string;
    /**
     * 
     * @type {Gender}
     * @memberof OnboardingDocumentData
     */
    gender?: Gender | null;
    /**
     * The expiry date of the work permit of the new employee. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof OnboardingDocumentData
     */
    workPermitExpiryDate?: Date;
    /**
     * The expiry date of the residence permit of the new employee. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof OnboardingDocumentData
     */
    residencePermitExpiryDate?: Date;
    /**
     * 
     * @type {MaritalStatus}
     * @memberof OnboardingDocumentData
     */
    maritalStatus?: MaritalStatus | null;
    /**
     * 
     * @type {EmergencyContactDegreeOfKinship}
     * @memberof OnboardingDocumentData
     */
    emergencyContactDegreeOfKinship?: EmergencyContactDegreeOfKinship | null;
    /**
     * If emergency contact data are known, use this attribute to specify the name of the emergency contact.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    emergencyContactName?: string;
    /**
     * If emergency contact data are known, use this attribute to specify the phone number of the emergency contact.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    emergencyContactPhone?: string;
    /**
     * The form of address of the new employee.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    salutation?: string;
    /**
     * The birth name of the new employee.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    birthName?: string;
    /**
     * The country where the new employee was born.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    countryOfBirth?: string;
    /**
     * The title (e.g. Dr.) of the new employee.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    title?: string;
    /**
     * The language code of the new employee. Determines the GUI language of the onboarding tool. Defaults to the language code of the assigned organization unit.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    languageCode?: string;
    /**
     * The private phone number of the new employee.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    privateMobilePhoneNumber?: string;
    /**
     * The city/location where the new employee was born.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    placeOfBirth?: string;
    /**
     * A note that will be displayed for the onboarding administrator in HR WORKS.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    noteForOnboardingAdministrator?: string;
    /**
     * A note that will be displayed for the new employee.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    noteForOnboardingPerson?: string;
    /**
     * 
     * @type {HealthInsuranceType}
     * @memberof OnboardingDocumentData
     */
    healthInsuranceType?: HealthInsuranceType | null;
    /**
     * 
     * @type {Confession}
     * @memberof OnboardingDocumentData
     */
    confession?: Confession | null;
    /**
     * 
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    socialSecurityNumber?: string;
    /**
     * Only applicable for onboarding documents for German persons.
     * @type {boolean}
     * @memberof OnboardingDocumentData
     */
    isMainActivity?: boolean;
    /**
     * Only applicable for onboarding documents for German persons.
     * @type {boolean}
     * @memberof OnboardingDocumentData
     */
    hasSecondaryEmployment?: boolean;
    /**
     * Only applicable for onboarding documents for German persons.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    secondaryEmploymentBeginDate?: string;
    /**
     * Only applicable for onboarding documents for German persons.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    taxCategory?: string;
    /**
     * Only applicable for onboarding documents for German persons.
     * @type {string}
     * @memberof OnboardingDocumentData
     */
    childAllowanceCategory?: string;
}



/**
 * Check if a given object implements the OnboardingDocumentData interface.
 */
export function instanceOfOnboardingDocumentData(value: object): value is OnboardingDocumentData {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('organizationUnitNumber' in value) || value['organizationUnitNumber'] === undefined) return false;
    if (!('privateEmail' in value) || value['privateEmail'] === undefined) return false;
    if (!('joinDate' in value) || value['joinDate'] === undefined) return false;
    return true;
}

export function OnboardingDocumentDataFromJSON(json: any): OnboardingDocumentData {
    return OnboardingDocumentDataFromJSONTyped(json, false);
}

export function OnboardingDocumentDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingDocumentData {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'organizationUnitNumber': json['organizationUnitNumber'],
        'privateEmail': json['privateEmail'],
        'joinDate': (new Date(json['joinDate'])),
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'bankAccount': json['bankAccount'] == null ? undefined : BankAccountFromJSON(json['bankAccount']),
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'gender': json['gender'] == null ? undefined : GenderFromJSON(json['gender']),
        'workPermitExpiryDate': json['workPermitExpiryDate'] == null ? undefined : (new Date(json['workPermitExpiryDate'])),
        'residencePermitExpiryDate': json['residencePermitExpiryDate'] == null ? undefined : (new Date(json['residencePermitExpiryDate'])),
        'maritalStatus': json['maritalStatus'] == null ? undefined : MaritalStatusFromJSON(json['maritalStatus']),
        'emergencyContactDegreeOfKinship': json['emergencyContactDegreeOfKinship'] == null ? undefined : EmergencyContactDegreeOfKinshipFromJSON(json['emergencyContactDegreeOfKinship']),
        'emergencyContactName': json['emergencyContactName'] == null ? undefined : json['emergencyContactName'],
        'emergencyContactPhone': json['emergencyContactPhone'] == null ? undefined : json['emergencyContactPhone'],
        'salutation': json['salutation'] == null ? undefined : json['salutation'],
        'birthName': json['birthName'] == null ? undefined : json['birthName'],
        'countryOfBirth': json['countryOfBirth'] == null ? undefined : json['countryOfBirth'],
        'title': json['title'] == null ? undefined : json['title'],
        'languageCode': json['languageCode'] == null ? undefined : json['languageCode'],
        'privateMobilePhoneNumber': json['privateMobilePhoneNumber'] == null ? undefined : json['privateMobilePhoneNumber'],
        'placeOfBirth': json['placeOfBirth'] == null ? undefined : json['placeOfBirth'],
        'noteForOnboardingAdministrator': json['noteForOnboardingAdministrator'] == null ? undefined : json['noteForOnboardingAdministrator'],
        'noteForOnboardingPerson': json['noteForOnboardingPerson'] == null ? undefined : json['noteForOnboardingPerson'],
        'healthInsuranceType': json['healthInsuranceType'] == null ? undefined : HealthInsuranceTypeFromJSON(json['healthInsuranceType']),
        'confession': json['confession'] == null ? undefined : ConfessionFromJSON(json['confession']),
        'socialSecurityNumber': json['socialSecurityNumber'] == null ? undefined : json['socialSecurityNumber'],
        'isMainActivity': json['isMainActivity'] == null ? undefined : json['isMainActivity'],
        'hasSecondaryEmployment': json['hasSecondaryEmployment'] == null ? undefined : json['hasSecondaryEmployment'],
        'secondaryEmploymentBeginDate': json['secondaryEmploymentBeginDate'] == null ? undefined : json['secondaryEmploymentBeginDate'],
        'taxCategory': json['taxCategory'] == null ? undefined : json['taxCategory'],
        'childAllowanceCategory': json['childAllowanceCategory'] == null ? undefined : json['childAllowanceCategory'],
    };
}

export function OnboardingDocumentDataToJSON(json: any): OnboardingDocumentData {
    return OnboardingDocumentDataToJSONTyped(json, false);
}

export function OnboardingDocumentDataToJSONTyped(value?: OnboardingDocumentData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'organizationUnitNumber': value['organizationUnitNumber'],
        'privateEmail': value['privateEmail'],
        'joinDate': value['joinDate'].toISOString().substring(0,10),
        'address': AddressToJSON(value['address']),
        'bankAccount': BankAccountToJSON(value['bankAccount']),
        'birthday': value['birthday'] == null ? value['birthday'] : value['birthday'].toISOString().substring(0,10),
        'nationality': value['nationality'],
        'gender': GenderToJSON(value['gender']),
        'workPermitExpiryDate': value['workPermitExpiryDate'] == null ? value['workPermitExpiryDate'] : value['workPermitExpiryDate'].toISOString().substring(0,10),
        'residencePermitExpiryDate': value['residencePermitExpiryDate'] == null ? value['residencePermitExpiryDate'] : value['residencePermitExpiryDate'].toISOString().substring(0,10),
        'maritalStatus': MaritalStatusToJSON(value['maritalStatus']),
        'emergencyContactDegreeOfKinship': EmergencyContactDegreeOfKinshipToJSON(value['emergencyContactDegreeOfKinship']),
        'emergencyContactName': value['emergencyContactName'],
        'emergencyContactPhone': value['emergencyContactPhone'],
        'salutation': value['salutation'],
        'birthName': value['birthName'],
        'countryOfBirth': value['countryOfBirth'],
        'title': value['title'],
        'languageCode': value['languageCode'],
        'privateMobilePhoneNumber': value['privateMobilePhoneNumber'],
        'placeOfBirth': value['placeOfBirth'],
        'noteForOnboardingAdministrator': value['noteForOnboardingAdministrator'],
        'noteForOnboardingPerson': value['noteForOnboardingPerson'],
        'healthInsuranceType': HealthInsuranceTypeToJSON(value['healthInsuranceType']),
        'confession': ConfessionToJSON(value['confession']),
        'socialSecurityNumber': value['socialSecurityNumber'],
        'isMainActivity': value['isMainActivity'],
        'hasSecondaryEmployment': value['hasSecondaryEmployment'],
        'secondaryEmploymentBeginDate': value['secondaryEmploymentBeginDate'],
        'taxCategory': value['taxCategory'],
        'childAllowanceCategory': value['childAllowanceCategory'],
    };
}

