/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * A physical business location of the company.
 * @export
 * @interface PermanentEstablishment
 */
export interface PermanentEstablishment {
    /**
     * 
     * @type {string}
     * @memberof PermanentEstablishment
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PermanentEstablishment
     */
    name?: string;
    /**
     * 
     * @type {Address}
     * @memberof PermanentEstablishment
     */
    address?: Address;
    /**
     * The eight-digit identification number of the permanent establishment.
     * @type {string}
     * @memberof PermanentEstablishment
     */
    number?: string;
}

/**
 * Check if a given object implements the PermanentEstablishment interface.
 */
export function instanceOfPermanentEstablishment(value: object): value is PermanentEstablishment {
    return true;
}

export function PermanentEstablishmentFromJSON(json: any): PermanentEstablishment {
    return PermanentEstablishmentFromJSONTyped(json, false);
}

export function PermanentEstablishmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermanentEstablishment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'number': json['number'] == null ? undefined : json['number'],
    };
}

export function PermanentEstablishmentToJSON(json: any): PermanentEstablishment {
    return PermanentEstablishmentToJSONTyped(json, false);
}

export function PermanentEstablishmentToJSONTyped(value?: PermanentEstablishment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': AddressToJSON(value['address']),
        'number': value['number'],
    };
}

