/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExternalId } from './ExternalId';
import {
    ExternalIdFromJSON,
    ExternalIdFromJSONTyped,
    ExternalIdToJSON,
    ExternalIdToJSONTyped,
} from './ExternalId';

/**
 * 
 * @export
 * @interface PersonBaseData
 */
export interface PersonBaseData {
    /**
     * The ids of the person in external systems.
     * @type {Array<ExternalId>}
     * @memberof PersonBaseData
     */
    externalIds?: Array<ExternalId>;
    /**
     * The given name of the person.
     * @type {string}
     * @memberof PersonBaseData
     */
    firstName?: string;
    /**
     * The surname of the person.
     * @type {string}
     * @memberof PersonBaseData
     */
    lastName?: string;
    /**
     * The HR WORKS username of the person.
     * @type {string}
     * @memberof PersonBaseData
     */
    personId?: string;
    /**
     * The personnel number of the person.
     * @type {string}
     * @memberof PersonBaseData
     */
    personnelNumber?: string;
    /**
     * The person identifier for kiosk of the person.
     * @type {string}
     * @memberof PersonBaseData
     */
    personIdentifierForKiosk?: string;
    /**
     * The DATEV personnel number of the person. This attribute is only returned if the DATEV integration is active.
     * @type {string}
     * @memberof PersonBaseData
     */
    datevPersonnelNumber?: string;
    /**
     * The unique identifier of the person in HR WORKS. This identifier does not change.
     * @type {string}
     * @memberof PersonBaseData
     */
    uuid?: string;
}

/**
 * Check if a given object implements the PersonBaseData interface.
 */
export function instanceOfPersonBaseData(value: object): value is PersonBaseData {
    return true;
}

export function PersonBaseDataFromJSON(json: any): PersonBaseData {
    return PersonBaseDataFromJSONTyped(json, false);
}

export function PersonBaseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonBaseData {
    if (json == null) {
        return json;
    }
    return {
        
        'externalIds': json['externalIds'] == null ? undefined : ((json['externalIds'] as Array<any>).map(ExternalIdFromJSON)),
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'personId': json['personId'] == null ? undefined : json['personId'],
        'personnelNumber': json['personnelNumber'] == null ? undefined : json['personnelNumber'],
        'personIdentifierForKiosk': json['personIdentifierForKiosk'] == null ? undefined : json['personIdentifierForKiosk'],
        'datevPersonnelNumber': json['datevPersonnelNumber'] == null ? undefined : json['datevPersonnelNumber'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function PersonBaseDataToJSON(json: any): PersonBaseData {
    return PersonBaseDataToJSONTyped(json, false);
}

export function PersonBaseDataToJSONTyped(value?: PersonBaseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalIds': value['externalIds'] == null ? undefined : ((value['externalIds'] as Array<any>).map(ExternalIdToJSON)),
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'personId': value['personId'],
        'personnelNumber': value['personnelNumber'],
        'personIdentifierForKiosk': value['personIdentifierForKiosk'],
        'datevPersonnelNumber': value['datevPersonnelNumber'],
        'uuid': value['uuid'],
    };
}

