/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SevereDisability } from './SevereDisability';
import {
    SevereDisabilityFromJSON,
    SevereDisabilityFromJSONTyped,
    SevereDisabilityToJSON,
    SevereDisabilityToJSONTyped,
} from './SevereDisability';

/**
 * 
 * @export
 * @interface PersonHistoricizedSevereDisabilityData
 */
export interface PersonHistoricizedSevereDisabilityData {
    /**
     * The start date of the assignment. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonHistoricizedSevereDisabilityData
     */
    beginDate?: Date;
    /**
     * The end date of the assignment. Not present if the assignment time period is set to unlimited. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonHistoricizedSevereDisabilityData
     */
    endDate?: Date;
    /**
     * 
     * @type {SevereDisability}
     * @memberof PersonHistoricizedSevereDisabilityData
     */
    data?: SevereDisability;
}

/**
 * Check if a given object implements the PersonHistoricizedSevereDisabilityData interface.
 */
export function instanceOfPersonHistoricizedSevereDisabilityData(value: object): value is PersonHistoricizedSevereDisabilityData {
    return true;
}

export function PersonHistoricizedSevereDisabilityDataFromJSON(json: any): PersonHistoricizedSevereDisabilityData {
    return PersonHistoricizedSevereDisabilityDataFromJSONTyped(json, false);
}

export function PersonHistoricizedSevereDisabilityDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonHistoricizedSevereDisabilityData {
    if (json == null) {
        return json;
    }
    return {
        
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'data': json['data'] == null ? undefined : SevereDisabilityFromJSON(json['data']),
    };
}

export function PersonHistoricizedSevereDisabilityDataToJSON(json: any): PersonHistoricizedSevereDisabilityData {
    return PersonHistoricizedSevereDisabilityDataToJSONTyped(json, false);
}

export function PersonHistoricizedSevereDisabilityDataToJSONTyped(value?: PersonHistoricizedSevereDisabilityData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'data': SevereDisabilityToJSON(value['data']),
    };
}

