/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';

/**
 * 
 * @export
 * @interface PersonHistoricizedAddressData
 */
export interface PersonHistoricizedAddressData {
    /**
     * The start date of the assignment. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonHistoricizedAddressData
     */
    beginDate?: Date;
    /**
     * The end date of the assignment. Not present if the assignment time period is set to unlimited. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonHistoricizedAddressData
     */
    endDate?: Date;
    /**
     * 
     * @type {Address}
     * @memberof PersonHistoricizedAddressData
     */
    data?: Address;
}

/**
 * Check if a given object implements the PersonHistoricizedAddressData interface.
 */
export function instanceOfPersonHistoricizedAddressData(value: object): value is PersonHistoricizedAddressData {
    return true;
}

export function PersonHistoricizedAddressDataFromJSON(json: any): PersonHistoricizedAddressData {
    return PersonHistoricizedAddressDataFromJSONTyped(json, false);
}

export function PersonHistoricizedAddressDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonHistoricizedAddressData {
    if (json == null) {
        return json;
    }
    return {
        
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'data': json['data'] == null ? undefined : AddressFromJSON(json['data']),
    };
}

export function PersonHistoricizedAddressDataToJSON(json: any): PersonHistoricizedAddressData {
    return PersonHistoricizedAddressDataToJSONTyped(json, false);
}

export function PersonHistoricizedAddressDataToJSONTyped(value?: PersonHistoricizedAddressData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'data': AddressToJSON(value['data']),
    };
}

