/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthInsurance } from './HealthInsurance';
import {
    HealthInsuranceFromJSON,
    HealthInsuranceFromJSONTyped,
    HealthInsuranceToJSON,
    HealthInsuranceToJSONTyped,
} from './HealthInsurance';

/**
 * 
 * @export
 * @interface PersonHistoricizedHealthInsuranceData
 */
export interface PersonHistoricizedHealthInsuranceData {
    /**
     * The start date of the assignment. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonHistoricizedHealthInsuranceData
     */
    beginDate?: Date;
    /**
     * The end date of the assignment. Not present if the assignment time period is set to unlimited. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonHistoricizedHealthInsuranceData
     */
    endDate?: Date;
    /**
     * 
     * @type {HealthInsurance}
     * @memberof PersonHistoricizedHealthInsuranceData
     */
    data?: HealthInsurance;
}

/**
 * Check if a given object implements the PersonHistoricizedHealthInsuranceData interface.
 */
export function instanceOfPersonHistoricizedHealthInsuranceData(value: object): value is PersonHistoricizedHealthInsuranceData {
    return true;
}

export function PersonHistoricizedHealthInsuranceDataFromJSON(json: any): PersonHistoricizedHealthInsuranceData {
    return PersonHistoricizedHealthInsuranceDataFromJSONTyped(json, false);
}

export function PersonHistoricizedHealthInsuranceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonHistoricizedHealthInsuranceData {
    if (json == null) {
        return json;
    }
    return {
        
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'data': json['data'] == null ? undefined : HealthInsuranceFromJSON(json['data']),
    };
}

export function PersonHistoricizedHealthInsuranceDataToJSON(json: any): PersonHistoricizedHealthInsuranceData {
    return PersonHistoricizedHealthInsuranceDataToJSONTyped(json, false);
}

export function PersonHistoricizedHealthInsuranceDataToJSONTyped(value?: PersonHistoricizedHealthInsuranceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'data': HealthInsuranceToJSON(value['data']),
    };
}

