/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * JSON object representing a personnel file entry.
 * @export
 * @interface PersonnelFileEntryData
 */
export interface PersonnelFileEntryData {
    /**
     * The name of the personnel file entry.
     * @type {string}
     * @memberof PersonnelFileEntryData
     */
    name: string;
    /**
     * The key of the category for the personnel file entry. All available categories can be fetched via /v2/persons/personnel-file/categories.
     * @type {string}
     * @memberof PersonnelFileEntryData
     */
    category: string;
    /**
     * The date of creation.
     * @type {Date}
     * @memberof PersonnelFileEntryData
     */
    creationDate: Date;
    /**
     * Identifier of the person to create an entry for. Use personIdentifierType to specify what type the value is.
     * @type {string}
     * @memberof PersonnelFileEntryData
     */
    personIdentifier?: string;
    /**
     * The personnel number of the person to create an entry for. Only used if no personIdentifier is present.
     * @type {string}
     * @memberof PersonnelFileEntryData
     */
    personnelNumber: string;
    /**
     * The notes of the personnel file entry.
     * @type {string}
     * @memberof PersonnelFileEntryData
     */
    notes?: string;
    /**
     * Specifies whether the personnel file is relevant to wages.
     * @type {boolean}
     * @memberof PersonnelFileEntryData
     */
    isWageRelevant?: boolean;
}

/**
 * Check if a given object implements the PersonnelFileEntryData interface.
 */
export function instanceOfPersonnelFileEntryData(value: object): value is PersonnelFileEntryData {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('creationDate' in value) || value['creationDate'] === undefined) return false;
    if (!('personnelNumber' in value) || value['personnelNumber'] === undefined) return false;
    return true;
}

export function PersonnelFileEntryDataFromJSON(json: any): PersonnelFileEntryData {
    return PersonnelFileEntryDataFromJSONTyped(json, false);
}

export function PersonnelFileEntryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonnelFileEntryData {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'category': json['category'],
        'creationDate': (new Date(json['creationDate'])),
        'personIdentifier': json['personIdentifier'] == null ? undefined : json['personIdentifier'],
        'personnelNumber': json['personnelNumber'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'isWageRelevant': json['isWageRelevant'] == null ? undefined : json['isWageRelevant'],
    };
}

export function PersonnelFileEntryDataToJSON(json: any): PersonnelFileEntryData {
    return PersonnelFileEntryDataToJSONTyped(json, false);
}

export function PersonnelFileEntryDataToJSONTyped(value?: PersonnelFileEntryData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'category': value['category'],
        'creationDate': value['creationDate'].toISOString().substring(0,10),
        'personIdentifier': value['personIdentifier'],
        'personnelNumber': value['personnelNumber'],
        'notes': value['notes'],
        'isWageRelevant': value['isWageRelevant'],
    };
}

