/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShortTimeWorkSchedule } from './ShortTimeWorkSchedule';
import {
    ShortTimeWorkScheduleFromJSON,
    ShortTimeWorkScheduleFromJSONTyped,
    ShortTimeWorkScheduleToJSON,
    ShortTimeWorkScheduleToJSONTyped,
} from './ShortTimeWorkSchedule';

/**
 * 
 * @export
 * @interface PersonHistoricizedShortTimeWorkScheduleData
 */
export interface PersonHistoricizedShortTimeWorkScheduleData {
    /**
     * The start date of the assignment. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonHistoricizedShortTimeWorkScheduleData
     */
    beginDate?: Date;
    /**
     * The end date of the assignment. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonHistoricizedShortTimeWorkScheduleData
     */
    endDate?: Date;
    /**
     * 
     * @type {ShortTimeWorkSchedule}
     * @memberof PersonHistoricizedShortTimeWorkScheduleData
     */
    data?: ShortTimeWorkSchedule;
}

/**
 * Check if a given object implements the PersonHistoricizedShortTimeWorkScheduleData interface.
 */
export function instanceOfPersonHistoricizedShortTimeWorkScheduleData(value: object): value is PersonHistoricizedShortTimeWorkScheduleData {
    return true;
}

export function PersonHistoricizedShortTimeWorkScheduleDataFromJSON(json: any): PersonHistoricizedShortTimeWorkScheduleData {
    return PersonHistoricizedShortTimeWorkScheduleDataFromJSONTyped(json, false);
}

export function PersonHistoricizedShortTimeWorkScheduleDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonHistoricizedShortTimeWorkScheduleData {
    if (json == null) {
        return json;
    }
    return {
        
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'data': json['data'] == null ? undefined : ShortTimeWorkScheduleFromJSON(json['data']),
    };
}

export function PersonHistoricizedShortTimeWorkScheduleDataToJSON(json: any): PersonHistoricizedShortTimeWorkScheduleData {
    return PersonHistoricizedShortTimeWorkScheduleDataToJSONTyped(json, false);
}

export function PersonHistoricizedShortTimeWorkScheduleDataToJSONTyped(value?: PersonHistoricizedShortTimeWorkScheduleData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'data': ShortTimeWorkScheduleToJSON(value['data']),
    };
}

