/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object representing a category for personnel file entries.
 * @export
 * @interface PersonnelFileCategory
 */
export interface PersonnelFileCategory {
    /**
     * The user-assigned name of the personnel file category.
     * @type {string}
     * @memberof PersonnelFileCategory
     */
    name?: string;
    /**
     * The unique key of the personnel file category.
     * @type {string}
     * @memberof PersonnelFileCategory
     */
    key?: string;
}

/**
 * Check if a given object implements the PersonnelFileCategory interface.
 */
export function instanceOfPersonnelFileCategory(value: object): value is PersonnelFileCategory {
    return true;
}

export function PersonnelFileCategoryFromJSON(json: any): PersonnelFileCategory {
    return PersonnelFileCategoryFromJSONTyped(json, false);
}

export function PersonnelFileCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonnelFileCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function PersonnelFileCategoryToJSON(json: any): PersonnelFileCategory {
    return PersonnelFileCategoryToJSONTyped(json, false);
}

export function PersonnelFileCategoryToJSONTyped(value?: PersonnelFileCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
    };
}

