/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { PaymentAccount } from './PaymentAccount';
import {
    PaymentAccountFromJSON,
    PaymentAccountFromJSONTyped,
    PaymentAccountToJSON,
    PaymentAccountToJSONTyped,
} from './PaymentAccount';
import type { ExternalId } from './ExternalId';
import {
    ExternalIdFromJSON,
    ExternalIdFromJSONTyped,
    ExternalIdToJSON,
    ExternalIdToJSONTyped,
} from './ExternalId';
import type { HighestLevelOfEducationId } from './HighestLevelOfEducationId';
import {
    HighestLevelOfEducationIdFromJSON,
    HighestLevelOfEducationIdFromJSONTyped,
    HighestLevelOfEducationIdToJSON,
    HighestLevelOfEducationIdToJSONTyped,
} from './HighestLevelOfEducationId';
import type { BankAccount } from './BankAccount';
import {
    BankAccountFromJSON,
    BankAccountFromJSONTyped,
    BankAccountToJSON,
    BankAccountToJSONTyped,
} from './BankAccount';
import type { EmergencyContactDegreeOfKinship } from './EmergencyContactDegreeOfKinship';
import {
    EmergencyContactDegreeOfKinshipFromJSON,
    EmergencyContactDegreeOfKinshipFromJSONTyped,
    EmergencyContactDegreeOfKinshipToJSON,
    EmergencyContactDegreeOfKinshipToJSONTyped,
} from './EmergencyContactDegreeOfKinship';
import type { Gender } from './Gender';
import {
    GenderFromJSON,
    GenderFromJSONTyped,
    GenderToJSON,
    GenderToJSONTyped,
} from './Gender';
import type { PersonHistoricizedData } from './PersonHistoricizedData';
import {
    PersonHistoricizedDataFromJSON,
    PersonHistoricizedDataFromJSONTyped,
    PersonHistoricizedDataToJSON,
    PersonHistoricizedDataToJSONTyped,
} from './PersonHistoricizedData';
import type { ShortTimeWorkSchedule } from './ShortTimeWorkSchedule';
import {
    ShortTimeWorkScheduleFromJSON,
    ShortTimeWorkScheduleFromJSONTyped,
    ShortTimeWorkScheduleToJSON,
    ShortTimeWorkScheduleToJSONTyped,
} from './ShortTimeWorkSchedule';
import type { EmploymentType } from './EmploymentType';
import {
    EmploymentTypeFromJSON,
    EmploymentTypeFromJSONTyped,
    EmploymentTypeToJSON,
    EmploymentTypeToJSONTyped,
} from './EmploymentType';
import type { WorkSchedule } from './WorkSchedule';
import {
    WorkScheduleFromJSON,
    WorkScheduleFromJSONTyped,
    WorkScheduleToJSON,
    WorkScheduleToJSONTyped,
} from './WorkSchedule';
import type { CostObjective } from './CostObjective';
import {
    CostObjectiveFromJSON,
    CostObjectiveFromJSONTyped,
    CostObjectiveToJSON,
    CostObjectiveToJSONTyped,
} from './CostObjective';
import type { CostCenter } from './CostCenter';
import {
    CostCenterFromJSON,
    CostCenterFromJSONTyped,
    CostCenterToJSON,
    CostCenterToJSONTyped,
} from './CostCenter';
import type { OrganizationUnit } from './OrganizationUnit';
import {
    OrganizationUnitFromJSON,
    OrganizationUnitFromJSONTyped,
    OrganizationUnitToJSON,
    OrganizationUnitToJSONTyped,
} from './OrganizationUnit';
import type { ExpensesGroup } from './ExpensesGroup';
import {
    ExpensesGroupFromJSON,
    ExpensesGroupFromJSONTyped,
    ExpensesGroupToJSON,
    ExpensesGroupToJSONTyped,
} from './ExpensesGroup';
import type { PermanentEstablishment } from './PermanentEstablishment';
import {
    PermanentEstablishmentFromJSON,
    PermanentEstablishmentFromJSONTyped,
    PermanentEstablishmentToJSON,
    PermanentEstablishmentToJSONTyped,
} from './PermanentEstablishment';
import type { TimeRecordingRegulationBaseData } from './TimeRecordingRegulationBaseData';
import {
    TimeRecordingRegulationBaseDataFromJSON,
    TimeRecordingRegulationBaseDataFromJSONTyped,
    TimeRecordingRegulationBaseDataToJSON,
    TimeRecordingRegulationBaseDataToJSONTyped,
} from './TimeRecordingRegulationBaseData';
import type { HighestProfessionalQualificationId } from './HighestProfessionalQualificationId';
import {
    HighestProfessionalQualificationIdFromJSON,
    HighestProfessionalQualificationIdFromJSONTyped,
    HighestProfessionalQualificationIdToJSON,
    HighestProfessionalQualificationIdToJSONTyped,
} from './HighestProfessionalQualificationId';
import type { PersonBaseData } from './PersonBaseData';
import {
    PersonBaseDataFromJSON,
    PersonBaseDataFromJSONTyped,
    PersonBaseDataToJSON,
    PersonBaseDataToJSONTyped,
} from './PersonBaseData';
import type { TriggerForGivingNotice } from './TriggerForGivingNotice';
import {
    TriggerForGivingNoticeFromJSON,
    TriggerForGivingNoticeFromJSONTyped,
    TriggerForGivingNoticeToJSON,
    TriggerForGivingNoticeToJSONTyped,
} from './TriggerForGivingNotice';

/**
 * Describes a person/employee that exists in HR WORKS. NOTE: If your company has defined additional custom free fields for person master data in HR WORKS, the API will return those as well with the assigned field name as key and the respective values set in the person's master data.
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * The default account payable of the person.
     * @type {string}
     * @memberof Person
     */
    accountPayable?: string;
    /**
     * 
     * @type {Address}
     * @memberof Person
     */
    address?: Address;
    /**
     * 
     * @type {BankAccount}
     * @memberof Person
     */
    bankAccount?: BankAccount;
    /**
     * The person's birthday. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof Person
     */
    birthday?: Date;
    /**
     * The birth name of the person.
     * @type {string}
     * @memberof Person
     */
    birthName?: string;
    /**
     * The room/building where the person usually works.
     * @type {string}
     * @memberof Person
     */
    buildingOrRoom?: string;
    /**
     * The number of the person's business mobile phone.
     * @type {string}
     * @memberof Person
     */
    companyMobilePhoneNumber?: string;
    /**
     * 
     * @type {CostCenter}
     * @memberof Person
     */
    costCenter?: CostCenter;
    /**
     * 
     * @type {CostObjective}
     * @memberof Person
     */
    costObjective?: CostObjective;
    /**
     * The person's country in HR WORKS, given as a 3-digit country code. This pertains to the country of the person as set in HR WORKS (usually the country of residence), not the nationality that was set in the person master data.
     * @type {string}
     * @memberof Person
     */
    countryCode?: string;
    /**
     * The person's personnel number in DATEV. Required if the person is assigned to a DATEV client in HR WORKS or if you want to create a new person which is assigned to an organization unit that is associated with a DATEV client.
     * @type {string}
     * @memberof Person
     */
    datevPersonnelNumber?: string;
    /**
     * 
     * @type {EmergencyContactDegreeOfKinship}
     * @memberof Person
     */
    emergencyContactDegreeOfKinship?: EmergencyContactDegreeOfKinship | null;
    /**
     * The person's emergency contact name.
     * @type {string}
     * @memberof Person
     */
    emergencyContactName?: string;
    /**
     * The person's emergency contact phone number.
     * @type {string}
     * @memberof Person
     */
    emergencyContactPhone?: string;
    /**
     * The person's email address. The value is always the business email address.
     * @type {string}
     * @memberof Person
     */
    email?: string;
    /**
     * 
     * @type {EmploymentType}
     * @memberof Person
     */
    employmentType?: EmploymentType | null;
    /**
     * 
     * @type {ExpensesGroup}
     * @memberof Person
     */
    expensesGroup?: ExpensesGroup;
    /**
     * The ids of the person in external systems.
     * @type {Array<ExternalId>}
     * @memberof Person
     */
    externalIds?: Array<ExternalId>;
    /**
     * The person's given name.
     * @type {string}
     * @memberof Person
     */
    firstName?: string;
    /**
     * 
     * @type {Gender}
     * @memberof Person
     */
    gender?: Gender | null;
    /**
     * 
     * @type {PersonHistoricizedData}
     * @memberof Person
     */
    historicizedData?: PersonHistoricizedData;
    /**
     * The date of the person's first working day in the company. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof Person
     */
    joinDate?: Date;
    /**
     * The language set for the HR WORKS GUI for this employee.
     * @type {string}
     * @memberof Person
     */
    languageCode?: string;
    /**
     * The person's surname.
     * @type {string}
     * @memberof Person
     */
    lastName?: string;
    /**
     * The date of the person's last working day in the company (if set). Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof Person
     */
    leaveDate?: Date;
    /**
     * The nationality of the person.
     * @type {string}
     * @memberof Person
     */
    nationality?: string;
    /**
     * The landline office phone number of the person.
     * @type {string}
     * @memberof Person
     */
    officePhoneNumber?: string;
    /**
     * 
     * @type {OrganizationUnit}
     * @memberof Person
     */
    organizationUnit?: OrganizationUnit;
    /**
     * 
     * @type {PermanentEstablishment}
     * @memberof Person
     */
    permanentEstablishment?: PermanentEstablishment;
    /**
     * 
     * @type {ShortTimeWorkSchedule}
     * @memberof Person
     */
    shortTimeWorkSchedule?: ShortTimeWorkSchedule;
    /**
     * The user id assigned to the person. Used as the login name. Unique identifier.
     * @type {string}
     * @memberof Person
     */
    personId?: string;
    /**
     * A unique identifier assigned by HR WORKS on person creation. Cannot be changed.
     * @type {string}
     * @memberof Person
     */
    personLicenseNumber?: string;
    /**
     * The personnel number assigned to the person. Unique identifier.
     * @type {string}
     * @memberof Person
     */
    personnelNumber?: string;
    /**
     * The job title / position of the person, e.g. 'accountant'.
     * @type {string}
     * @memberof Person
     */
    position?: string;
    /**
     * The person's private email address.
     * @type {string}
     * @memberof Person
     */
    privateEmail?: string;
    /**
     * The person's private mobile phone number.
     * @type {string}
     * @memberof Person
     */
    privateMobilePhoneNumber?: string;
    /**
     * The date on which the probationary period of the person ended or will end. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof Person
     */
    probationEndDate?: Date;
    /**
     * The form of address of the person.
     * @type {string}
     * @memberof Person
     */
    salutation?: string;
    /**
     * The second nationality of the person (if any).
     * @type {string}
     * @memberof Person
     */
    secondNationality?: string;
    /**
     * 
     * @type {PersonBaseData}
     * @memberof Person
     */
    superior?: PersonBaseData;
    /**
     * A honorific used by the person, e.g. "Dr.".
     * @type {string}
     * @memberof Person
     */
    title?: string;
    /**
     * 
     * @type {WorkSchedule}
     * @memberof Person
     */
    workSchedule?: WorkSchedule;
    /**
     * Returned for German persons only. The highest school degree attained by the person.
     * @type {string}
     * @memberof Person
     */
    highestLevelOfEducation?: string;
    /**
     * 
     * @type {HighestLevelOfEducationId}
     * @memberof Person
     */
    highestLevelOfEducationId?: HighestLevelOfEducationId;
    /**
     * Returned for German persons only. The advanced education / university degree attained by the person.
     * @type {string}
     * @memberof Person
     */
    highestProfessionalQualification?: string;
    /**
     * 
     * @type {HighestProfessionalQualificationId}
     * @memberof Person
     */
    highestProfessionalQualificationId?: HighestProfessionalQualificationId;
    /**
     * Returned for German persons only. The person's social security number.
     * @type {string}
     * @memberof Person
     */
    socialSecurityNumber?: string;
    /**
     * Returned for German persons only. The person's taxpayer ID.
     * @type {string}
     * @memberof Person
     */
    taxpayerIdentificationNumber?: string;
    /**
     * The date of notice given as a YYY-MM-DD formatted string.
     * @type {string}
     * @memberof Person
     */
    dateOfNotice?: string;
    /**
     * The reason why the employee left the company.
     * @type {string}
     * @memberof Person
     */
    reasonForGivingNotice?: string;
    /**
     * 
     * @type {TriggerForGivingNotice}
     * @memberof Person
     */
    triggerForGivingNotice?: TriggerForGivingNotice;
    /**
     * Denoting whether the employee was set to gone or not.
     * @type {boolean}
     * @memberof Person
     */
    isActive?: boolean;
    /**
     * Only returned if SSO is active for the company. Custom nameID value.
     * @type {string}
     * @memberof Person
     */
    customNameId?: string;
    /**
     * The profile picture of the employee in downloadable form. If you want to store the picture on your end, it is advised to download it on receipt of the API response - the link expires.
     * @type {string}
     * @memberof Person
     */
    profilePictureUrl?: string;
    /**
     * 
     * @type {TimeRecordingRegulationBaseData}
     * @memberof Person
     */
    timeRecordingRegulation?: TimeRecordingRegulationBaseData;
    /**
     * Unique number which is created after creating a QR Code card for the person.
     * @type {string}
     * @memberof Person
     */
    personIdentifierForKiosk?: string;
    /**
     * All accounts payable of the person.
     * @type {Array<PaymentAccount>}
     * @memberof Person
     */
    paymentAccounts?: Array<PaymentAccount>;
    /**
     * The unique identifier of the person in HR WORKS. This identifier does not change.
     * @type {string}
     * @memberof Person
     */
    uuid?: string;
    /**
     * The unique identifier of the organization unit the person belongs to.
     * @type {string}
     * @memberof Person
     */
    organizationUnitUuid?: string;
}



/**
 * Check if a given object implements the Person interface.
 */
export function instanceOfPerson(value: object): value is Person {
    return true;
}

export function PersonFromJSON(json: any): Person {
    return PersonFromJSONTyped(json, false);
}

export function PersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Person {
    if (json == null) {
        return json;
    }
    return {
        
        'accountPayable': json['accountPayable'] == null ? undefined : json['accountPayable'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'bankAccount': json['bankAccount'] == null ? undefined : BankAccountFromJSON(json['bankAccount']),
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'birthName': json['birthName'] == null ? undefined : json['birthName'],
        'buildingOrRoom': json['buildingOrRoom'] == null ? undefined : json['buildingOrRoom'],
        'companyMobilePhoneNumber': json['companyMobilePhoneNumber'] == null ? undefined : json['companyMobilePhoneNumber'],
        'costCenter': json['costCenter'] == null ? undefined : CostCenterFromJSON(json['costCenter']),
        'costObjective': json['costObjective'] == null ? undefined : CostObjectiveFromJSON(json['costObjective']),
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'datevPersonnelNumber': json['datevPersonnelNumber'] == null ? undefined : json['datevPersonnelNumber'],
        'emergencyContactDegreeOfKinship': json['emergencyContactDegreeOfKinship'] == null ? undefined : EmergencyContactDegreeOfKinshipFromJSON(json['emergencyContactDegreeOfKinship']),
        'emergencyContactName': json['emergencyContactName'] == null ? undefined : json['emergencyContactName'],
        'emergencyContactPhone': json['emergencyContactPhone'] == null ? undefined : json['emergencyContactPhone'],
        'email': json['email'] == null ? undefined : json['email'],
        'employmentType': json['employmentType'] == null ? undefined : EmploymentTypeFromJSON(json['employmentType']),
        'expensesGroup': json['expensesGroup'] == null ? undefined : ExpensesGroupFromJSON(json['expensesGroup']),
        'externalIds': json['externalIds'] == null ? undefined : ((json['externalIds'] as Array<any>).map(ExternalIdFromJSON)),
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'gender': json['gender'] == null ? undefined : GenderFromJSON(json['gender']),
        'historicizedData': json['historicizedData'] == null ? undefined : PersonHistoricizedDataFromJSON(json['historicizedData']),
        'joinDate': json['joinDate'] == null ? undefined : (new Date(json['joinDate'])),
        'languageCode': json['languageCode'] == null ? undefined : json['languageCode'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'leaveDate': json['leaveDate'] == null ? undefined : (new Date(json['leaveDate'])),
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'officePhoneNumber': json['officePhoneNumber'] == null ? undefined : json['officePhoneNumber'],
        'organizationUnit': json['organizationUnit'] == null ? undefined : OrganizationUnitFromJSON(json['organizationUnit']),
        'permanentEstablishment': json['permanentEstablishment'] == null ? undefined : PermanentEstablishmentFromJSON(json['permanentEstablishment']),
        'shortTimeWorkSchedule': json['shortTimeWorkSchedule'] == null ? undefined : ShortTimeWorkScheduleFromJSON(json['shortTimeWorkSchedule']),
        'personId': json['personId'] == null ? undefined : json['personId'],
        'personLicenseNumber': json['personLicenseNumber'] == null ? undefined : json['personLicenseNumber'],
        'personnelNumber': json['personnelNumber'] == null ? undefined : json['personnelNumber'],
        'position': json['position'] == null ? undefined : json['position'],
        'privateEmail': json['privateEmail'] == null ? undefined : json['privateEmail'],
        'privateMobilePhoneNumber': json['privateMobilePhoneNumber'] == null ? undefined : json['privateMobilePhoneNumber'],
        'probationEndDate': json['probationEndDate'] == null ? undefined : (new Date(json['probationEndDate'])),
        'salutation': json['salutation'] == null ? undefined : json['salutation'],
        'secondNationality': json['secondNationality'] == null ? undefined : json['secondNationality'],
        'superior': json['superior'] == null ? undefined : PersonBaseDataFromJSON(json['superior']),
        'title': json['title'] == null ? undefined : json['title'],
        'workSchedule': json['workSchedule'] == null ? undefined : WorkScheduleFromJSON(json['workSchedule']),
        'highestLevelOfEducation': json['highestLevelOfEducation'] == null ? undefined : json['highestLevelOfEducation'],
        'highestLevelOfEducationId': json['highestLevelOfEducationId'] == null ? undefined : HighestLevelOfEducationIdFromJSON(json['highestLevelOfEducationId']),
        'highestProfessionalQualification': json['highestProfessionalQualification'] == null ? undefined : json['highestProfessionalQualification'],
        'highestProfessionalQualificationId': json['highestProfessionalQualificationId'] == null ? undefined : HighestProfessionalQualificationIdFromJSON(json['highestProfessionalQualificationId']),
        'socialSecurityNumber': json['socialSecurityNumber'] == null ? undefined : json['socialSecurityNumber'],
        'taxpayerIdentificationNumber': json['taxpayerIdentificationNumber'] == null ? undefined : json['taxpayerIdentificationNumber'],
        'dateOfNotice': json['dateOfNotice'] == null ? undefined : json['dateOfNotice'],
        'reasonForGivingNotice': json['reasonForGivingNotice'] == null ? undefined : json['reasonForGivingNotice'],
        'triggerForGivingNotice': json['triggerForGivingNotice'] == null ? undefined : TriggerForGivingNoticeFromJSON(json['triggerForGivingNotice']),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'customNameId': json['customNameId'] == null ? undefined : json['customNameId'],
        'profilePictureUrl': json['profilePictureUrl'] == null ? undefined : json['profilePictureUrl'],
        'timeRecordingRegulation': json['timeRecordingRegulation'] == null ? undefined : TimeRecordingRegulationBaseDataFromJSON(json['timeRecordingRegulation']),
        'personIdentifierForKiosk': json['personIdentifierForKiosk'] == null ? undefined : json['personIdentifierForKiosk'],
        'paymentAccounts': json['paymentAccounts'] == null ? undefined : ((json['paymentAccounts'] as Array<any>).map(PaymentAccountFromJSON)),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'organizationUnitUuid': json['organizationUnitUuid'] == null ? undefined : json['organizationUnitUuid'],
    };
}

export function PersonToJSON(json: any): Person {
    return PersonToJSONTyped(json, false);
}

export function PersonToJSONTyped(value?: Person | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountPayable': value['accountPayable'],
        'address': AddressToJSON(value['address']),
        'bankAccount': BankAccountToJSON(value['bankAccount']),
        'birthday': value['birthday'] == null ? value['birthday'] : value['birthday'].toISOString().substring(0,10),
        'birthName': value['birthName'],
        'buildingOrRoom': value['buildingOrRoom'],
        'companyMobilePhoneNumber': value['companyMobilePhoneNumber'],
        'costCenter': CostCenterToJSON(value['costCenter']),
        'costObjective': CostObjectiveToJSON(value['costObjective']),
        'countryCode': value['countryCode'],
        'datevPersonnelNumber': value['datevPersonnelNumber'],
        'emergencyContactDegreeOfKinship': EmergencyContactDegreeOfKinshipToJSON(value['emergencyContactDegreeOfKinship']),
        'emergencyContactName': value['emergencyContactName'],
        'emergencyContactPhone': value['emergencyContactPhone'],
        'email': value['email'],
        'employmentType': EmploymentTypeToJSON(value['employmentType']),
        'expensesGroup': ExpensesGroupToJSON(value['expensesGroup']),
        'externalIds': value['externalIds'] == null ? undefined : ((value['externalIds'] as Array<any>).map(ExternalIdToJSON)),
        'firstName': value['firstName'],
        'gender': GenderToJSON(value['gender']),
        'historicizedData': PersonHistoricizedDataToJSON(value['historicizedData']),
        'joinDate': value['joinDate'] == null ? value['joinDate'] : value['joinDate'].toISOString().substring(0,10),
        'languageCode': value['languageCode'],
        'lastName': value['lastName'],
        'leaveDate': value['leaveDate'] == null ? value['leaveDate'] : value['leaveDate'].toISOString().substring(0,10),
        'nationality': value['nationality'],
        'officePhoneNumber': value['officePhoneNumber'],
        'organizationUnit': OrganizationUnitToJSON(value['organizationUnit']),
        'permanentEstablishment': PermanentEstablishmentToJSON(value['permanentEstablishment']),
        'shortTimeWorkSchedule': ShortTimeWorkScheduleToJSON(value['shortTimeWorkSchedule']),
        'personId': value['personId'],
        'personLicenseNumber': value['personLicenseNumber'],
        'personnelNumber': value['personnelNumber'],
        'position': value['position'],
        'privateEmail': value['privateEmail'],
        'privateMobilePhoneNumber': value['privateMobilePhoneNumber'],
        'probationEndDate': value['probationEndDate'] == null ? value['probationEndDate'] : value['probationEndDate'].toISOString().substring(0,10),
        'salutation': value['salutation'],
        'secondNationality': value['secondNationality'],
        'superior': PersonBaseDataToJSON(value['superior']),
        'title': value['title'],
        'workSchedule': WorkScheduleToJSON(value['workSchedule']),
        'highestLevelOfEducation': value['highestLevelOfEducation'],
        'highestLevelOfEducationId': HighestLevelOfEducationIdToJSON(value['highestLevelOfEducationId']),
        'highestProfessionalQualification': value['highestProfessionalQualification'],
        'highestProfessionalQualificationId': HighestProfessionalQualificationIdToJSON(value['highestProfessionalQualificationId']),
        'socialSecurityNumber': value['socialSecurityNumber'],
        'taxpayerIdentificationNumber': value['taxpayerIdentificationNumber'],
        'dateOfNotice': value['dateOfNotice'],
        'reasonForGivingNotice': value['reasonForGivingNotice'],
        'triggerForGivingNotice': TriggerForGivingNoticeToJSON(value['triggerForGivingNotice']),
        'isActive': value['isActive'],
        'customNameId': value['customNameId'],
        'profilePictureUrl': value['profilePictureUrl'],
        'timeRecordingRegulation': TimeRecordingRegulationBaseDataToJSON(value['timeRecordingRegulation']),
        'personIdentifierForKiosk': value['personIdentifierForKiosk'],
        'paymentAccounts': value['paymentAccounts'] == null ? undefined : ((value['paymentAccounts'] as Array<any>).map(PaymentAccountToJSON)),
        'uuid': value['uuid'],
        'organizationUnitUuid': value['organizationUnitUuid'],
    };
}

