/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SickLeave } from './SickLeave';
import {
    SickLeaveFromJSON,
    SickLeaveFromJSONTyped,
    SickLeaveToJSON,
    SickLeaveToJSONTyped,
} from './SickLeave';
import type { WorkingTime } from './WorkingTime';
import {
    WorkingTimeFromJSON,
    WorkingTimeFromJSONTyped,
    WorkingTimeToJSON,
    WorkingTimeToJSONTyped,
} from './WorkingTime';
import type { RemoteWork } from './RemoteWork';
import {
    RemoteWorkFromJSON,
    RemoteWorkFromJSONTyped,
    RemoteWorkToJSON,
    RemoteWorkToJSONTyped,
} from './RemoteWork';
import type { TravelRequest } from './TravelRequest';
import {
    TravelRequestFromJSON,
    TravelRequestFromJSONTyped,
    TravelRequestToJSON,
    TravelRequestToJSONTyped,
} from './TravelRequest';
import type { Holiday } from './Holiday';
import {
    HolidayFromJSON,
    HolidayFromJSONTyped,
    HolidayToJSON,
    HolidayToJSONTyped,
} from './Holiday';
import type { Absence } from './Absence';
import {
    AbsenceFromJSON,
    AbsenceFromJSONTyped,
    AbsenceToJSON,
    AbsenceToJSONTyped,
} from './Absence';
import type { ExpenseReport } from './ExpenseReport';
import {
    ExpenseReportFromJSON,
    ExpenseReportFromJSONTyped,
    ExpenseReportToJSON,
    ExpenseReportToJSONTyped,
} from './ExpenseReport';

/**
 * 
 * @export
 * @interface PersonDay
 */
export interface PersonDay {
    /**
     * 
     * @type {number}
     * @memberof PersonDay
     */
    targetWorkingTime?: number;
    /**
     * 
     * @type {Array<Holiday>}
     * @memberof PersonDay
     */
    holidays?: Array<Holiday>;
    /**
     * 
     * @type {Array<WorkingTime>}
     * @memberof PersonDay
     */
    workingTimes?: Array<WorkingTime>;
    /**
     * 
     * @type {Array<Absence>}
     * @memberof PersonDay
     */
    absences?: Array<Absence>;
    /**
     * 
     * @type {Array<SickLeave>}
     * @memberof PersonDay
     */
    sickLeaves?: Array<SickLeave>;
    /**
     * 
     * @type {Array<TravelRequest>}
     * @memberof PersonDay
     */
    travelRequests?: Array<TravelRequest>;
    /**
     * 
     * @type {Array<ExpenseReport>}
     * @memberof PersonDay
     */
    expenseReports?: Array<ExpenseReport>;
    /**
     * 
     * @type {Array<RemoteWork>}
     * @memberof PersonDay
     */
    remoteWork?: Array<RemoteWork>;
    /**
     * The working hours balance of the previous day in minutes.
     * @type {number}
     * @memberof PersonDay
     */
    previousDayTimeAccountBalance?: number;
}

/**
 * Check if a given object implements the PersonDay interface.
 */
export function instanceOfPersonDay(value: object): value is PersonDay {
    return true;
}

export function PersonDayFromJSON(json: any): PersonDay {
    return PersonDayFromJSONTyped(json, false);
}

export function PersonDayFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonDay {
    if (json == null) {
        return json;
    }
    return {
        
        'targetWorkingTime': json['targetWorkingTime'] == null ? undefined : json['targetWorkingTime'],
        'holidays': json['holidays'] == null ? undefined : ((json['holidays'] as Array<any>).map(HolidayFromJSON)),
        'workingTimes': json['workingTimes'] == null ? undefined : ((json['workingTimes'] as Array<any>).map(WorkingTimeFromJSON)),
        'absences': json['absences'] == null ? undefined : ((json['absences'] as Array<any>).map(AbsenceFromJSON)),
        'sickLeaves': json['sickLeaves'] == null ? undefined : ((json['sickLeaves'] as Array<any>).map(SickLeaveFromJSON)),
        'travelRequests': json['travelRequests'] == null ? undefined : ((json['travelRequests'] as Array<any>).map(TravelRequestFromJSON)),
        'expenseReports': json['expenseReports'] == null ? undefined : ((json['expenseReports'] as Array<any>).map(ExpenseReportFromJSON)),
        'remoteWork': json['remoteWork'] == null ? undefined : ((json['remoteWork'] as Array<any>).map(RemoteWorkFromJSON)),
        'previousDayTimeAccountBalance': json['previousDayTimeAccountBalance'] == null ? undefined : json['previousDayTimeAccountBalance'],
    };
}

export function PersonDayToJSON(json: any): PersonDay {
    return PersonDayToJSONTyped(json, false);
}

export function PersonDayToJSONTyped(value?: PersonDay | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetWorkingTime': value['targetWorkingTime'],
        'holidays': value['holidays'] == null ? undefined : ((value['holidays'] as Array<any>).map(HolidayToJSON)),
        'workingTimes': value['workingTimes'] == null ? undefined : ((value['workingTimes'] as Array<any>).map(WorkingTimeToJSON)),
        'absences': value['absences'] == null ? undefined : ((value['absences'] as Array<any>).map(AbsenceToJSON)),
        'sickLeaves': value['sickLeaves'] == null ? undefined : ((value['sickLeaves'] as Array<any>).map(SickLeaveToJSON)),
        'travelRequests': value['travelRequests'] == null ? undefined : ((value['travelRequests'] as Array<any>).map(TravelRequestToJSON)),
        'expenseReports': value['expenseReports'] == null ? undefined : ((value['expenseReports'] as Array<any>).map(ExpenseReportToJSON)),
        'remoteWork': value['remoteWork'] == null ? undefined : ((value['remoteWork'] as Array<any>).map(RemoteWorkToJSON)),
        'previousDayTimeAccountBalance': value['previousDayTimeAccountBalance'],
    };
}

