/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Address } from './Address';
import {
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    AddressToJSONTyped,
} from './Address';
import type { HighestLevelOfEducationId } from './HighestLevelOfEducationId';
import {
    HighestLevelOfEducationIdFromJSON,
    HighestLevelOfEducationIdFromJSONTyped,
    HighestLevelOfEducationIdToJSON,
    HighestLevelOfEducationIdToJSONTyped,
} from './HighestLevelOfEducationId';
import type { BankAccount } from './BankAccount';
import {
    BankAccountFromJSON,
    BankAccountFromJSONTyped,
    BankAccountToJSON,
    BankAccountToJSONTyped,
} from './BankAccount';
import type { Gender } from './Gender';
import {
    GenderFromJSON,
    GenderFromJSONTyped,
    GenderToJSON,
    GenderToJSONTyped,
} from './Gender';
import type { EmploymentType } from './EmploymentType';
import {
    EmploymentTypeFromJSON,
    EmploymentTypeFromJSONTyped,
    EmploymentTypeToJSON,
    EmploymentTypeToJSONTyped,
} from './EmploymentType';
import type { HighestProfessionalQualificationId } from './HighestProfessionalQualificationId';
import {
    HighestProfessionalQualificationIdFromJSON,
    HighestProfessionalQualificationIdFromJSONTyped,
    HighestProfessionalQualificationIdToJSON,
    HighestProfessionalQualificationIdToJSONTyped,
} from './HighestProfessionalQualificationId';

/**
 * Describes the attributes that can be set while creating/editing persons via the API.
 * @export
 * @interface PersonData
 */
export interface PersonData {
    /**
     * The default account payable of the person, referenced by the account's number.
     * @type {string}
     * @memberof PersonData
     */
    accountPayable?: string;
    /**
     * 
     * @type {Address}
     * @memberof PersonData
     */
    address?: Address;
    /**
     * 
     * @type {BankAccount}
     * @memberof PersonData
     */
    bankAccount?: BankAccount;
    /**
     * The person's birthday. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonData
     */
    birthday?: Date;
    /**
     * The room/building where the person usually works.
     * @type {string}
     * @memberof PersonData
     */
    buildingOrRoom?: string;
    /**
     * The number of the person's business mobile phone.
     * @type {string}
     * @memberof PersonData
     */
    companyMobilePhoneNumber?: string;
    /**
     * The default cost center of the person, references by number.
     * @type {string}
     * @memberof PersonData
     */
    costCenterNumber?: string;
    /**
     * The default cost objective of the person, references by number.
     * @type {string}
     * @memberof PersonData
     */
    costObjectiveNumber?: string;
    /**
     * The person's country in HR WORKS, given as a 3-digit country code. This pertains to the country of the person as set in HR WORKS (usually the country of residence), not the nationality that was set in the person master data.
     * @type {string}
     * @memberof PersonData
     */
    countryCode?: string;
    /**
     * Only returned if SSO is active for the company. Custom nameID value.
     * @type {string}
     * @memberof PersonData
     */
    customNameId?: string;
    /**
     * The person's personnel number in DATEV. Required if the person is assigned to a DATEV client in HR WORKS or if you want to create a new person which is assigned to an organization unit that is associated with a DATEV client.
     * @type {string}
     * @memberof PersonData
     */
    datevPersonnelNumber?: string;
    /**
     * The person's email address. The value is always the business email address.
     * @type {string}
     * @memberof PersonData
     */
    email?: string;
    /**
     * 
     * @type {EmploymentType}
     * @memberof PersonData
     */
    employmentType?: EmploymentType | null;
    /**
     * The person's given name.
     * @type {string}
     * @memberof PersonData
     */
    firstName?: string;
    /**
     * 
     * @type {Gender}
     * @memberof PersonData
     */
    gender?: Gender | null;
    /**
     * The date of the person's first working day in the company. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonData
     */
    joinDate?: Date;
    /**
     * The person's surname.
     * @type {string}
     * @memberof PersonData
     */
    lastName?: string;
    /**
     * The date of the person's last working day in the company (if set). Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonData
     */
    leaveDate?: Date;
    /**
     * The nationality of the person.
     * @type {string}
     * @memberof PersonData
     */
    nationality?: string;
    /**
     * The landline office phone number of the person.
     * @type {string}
     * @memberof PersonData
     */
    officePhoneNumber?: string;
    /**
     * The number of the organization unit that the person is assigned to.
     * @type {string}
     * @memberof PersonData
     */
    organizationUnitNumber?: string;
    /**
     * The unique identifier of the permanent establishment that the person is assigned to.
     * @type {string}
     * @memberof PersonData
     */
    permanentEstablishmentId?: string;
    /**
     * The user id assigned to the person. Used as the login name. Unique identifier.
     * @type {string}
     * @memberof PersonData
     */
    personId: string;
    /**
     * The personnel number assigned to the person. Unique identifier.
     * @type {string}
     * @memberof PersonData
     */
    personnelNumber: string;
    /**
     * The job title / position of the person, e.g. 'accountant'.
     * @type {string}
     * @memberof PersonData
     */
    position?: string;
    /**
     * The date on which the probationary period of the person ended or will end. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonData
     */
    probationEndDate?: Date;
    /**
     * The second nationality of the person (if any).
     * @type {string}
     * @memberof PersonData
     */
    secondNationality?: string;
    /**
     * The personnel number of the superior assigned to the person.
     * @type {string}
     * @memberof PersonData
     */
    superiorPersonnelNumber?: string;
    /**
     * A honorific used by the person, e.g. 'Dr.'.
     * @type {string}
     * @memberof PersonData
     */
    title?: string;
    /**
     * The date on which the work schedule assignment starts. Required if workScheduleId is set. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PersonData
     */
    workScheduleBeginDate?: Date;
    /**
     * The unique identifier of the work schedule assigned to the person.
     * @type {string}
     * @memberof PersonData
     */
    workScheduleId?: string;
    /**
     * German persons only. The highest school degree attained by the person.
     * @type {string}
     * @memberof PersonData
     */
    highestLevelOfEducation?: string;
    /**
     * 
     * @type {HighestLevelOfEducationId}
     * @memberof PersonData
     */
    highestLevelOfEducationId?: HighestLevelOfEducationId;
    /**
     * German persons only. The advanced education / university degree attained by the person.
     * @type {string}
     * @memberof PersonData
     */
    highestProfessionalQualification?: string;
    /**
     * 
     * @type {HighestProfessionalQualificationId}
     * @memberof PersonData
     */
    highestProfessionalQualificationId?: HighestProfessionalQualificationId;
    /**
     * German persons only. The person's social security number.
     * @type {string}
     * @memberof PersonData
     */
    socialSecurityNumber?: string;
    /**
     * German persons only. The person's taxpayer ID.
     * @type {string}
     * @memberof PersonData
     */
    taxpayerIdentificationNumber?: string;
    /**
     * Unique number which is created after creating a QR Code card for the person.
     * @type {string}
     * @memberof PersonData
     */
    personIdentifierForKiosk?: string;
    /**
     * The unique identifier of the time recording regulation assigned to the person.
     * @type {string}
     * @memberof PersonData
     */
    timeRecordingRegulationKey?: string;
}



/**
 * Check if a given object implements the PersonData interface.
 */
export function instanceOfPersonData(value: object): value is PersonData {
    if (!('personId' in value) || value['personId'] === undefined) return false;
    if (!('personnelNumber' in value) || value['personnelNumber'] === undefined) return false;
    return true;
}

export function PersonDataFromJSON(json: any): PersonData {
    return PersonDataFromJSONTyped(json, false);
}

export function PersonDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonData {
    if (json == null) {
        return json;
    }
    return {
        
        'accountPayable': json['accountPayable'] == null ? undefined : json['accountPayable'],
        'address': json['address'] == null ? undefined : AddressFromJSON(json['address']),
        'bankAccount': json['bankAccount'] == null ? undefined : BankAccountFromJSON(json['bankAccount']),
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'buildingOrRoom': json['buildingOrRoom'] == null ? undefined : json['buildingOrRoom'],
        'companyMobilePhoneNumber': json['companyMobilePhoneNumber'] == null ? undefined : json['companyMobilePhoneNumber'],
        'costCenterNumber': json['costCenterNumber'] == null ? undefined : json['costCenterNumber'],
        'costObjectiveNumber': json['costObjectiveNumber'] == null ? undefined : json['costObjectiveNumber'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'customNameId': json['customNameId'] == null ? undefined : json['customNameId'],
        'datevPersonnelNumber': json['datevPersonnelNumber'] == null ? undefined : json['datevPersonnelNumber'],
        'email': json['email'] == null ? undefined : json['email'],
        'employmentType': json['employmentType'] == null ? undefined : EmploymentTypeFromJSON(json['employmentType']),
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'gender': json['gender'] == null ? undefined : GenderFromJSON(json['gender']),
        'joinDate': json['joinDate'] == null ? undefined : (new Date(json['joinDate'])),
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'leaveDate': json['leaveDate'] == null ? undefined : (new Date(json['leaveDate'])),
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'officePhoneNumber': json['officePhoneNumber'] == null ? undefined : json['officePhoneNumber'],
        'organizationUnitNumber': json['organizationUnitNumber'] == null ? undefined : json['organizationUnitNumber'],
        'permanentEstablishmentId': json['permanentEstablishmentId'] == null ? undefined : json['permanentEstablishmentId'],
        'personId': json['personId'],
        'personnelNumber': json['personnelNumber'],
        'position': json['position'] == null ? undefined : json['position'],
        'probationEndDate': json['probationEndDate'] == null ? undefined : (new Date(json['probationEndDate'])),
        'secondNationality': json['secondNationality'] == null ? undefined : json['secondNationality'],
        'superiorPersonnelNumber': json['superiorPersonnelNumber'] == null ? undefined : json['superiorPersonnelNumber'],
        'title': json['title'] == null ? undefined : json['title'],
        'workScheduleBeginDate': json['workScheduleBeginDate'] == null ? undefined : (new Date(json['workScheduleBeginDate'])),
        'workScheduleId': json['workScheduleId'] == null ? undefined : json['workScheduleId'],
        'highestLevelOfEducation': json['highestLevelOfEducation'] == null ? undefined : json['highestLevelOfEducation'],
        'highestLevelOfEducationId': json['highestLevelOfEducationId'] == null ? undefined : HighestLevelOfEducationIdFromJSON(json['highestLevelOfEducationId']),
        'highestProfessionalQualification': json['highestProfessionalQualification'] == null ? undefined : json['highestProfessionalQualification'],
        'highestProfessionalQualificationId': json['highestProfessionalQualificationId'] == null ? undefined : HighestProfessionalQualificationIdFromJSON(json['highestProfessionalQualificationId']),
        'socialSecurityNumber': json['socialSecurityNumber'] == null ? undefined : json['socialSecurityNumber'],
        'taxpayerIdentificationNumber': json['taxpayerIdentificationNumber'] == null ? undefined : json['taxpayerIdentificationNumber'],
        'personIdentifierForKiosk': json['personIdentifierForKiosk'] == null ? undefined : json['personIdentifierForKiosk'],
        'timeRecordingRegulationKey': json['timeRecordingRegulationKey'] == null ? undefined : json['timeRecordingRegulationKey'],
    };
}

export function PersonDataToJSON(json: any): PersonData {
    return PersonDataToJSONTyped(json, false);
}

export function PersonDataToJSONTyped(value?: PersonData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountPayable': value['accountPayable'],
        'address': AddressToJSON(value['address']),
        'bankAccount': BankAccountToJSON(value['bankAccount']),
        'birthday': value['birthday'] == null ? value['birthday'] : value['birthday'].toISOString().substring(0,10),
        'buildingOrRoom': value['buildingOrRoom'],
        'companyMobilePhoneNumber': value['companyMobilePhoneNumber'],
        'costCenterNumber': value['costCenterNumber'],
        'costObjectiveNumber': value['costObjectiveNumber'],
        'countryCode': value['countryCode'],
        'customNameId': value['customNameId'],
        'datevPersonnelNumber': value['datevPersonnelNumber'],
        'email': value['email'],
        'employmentType': EmploymentTypeToJSON(value['employmentType']),
        'firstName': value['firstName'],
        'gender': GenderToJSON(value['gender']),
        'joinDate': value['joinDate'] == null ? value['joinDate'] : value['joinDate'].toISOString().substring(0,10),
        'lastName': value['lastName'],
        'leaveDate': value['leaveDate'] == null ? value['leaveDate'] : value['leaveDate'].toISOString().substring(0,10),
        'nationality': value['nationality'],
        'officePhoneNumber': value['officePhoneNumber'],
        'organizationUnitNumber': value['organizationUnitNumber'],
        'permanentEstablishmentId': value['permanentEstablishmentId'],
        'personId': value['personId'],
        'personnelNumber': value['personnelNumber'],
        'position': value['position'],
        'probationEndDate': value['probationEndDate'] == null ? value['probationEndDate'] : value['probationEndDate'].toISOString().substring(0,10),
        'secondNationality': value['secondNationality'],
        'superiorPersonnelNumber': value['superiorPersonnelNumber'],
        'title': value['title'],
        'workScheduleBeginDate': value['workScheduleBeginDate'] == null ? value['workScheduleBeginDate'] : value['workScheduleBeginDate'].toISOString().substring(0,10),
        'workScheduleId': value['workScheduleId'],
        'highestLevelOfEducation': value['highestLevelOfEducation'],
        'highestLevelOfEducationId': HighestLevelOfEducationIdToJSON(value['highestLevelOfEducationId']),
        'highestProfessionalQualification': value['highestProfessionalQualification'],
        'highestProfessionalQualificationId': HighestProfessionalQualificationIdToJSON(value['highestProfessionalQualificationId']),
        'socialSecurityNumber': value['socialSecurityNumber'],
        'taxpayerIdentificationNumber': value['taxpayerIdentificationNumber'],
        'personIdentifierForKiosk': value['personIdentifierForKiosk'],
        'timeRecordingRegulationKey': value['timeRecordingRegulationKey'],
    };
}

