/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The unique key of the place of work type of the post offer.
 * @export
 */
export const PlaceOfWorkTypeKey = {
    Hybrid: 'hybrid',
    Onsite: 'onsite',
    Remote: 'remote'
} as const;
export type PlaceOfWorkTypeKey = typeof PlaceOfWorkTypeKey[keyof typeof PlaceOfWorkTypeKey];


export function instanceOfPlaceOfWorkTypeKey(value: any): boolean {
    for (const key in PlaceOfWorkTypeKey) {
        if (Object.prototype.hasOwnProperty.call(PlaceOfWorkTypeKey, key)) {
            if (PlaceOfWorkTypeKey[key as keyof typeof PlaceOfWorkTypeKey] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PlaceOfWorkTypeKeyFromJSON(json: any): PlaceOfWorkTypeKey {
    return PlaceOfWorkTypeKeyFromJSONTyped(json, false);
}

export function PlaceOfWorkTypeKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceOfWorkTypeKey {
    return json as PlaceOfWorkTypeKey;
}

export function PlaceOfWorkTypeKeyToJSON(value?: PlaceOfWorkTypeKey | null): any {
    return value as any;
}

export function PlaceOfWorkTypeKeyToJSONTyped(value: any, ignoreDiscriminator: boolean): PlaceOfWorkTypeKey {
    return value as PlaceOfWorkTypeKey;
}

