/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaceOfWorkTypeKey } from './PlaceOfWorkTypeKey';
import {
    PlaceOfWorkTypeKeyFromJSON,
    PlaceOfWorkTypeKeyFromJSONTyped,
    PlaceOfWorkTypeKeyToJSON,
    PlaceOfWorkTypeKeyToJSONTyped,
} from './PlaceOfWorkTypeKey';
import type { WorkingTimeModelKey } from './WorkingTimeModelKey';
import {
    WorkingTimeModelKeyFromJSON,
    WorkingTimeModelKeyFromJSONTyped,
    WorkingTimeModelKeyToJSON,
    WorkingTimeModelKeyToJSONTyped,
} from './WorkingTimeModelKey';
import type { PermanentEstablishment } from './PermanentEstablishment';
import {
    PermanentEstablishmentFromJSON,
    PermanentEstablishmentFromJSONTyped,
    PermanentEstablishmentToJSON,
    PermanentEstablishmentToJSONTyped,
} from './PermanentEstablishment';
import type { EmploymentContractTypeKey } from './EmploymentContractTypeKey';
import {
    EmploymentContractTypeKeyFromJSON,
    EmploymentContractTypeKeyFromJSONTyped,
    EmploymentContractTypeKeyToJSON,
    EmploymentContractTypeKeyToJSONTyped,
} from './EmploymentContractTypeKey';
import type { CareerLevelKey } from './CareerLevelKey';
import {
    CareerLevelKeyFromJSON,
    CareerLevelKeyFromJSONTyped,
    CareerLevelKeyToJSON,
    CareerLevelKeyToJSONTyped,
} from './CareerLevelKey';

/**
 * Representation of a post offer. Used in applicant management endpoints.
 * @export
 * @interface PostOffer
 */
export interface PostOffer {
    /**
     * The ID of the postOffer.
     * @type {string}
     * @memberof PostOffer
     */
    id?: string;
    /**
     * The post offer name suffix to show after the display name of the post.
     * @type {string}
     * @memberof PostOffer
     */
    postOfferNameSuffix?: string;
    /**
     * 
     * @type {Array<PermanentEstablishment>}
     * @memberof PostOffer
     */
    permanentEstablishments?: Array<PermanentEstablishment>;
    /**
     * The translated place of work type of the post offer, e.g. 'hybrid'.
     * @type {string}
     * @memberof PostOffer
     */
    placeOfWorkType?: string;
    /**
     * 
     * @type {PlaceOfWorkTypeKey}
     * @memberof PostOffer
     */
    placeOfWorkTypeKey?: PlaceOfWorkTypeKey;
    /**
     * The translated employment contract type of the post offer.
     * @type {string}
     * @memberof PostOffer
     */
    employmentContract?: string;
    /**
     * 
     * @type {EmploymentContractTypeKey}
     * @memberof PostOffer
     */
    employmentContractKey?: EmploymentContractTypeKey;
    /**
     * The career level of the post offer, e.g. 'Professional'.
     * @type {string}
     * @memberof PostOffer
     */
    careerLevel?: string;
    /**
     * 
     * @type {CareerLevelKey}
     * @memberof PostOffer
     */
    careerLevelKey?: CareerLevelKey;
    /**
     * Description of the post offer.
     * @type {string}
     * @memberof PostOffer
     */
    description?: string;
    /**
     * The name of the post offer to display in job portals.
     * @type {string}
     * @memberof PostOffer
     */
    displayName?: string;
    /**
     * Given job portal of the post offer.
     * @type {string}
     * @memberof PostOffer
     */
    jobPortal?: string;
    /**
     * The priority of the post offer.
     * @type {number}
     * @memberof PostOffer
     */
    priority?: number;
    /**
     * The date on which the post offer should be published. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PostOffer
     */
    publicationDate?: Date;
    /**
     * The date after which the post offer expires. Only present, if the visibility of the offer is set to a limited period of time. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof PostOffer
     */
    validUntilDate?: Date;
    /**
     * The translated name of the working time model of the post offer.
     * @type {string}
     * @memberof PostOffer
     */
    workingTimeModel?: string;
    /**
     * 
     * @type {WorkingTimeModelKey}
     * @memberof PostOffer
     */
    workingTimeModelKey?: WorkingTimeModelKey;
    /**
     * Specifies if the post offer is set to active.
     * @type {boolean}
     * @memberof PostOffer
     */
    isActive?: boolean;
}



/**
 * Check if a given object implements the PostOffer interface.
 */
export function instanceOfPostOffer(value: object): value is PostOffer {
    return true;
}

export function PostOfferFromJSON(json: any): PostOffer {
    return PostOfferFromJSONTyped(json, false);
}

export function PostOfferFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostOffer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'postOfferNameSuffix': json['postOfferNameSuffix'] == null ? undefined : json['postOfferNameSuffix'],
        'permanentEstablishments': json['permanentEstablishments'] == null ? undefined : ((json['permanentEstablishments'] as Array<any>).map(PermanentEstablishmentFromJSON)),
        'placeOfWorkType': json['placeOfWorkType'] == null ? undefined : json['placeOfWorkType'],
        'placeOfWorkTypeKey': json['placeOfWorkTypeKey'] == null ? undefined : PlaceOfWorkTypeKeyFromJSON(json['placeOfWorkTypeKey']),
        'employmentContract': json['employmentContract'] == null ? undefined : json['employmentContract'],
        'employmentContractKey': json['employmentContractKey'] == null ? undefined : EmploymentContractTypeKeyFromJSON(json['employmentContractKey']),
        'careerLevel': json['careerLevel'] == null ? undefined : json['careerLevel'],
        'careerLevelKey': json['careerLevelKey'] == null ? undefined : CareerLevelKeyFromJSON(json['careerLevelKey']),
        'description': json['description'] == null ? undefined : json['description'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'jobPortal': json['jobPortal'] == null ? undefined : json['jobPortal'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'publicationDate': json['publicationDate'] == null ? undefined : (new Date(json['publicationDate'])),
        'validUntilDate': json['validUntilDate'] == null ? undefined : (new Date(json['validUntilDate'])),
        'workingTimeModel': json['workingTimeModel'] == null ? undefined : json['workingTimeModel'],
        'workingTimeModelKey': json['workingTimeModelKey'] == null ? undefined : WorkingTimeModelKeyFromJSON(json['workingTimeModelKey']),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function PostOfferToJSON(json: any): PostOffer {
    return PostOfferToJSONTyped(json, false);
}

export function PostOfferToJSONTyped(value?: PostOffer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'postOfferNameSuffix': value['postOfferNameSuffix'],
        'permanentEstablishments': value['permanentEstablishments'] == null ? undefined : ((value['permanentEstablishments'] as Array<any>).map(PermanentEstablishmentToJSON)),
        'placeOfWorkType': value['placeOfWorkType'],
        'placeOfWorkTypeKey': PlaceOfWorkTypeKeyToJSON(value['placeOfWorkTypeKey']),
        'employmentContract': value['employmentContract'],
        'employmentContractKey': EmploymentContractTypeKeyToJSON(value['employmentContractKey']),
        'careerLevel': value['careerLevel'],
        'careerLevelKey': CareerLevelKeyToJSON(value['careerLevelKey']),
        'description': value['description'],
        'displayName': value['displayName'],
        'jobPortal': value['jobPortal'],
        'priority': value['priority'],
        'publicationDate': value['publicationDate'] == null ? value['publicationDate'] : value['publicationDate'].toISOString().substring(0,10),
        'validUntilDate': value['validUntilDate'] == null ? value['validUntilDate'] : value['validUntilDate'].toISOString().substring(0,10),
        'workingTimeModel': value['workingTimeModel'],
        'workingTimeModelKey': WorkingTimeModelKeyToJSON(value['workingTimeModelKey']),
        'isActive': value['isActive'],
    };
}

