/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TitleDescriptionPair } from './TitleDescriptionPair';
import {
    TitleDescriptionPairFromJSON,
    TitleDescriptionPairFromJSONTyped,
    TitleDescriptionPairToJSON,
    TitleDescriptionPairToJSONTyped,
} from './TitleDescriptionPair';

/**
 * Description texts of a post. Used in applicant management endpoints.
 * @export
 * @interface PostDescriptions
 */
export interface PostDescriptions {
    /**
     * 
     * @type {TitleDescriptionPair}
     * @memberof PostDescriptions
     */
    introduction?: TitleDescriptionPair;
    /**
     * 
     * @type {TitleDescriptionPair}
     * @memberof PostDescriptions
     */
    tasks?: TitleDescriptionPair;
    /**
     * 
     * @type {TitleDescriptionPair}
     * @memberof PostDescriptions
     */
    profile?: TitleDescriptionPair;
    /**
     * 
     * @type {TitleDescriptionPair}
     * @memberof PostDescriptions
     */
    offer?: TitleDescriptionPair;
    /**
     * 
     * @type {TitleDescriptionPair}
     * @memberof PostDescriptions
     */
    summary?: TitleDescriptionPair;
}

/**
 * Check if a given object implements the PostDescriptions interface.
 */
export function instanceOfPostDescriptions(value: object): value is PostDescriptions {
    return true;
}

export function PostDescriptionsFromJSON(json: any): PostDescriptions {
    return PostDescriptionsFromJSONTyped(json, false);
}

export function PostDescriptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDescriptions {
    if (json == null) {
        return json;
    }
    return {
        
        'introduction': json['introduction'] == null ? undefined : TitleDescriptionPairFromJSON(json['introduction']),
        'tasks': json['tasks'] == null ? undefined : TitleDescriptionPairFromJSON(json['tasks']),
        'profile': json['profile'] == null ? undefined : TitleDescriptionPairFromJSON(json['profile']),
        'offer': json['offer'] == null ? undefined : TitleDescriptionPairFromJSON(json['offer']),
        'summary': json['summary'] == null ? undefined : TitleDescriptionPairFromJSON(json['summary']),
    };
}

export function PostDescriptionsToJSON(json: any): PostDescriptions {
    return PostDescriptionsToJSONTyped(json, false);
}

export function PostDescriptionsToJSONTyped(value?: PostDescriptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'introduction': TitleDescriptionPairToJSON(value['introduction']),
        'tasks': TitleDescriptionPairToJSON(value['tasks']),
        'profile': TitleDescriptionPairToJSON(value['profile']),
        'offer': TitleDescriptionPairToJSON(value['offer']),
        'summary': TitleDescriptionPairToJSON(value['summary']),
    };
}

