/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The purpose the account is used for.
 * @export
 */
export const ReceiptTypeAccountPurpose = {
    AncillaryServices: 'ancillaryServices',
    Breakfast: 'breakfast',
    PrimaryAccount: 'primaryAccount',
    Drinks: 'drinks',
    Tip: 'tip'
} as const;
export type ReceiptTypeAccountPurpose = typeof ReceiptTypeAccountPurpose[keyof typeof ReceiptTypeAccountPurpose];


export function instanceOfReceiptTypeAccountPurpose(value: any): boolean {
    for (const key in ReceiptTypeAccountPurpose) {
        if (Object.prototype.hasOwnProperty.call(ReceiptTypeAccountPurpose, key)) {
            if (ReceiptTypeAccountPurpose[key as keyof typeof ReceiptTypeAccountPurpose] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReceiptTypeAccountPurposeFromJSON(json: any): ReceiptTypeAccountPurpose {
    return ReceiptTypeAccountPurposeFromJSONTyped(json, false);
}

export function ReceiptTypeAccountPurposeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptTypeAccountPurpose {
    return json as ReceiptTypeAccountPurpose;
}

export function ReceiptTypeAccountPurposeToJSON(value?: ReceiptTypeAccountPurpose | null): any {
    return value as any;
}

export function ReceiptTypeAccountPurposeToJSONTyped(value: any, ignoreDiscriminator: boolean): ReceiptTypeAccountPurpose {
    return value as ReceiptTypeAccountPurpose;
}

