/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReceiptCategory = {
    HotelWithAncillaryServices: 'hotelWithAncillaryServices',
    Hotel: 'hotel',
    Gift: 'gift',
    DefaultReceipt: 'defaultReceipt',
    BusinessEntertainmentSeparateDrinks: 'businessEntertainmentSeparateDrinks',
    BusinessEntertainment: 'businessEntertainment'
} as const;
export type ReceiptCategory = typeof ReceiptCategory[keyof typeof ReceiptCategory];


export function instanceOfReceiptCategory(value: any): boolean {
    for (const key in ReceiptCategory) {
        if (Object.prototype.hasOwnProperty.call(ReceiptCategory, key)) {
            if (ReceiptCategory[key as keyof typeof ReceiptCategory] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReceiptCategoryFromJSON(json: any): ReceiptCategory {
    return ReceiptCategoryFromJSONTyped(json, false);
}

export function ReceiptCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptCategory {
    return json as ReceiptCategory;
}

export function ReceiptCategoryToJSON(value?: ReceiptCategory | null): any {
    return value as any;
}

export function ReceiptCategoryToJSONTyped(value: any, ignoreDiscriminator: boolean): ReceiptCategory {
    return value as ReceiptCategory;
}

