/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RemoteWorkStatus } from './RemoteWorkStatus';
import {
    RemoteWorkStatusFromJSON,
    RemoteWorkStatusFromJSONTyped,
    RemoteWorkStatusToJSON,
    RemoteWorkStatusToJSONTyped,
} from './RemoteWorkStatus';

/**
 * Describes the attributes that can be set while creating/editing remote work via the API.
 * @export
 * @interface RemoteWorkData
 */
export interface RemoteWorkData {
    /**
     * The start date of the remote work. Date in YYYY-MM-DD format
     * @type {Date}
     * @memberof RemoteWorkData
     */
    beginDate?: Date;
    /**
     * The end date of the remote work. Date in YYYY-MM-DD format
     * @type {Date}
     * @memberof RemoteWorkData
     */
    endDate?: Date;
    /**
     * Specifies whether the remote work spans only the afternoon of the first day (or only the afternoon for one-day absences).
     * @type {boolean}
     * @memberof RemoteWorkData
     */
    isBeginDateHalfDay?: boolean | null;
    /**
     * Specifies whether the remote work spans only the forenoon of the last day (or only the forenoon for one-day absences).
     * @type {boolean}
     * @memberof RemoteWorkData
     */
    isEndDateHalfDay?: boolean | null;
    /**
     * 
     * @type {RemoteWorkStatus}
     * @memberof RemoteWorkData
     */
    statusIdentifier?: RemoteWorkStatus | null;
}



/**
 * Check if a given object implements the RemoteWorkData interface.
 */
export function instanceOfRemoteWorkData(value: object): value is RemoteWorkData {
    return true;
}

export function RemoteWorkDataFromJSON(json: any): RemoteWorkData {
    return RemoteWorkDataFromJSONTyped(json, false);
}

export function RemoteWorkDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteWorkData {
    if (json == null) {
        return json;
    }
    return {
        
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'isBeginDateHalfDay': json['isBeginDateHalfDay'] == null ? undefined : json['isBeginDateHalfDay'],
        'isEndDateHalfDay': json['isEndDateHalfDay'] == null ? undefined : json['isEndDateHalfDay'],
        'statusIdentifier': json['statusIdentifier'] == null ? undefined : RemoteWorkStatusFromJSON(json['statusIdentifier']),
    };
}

export function RemoteWorkDataToJSON(json: any): RemoteWorkData {
    return RemoteWorkDataToJSONTyped(json, false);
}

export function RemoteWorkDataToJSONTyped(value?: RemoteWorkData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'isBeginDateHalfDay': value['isBeginDateHalfDay'],
        'isEndDateHalfDay': value['isEndDateHalfDay'],
        'statusIdentifier': RemoteWorkStatusToJSON(value['statusIdentifier']),
    };
}

