/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The salutation of the descripted person
 * @export
 */
export const Salutation = {
    Mr: 'mr',
    Ms: 'ms',
    None: 'none'
} as const;
export type Salutation = typeof Salutation[keyof typeof Salutation];


export function instanceOfSalutation(value: any): boolean {
    for (const key in Salutation) {
        if (Object.prototype.hasOwnProperty.call(Salutation, key)) {
            if (Salutation[key as keyof typeof Salutation] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SalutationFromJSON(json: any): Salutation {
    return SalutationFromJSONTyped(json, false);
}

export function SalutationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Salutation {
    return json as Salutation;
}

export function SalutationToJSON(value?: Salutation | null): any {
    return value as any;
}

export function SalutationToJSONTyped(value: any, ignoreDiscriminator: boolean): Salutation {
    return value as Salutation;
}

