/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The unique key of the scope of activities of the post.
 * @export
 */
export const ScopeOfActivitiesKey = {
    Administration: 'administration',
    AnalysisAndStatistics: 'analysisAndStatistics',
    Consulting: 'consulting',
    CustomerService: 'customerService',
    EngineeringAndTechnical: 'engineeringAndTechnical',
    FinanceAccountingAndControlling: 'financeAccountingAndControlling',
    GraphicDesignAndArchitecture: 'graphicDesignAndArchitecture',
    HealthMedicalAndSocial: 'healthMedicalAndSocial',
    Hr: 'hr',
    ItAndSoftwareDevelopment: 'itAndSoftwareDevelopment',
    Legal: 'legal',
    ManagementAndCorporateDevelopment: 'managementAndCorporateDevelopment',
    MarketingAndAdvertising: 'marketingAndAdvertising',
    NotSpecified: 'notSpecified',
    OtherDisciplines: 'otherDisciplines',
    PrAndJournalism: 'prAndJournalism',
    ProcessPlanningAndQa: 'processPlanningAndQa',
    ProductionAndManufacturing: 'productionAndManufacturing',
    ProductManagement: 'productManagement',
    ProjectManagement: 'projectManagement',
    PurchasingMaterialsManagementAndLogistics: 'purchasingMaterialsManagementAndLogistics',
    SalesAndCommerce: 'salesAndCommerce',
    ResearchAndDevelopment: 'researchAndDevelopment'
} as const;
export type ScopeOfActivitiesKey = typeof ScopeOfActivitiesKey[keyof typeof ScopeOfActivitiesKey];


export function instanceOfScopeOfActivitiesKey(value: any): boolean {
    for (const key in ScopeOfActivitiesKey) {
        if (Object.prototype.hasOwnProperty.call(ScopeOfActivitiesKey, key)) {
            if (ScopeOfActivitiesKey[key as keyof typeof ScopeOfActivitiesKey] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScopeOfActivitiesKeyFromJSON(json: any): ScopeOfActivitiesKey {
    return ScopeOfActivitiesKeyFromJSONTyped(json, false);
}

export function ScopeOfActivitiesKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScopeOfActivitiesKey {
    return json as ScopeOfActivitiesKey;
}

export function ScopeOfActivitiesKeyToJSON(value?: ScopeOfActivitiesKey | null): any {
    return value as any;
}

export function ScopeOfActivitiesKeyToJSONTyped(value: any, ignoreDiscriminator: boolean): ScopeOfActivitiesKey {
    return value as ScopeOfActivitiesKey;
}

