/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SingleResult } from './SingleResult';
import {
    SingleResultFromJSON,
    SingleResultFromJSONTyped,
    SingleResultToJSON,
    SingleResultToJSONTyped,
} from './SingleResult';
import type { DataError } from './DataError';
import {
    DataErrorFromJSON,
    DataErrorFromJSONTyped,
    DataErrorToJSON,
    DataErrorToJSONTyped,
} from './DataError';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * 
 * @export
 * @interface SingleWriteRequestResult
 */
export interface SingleWriteRequestResult {
    /**
     * A collection of all general errors that occurred during the write request. Not included if no errors occurred.
     * @type {Array<ApiError>}
     * @memberof SingleWriteRequestResult
     */
    generalErrors?: Array<ApiError>;
    /**
     * A collection of all object-specific errors that occurred during the write request. A write request is aborted as soon as an error occurs, so this error collection may be incomplete. Each error contains a recordId that allows matching the errors to input data.
     * @type {Array<DataError>}
     * @memberof SingleWriteRequestResult
     */
    dataErrors?: Array<DataError>;
    /**
     * 
     * @type {string}
     * @memberof SingleWriteRequestResult
     */
    status?: string;
    /**
     * 
     * @type {SingleResult}
     * @memberof SingleWriteRequestResult
     */
    result?: SingleResult;
}

/**
 * Check if a given object implements the SingleWriteRequestResult interface.
 */
export function instanceOfSingleWriteRequestResult(value: object): value is SingleWriteRequestResult {
    return true;
}

export function SingleWriteRequestResultFromJSON(json: any): SingleWriteRequestResult {
    return SingleWriteRequestResultFromJSONTyped(json, false);
}

export function SingleWriteRequestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleWriteRequestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'generalErrors': json['generalErrors'] == null ? undefined : ((json['generalErrors'] as Array<any>).map(ApiErrorFromJSON)),
        'dataErrors': json['dataErrors'] == null ? undefined : ((json['dataErrors'] as Array<any>).map(DataErrorFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
        'result': json['result'] == null ? undefined : SingleResultFromJSON(json['result']),
    };
}

export function SingleWriteRequestResultToJSON(json: any): SingleWriteRequestResult {
    return SingleWriteRequestResultToJSONTyped(json, false);
}

export function SingleWriteRequestResultToJSONTyped(value?: SingleWriteRequestResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generalErrors': value['generalErrors'] == null ? undefined : ((value['generalErrors'] as Array<any>).map(ApiErrorToJSON)),
        'dataErrors': value['dataErrors'] == null ? undefined : ((value['dataErrors'] as Array<any>).map(DataErrorToJSON)),
        'status': value['status'],
        'result': SingleResultToJSON(value['result']),
    };
}

