/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SingleResultDataValue } from './SingleResultDataValue';
import {
    SingleResultDataValueFromJSON,
    SingleResultDataValueFromJSONTyped,
    SingleResultDataValueToJSON,
    SingleResultDataValueToJSONTyped,
} from './SingleResultDataValue';
import type { ObjectManipulationNotification } from './ObjectManipulationNotification';
import {
    ObjectManipulationNotificationFromJSON,
    ObjectManipulationNotificationFromJSONTyped,
    ObjectManipulationNotificationToJSON,
    ObjectManipulationNotificationToJSONTyped,
} from './ObjectManipulationNotification';

/**
 * A wrapper object for a single-object result of a write (PUT/POST/DELETE) request against the HR WORKS API.
 * @export
 * @interface SingleResult
 */
export interface SingleResult {
    /**
     * A collection of all errors that occurred during the manipulation of this object. Not included if no errors occurred.
     * @type {Array<ObjectManipulationNotification>}
     * @memberof SingleResult
     */
    errors?: Array<ObjectManipulationNotification>;
    /**
     * A collection of all warnings that occurred during the manipulation of this object. Not included if no warnings occurred. Warnings are IGNORED by the HR WORKS server when processing API write requests.
     * @type {Array<ObjectManipulationNotification>}
     * @memberof SingleResult
     */
    warnings?: Array<ObjectManipulationNotification>;
    /**
     * The recordId of the object, corresponding to the object order in the write request. (Starts at 1, not 0!)
     * @type {number}
     * @memberof SingleResult
     */
    recordId?: number;
    /**
     * A JSON representation of the object that was  manipulated or created via the API request. May only contain an abridged version of the data.
     * @type {{ [key: string]: SingleResultDataValue; }}
     * @memberof SingleResult
     */
    data?: { [key: string]: SingleResultDataValue; };
    /**
     * A link to the single-resource endpoint for the manipulated resource.
     * @type {string}
     * @memberof SingleResult
     */
    resourceLocation?: string;
}

/**
 * Check if a given object implements the SingleResult interface.
 */
export function instanceOfSingleResult(value: object): value is SingleResult {
    return true;
}

export function SingleResultFromJSON(json: any): SingleResult {
    return SingleResultFromJSONTyped(json, false);
}

export function SingleResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleResult {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ObjectManipulationNotificationFromJSON)),
        'warnings': json['warnings'] == null ? undefined : ((json['warnings'] as Array<any>).map(ObjectManipulationNotificationFromJSON)),
        'recordId': json['recordId'] == null ? undefined : json['recordId'],
        'data': json['data'] == null ? undefined : (mapValues(json['data'], SingleResultDataValueFromJSON)),
        'resourceLocation': json['resourceLocation'] == null ? undefined : json['resourceLocation'],
    };
}

export function SingleResultToJSON(json: any): SingleResult {
    return SingleResultToJSONTyped(json, false);
}

export function SingleResultToJSONTyped(value?: SingleResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ObjectManipulationNotificationToJSON)),
        'warnings': value['warnings'] == null ? undefined : ((value['warnings'] as Array<any>).map(ObjectManipulationNotificationToJSON)),
        'recordId': value['recordId'],
        'data': value['data'] == null ? undefined : (mapValues(value['data'], SingleResultDataValueToJSON)),
        'resourceLocation': value['resourceLocation'],
    };
}

