/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataError } from './DataError';
import {
    DataErrorFromJSON,
    DataErrorFromJSONTyped,
    DataErrorToJSON,
    DataErrorToJSONTyped,
} from './DataError';
import type { SingleDeleteResult } from './SingleDeleteResult';
import {
    SingleDeleteResultFromJSON,
    SingleDeleteResultFromJSONTyped,
    SingleDeleteResultToJSON,
    SingleDeleteResultToJSONTyped,
} from './SingleDeleteResult';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * 
 * @export
 * @interface SingleDeleteRequestResult
 */
export interface SingleDeleteRequestResult {
    /**
     * A collection of all general errors that occurred during the write request. Not included if no errors occurred.
     * @type {Array<ApiError>}
     * @memberof SingleDeleteRequestResult
     */
    generalErrors?: Array<ApiError>;
    /**
     * A collection of all object-specific errors that occurred during the write request. A write request is aborted as soon as an error occurs, so this error collection may be incomplete. Each error contains a recordId that allows matching the errors to input data.
     * @type {Array<DataError>}
     * @memberof SingleDeleteRequestResult
     */
    dataErrors?: Array<DataError>;
    /**
     * 
     * @type {string}
     * @memberof SingleDeleteRequestResult
     */
    status?: string;
    /**
     * 
     * @type {SingleDeleteResult}
     * @memberof SingleDeleteRequestResult
     */
    result?: SingleDeleteResult;
}

/**
 * Check if a given object implements the SingleDeleteRequestResult interface.
 */
export function instanceOfSingleDeleteRequestResult(value: object): value is SingleDeleteRequestResult {
    return true;
}

export function SingleDeleteRequestResultFromJSON(json: any): SingleDeleteRequestResult {
    return SingleDeleteRequestResultFromJSONTyped(json, false);
}

export function SingleDeleteRequestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleDeleteRequestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'generalErrors': json['generalErrors'] == null ? undefined : ((json['generalErrors'] as Array<any>).map(ApiErrorFromJSON)),
        'dataErrors': json['dataErrors'] == null ? undefined : ((json['dataErrors'] as Array<any>).map(DataErrorFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
        'result': json['result'] == null ? undefined : SingleDeleteResultFromJSON(json['result']),
    };
}

export function SingleDeleteRequestResultToJSON(json: any): SingleDeleteRequestResult {
    return SingleDeleteRequestResultToJSONTyped(json, false);
}

export function SingleDeleteRequestResultToJSONTyped(value?: SingleDeleteRequestResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generalErrors': value['generalErrors'] == null ? undefined : ((value['generalErrors'] as Array<any>).map(ApiErrorToJSON)),
        'dataErrors': value['dataErrors'] == null ? undefined : ((value['dataErrors'] as Array<any>).map(DataErrorToJSON)),
        'status': value['status'],
        'result': SingleDeleteResultToJSON(value['result']),
    };
}

