/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WriteRequestResponse } from './WriteRequestResponse';
import {
    WriteRequestResponseFromJSON,
    WriteRequestResponseFromJSONTyped,
    WriteRequestResponseToJSON,
    WriteRequestResponseToJSONTyped,
} from './WriteRequestResponse';
import type { SingleWriteRequestResult } from './SingleWriteRequestResult';
import {
    SingleWriteRequestResultFromJSON,
    SingleWriteRequestResultFromJSONTyped,
    SingleWriteRequestResultToJSON,
    SingleWriteRequestResultToJSONTyped,
} from './SingleWriteRequestResult';

/**
 * 
 * @export
 * @interface SingleWriteRequestResponse
 */
export interface SingleWriteRequestResponse extends WriteRequestResponse {
    /**
     * 
     * @type {SingleWriteRequestResult}
     * @memberof SingleWriteRequestResponse
     */
    apiResponse?: SingleWriteRequestResult;
}

/**
 * Check if a given object implements the SingleWriteRequestResponse interface.
 */
export function instanceOfSingleWriteRequestResponse(value: object): value is SingleWriteRequestResponse {
    return true;
}

export function SingleWriteRequestResponseFromJSON(json: any): SingleWriteRequestResponse {
    return SingleWriteRequestResponseFromJSONTyped(json, false);
}

export function SingleWriteRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleWriteRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        ...WriteRequestResponseFromJSONTyped(json, true),
        'apiResponse': json['apiResponse'] == null ? undefined : SingleWriteRequestResultFromJSON(json['apiResponse']),
    };
}

export function SingleWriteRequestResponseToJSON(json: any): SingleWriteRequestResponse {
    return SingleWriteRequestResponseToJSONTyped(json, false);
}

export function SingleWriteRequestResponseToJSONTyped(value?: SingleWriteRequestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...WriteRequestResponseToJSONTyped(value, true),
        'apiResponse': SingleWriteRequestResultToJSON(value['apiResponse']),
    };
}

