/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines a reference point in time.
 * @export
 */
export const TimeReference = {
    EndOfMonth: 'endOfMonth',
    EndOfQuarter: 'endOfQuarter',
    EndOfYear: 'endOfYear',
    FifteenthOfMonth: 'fifteenthOfMonth',
    FifteenthOrEndOfMonth: 'fifteenthOrEndOfMonth',
    OnEveryDay: 'onEveryDay'
} as const;
export type TimeReference = typeof TimeReference[keyof typeof TimeReference];


export function instanceOfTimeReference(value: any): boolean {
    for (const key in TimeReference) {
        if (Object.prototype.hasOwnProperty.call(TimeReference, key)) {
            if (TimeReference[key as keyof typeof TimeReference] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TimeReferenceFromJSON(json: any): TimeReference {
    return TimeReferenceFromJSONTyped(json, false);
}

export function TimeReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeReference {
    return json as TimeReference;
}

export function TimeReferenceToJSON(value?: TimeReference | null): any {
    return value as any;
}

export function TimeReferenceToJSONTyped(value: any, ignoreDiscriminator: boolean): TimeReference {
    return value as TimeReference;
}

