/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeTrackingProjectStatus } from './TimeTrackingProjectStatus';
import {
    TimeTrackingProjectStatusFromJSON,
    TimeTrackingProjectStatusFromJSONTyped,
    TimeTrackingProjectStatusToJSON,
    TimeTrackingProjectStatusToJSONTyped,
} from './TimeTrackingProjectStatus';

/**
 * Object representing a single time tracking project.
 * @export
 * @interface TimeTrackingProjectData
 */
export interface TimeTrackingProjectData {
    /**
     * The id of the time tracking project.
     * @type {string}
     * @memberof TimeTrackingProjectData
     */
    id: string;
    /**
     * The name of the time tracking project.
     * @type {string}
     * @memberof TimeTrackingProjectData
     */
    name: string;
    /**
     * The begin date of the time tracking project in YYYY-MM-DD format.
     * @type {Date}
     * @memberof TimeTrackingProjectData
     */
    beginDate: Date;
    /**
     * The end date of the time tracking project in YYYY-MM-DD format.
     * @type {Date}
     * @memberof TimeTrackingProjectData
     */
    endDate?: Date | null;
    /**
     * The description of the time tracking project.
     * @type {string}
     * @memberof TimeTrackingProjectData
     */
    description?: string | null;
    /**
     * Set the parent project id.
     * @type {string}
     * @memberof TimeTrackingProjectData
     */
    parentProjectId?: string | null;
    /**
     * 
     * @type {TimeTrackingProjectStatus}
     * @memberof TimeTrackingProjectData
     */
    status: TimeTrackingProjectStatus | null;
    /**
     * The hourly budget in minutes. This is required for sub projects or projects without sub projects.
     * @type {number}
     * @memberof TimeTrackingProjectData
     */
    hourlyBudget?: number | null;
    /**
     * The personnel number of the project manager.
     * @type {string}
     * @memberof TimeTrackingProjectData
     */
    projectManagerPersonnelNumber: string;
    /**
     * The unique id of the customer.
     * @type {string}
     * @memberof TimeTrackingProjectData
     */
    customerId: string;
}



/**
 * Check if a given object implements the TimeTrackingProjectData interface.
 */
export function instanceOfTimeTrackingProjectData(value: object): value is TimeTrackingProjectData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('beginDate' in value) || value['beginDate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('projectManagerPersonnelNumber' in value) || value['projectManagerPersonnelNumber'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    return true;
}

export function TimeTrackingProjectDataFromJSON(json: any): TimeTrackingProjectData {
    return TimeTrackingProjectDataFromJSONTyped(json, false);
}

export function TimeTrackingProjectDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeTrackingProjectData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'beginDate': (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'description': json['description'] == null ? undefined : json['description'],
        'parentProjectId': json['parentProjectId'] == null ? undefined : json['parentProjectId'],
        'status': TimeTrackingProjectStatusFromJSON(json['status']),
        'hourlyBudget': json['hourlyBudget'] == null ? undefined : json['hourlyBudget'],
        'projectManagerPersonnelNumber': json['projectManagerPersonnelNumber'],
        'customerId': json['customerId'],
    };
}

export function TimeTrackingProjectDataToJSON(json: any): TimeTrackingProjectData {
    return TimeTrackingProjectDataToJSONTyped(json, false);
}

export function TimeTrackingProjectDataToJSONTyped(value?: TimeTrackingProjectData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'beginDate': value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'description': value['description'],
        'parentProjectId': value['parentProjectId'],
        'status': TimeTrackingProjectStatusToJSON(value['status']),
        'hourlyBudget': value['hourlyBudget'],
        'projectManagerPersonnelNumber': value['projectManagerPersonnelNumber'],
        'customerId': value['customerId'],
    };
}

