/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeTrackingProjectCustomer
 */
export interface TimeTrackingProjectCustomer {
    /**
     * The unique identifier of the customer.
     * @type {string}
     * @memberof TimeTrackingProjectCustomer
     */
    id?: string;
    /**
     * The customer number.
     * @type {string}
     * @memberof TimeTrackingProjectCustomer
     */
    number?: string;
    /**
     * Name of the customer.
     * @type {string}
     * @memberof TimeTrackingProjectCustomer
     */
    name?: string;
    /**
     * Indicates whether the customer is currently in use.
     * @type {boolean}
     * @memberof TimeTrackingProjectCustomer
     */
    isActive?: boolean;
    /**
     * The number of active projects of the customer.
     * @type {number}
     * @memberof TimeTrackingProjectCustomer
     */
    activeProjectCount?: number;
    /**
     * The number of projects of the customer.
     * @type {number}
     * @memberof TimeTrackingProjectCustomer
     */
    totalProjectCount?: number;
}

/**
 * Check if a given object implements the TimeTrackingProjectCustomer interface.
 */
export function instanceOfTimeTrackingProjectCustomer(value: object): value is TimeTrackingProjectCustomer {
    return true;
}

export function TimeTrackingProjectCustomerFromJSON(json: any): TimeTrackingProjectCustomer {
    return TimeTrackingProjectCustomerFromJSONTyped(json, false);
}

export function TimeTrackingProjectCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeTrackingProjectCustomer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'number': json['number'] == null ? undefined : json['number'],
        'name': json['name'] == null ? undefined : json['name'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'activeProjectCount': json['activeProjectCount'] == null ? undefined : json['activeProjectCount'],
        'totalProjectCount': json['totalProjectCount'] == null ? undefined : json['totalProjectCount'],
    };
}

export function TimeTrackingProjectCustomerToJSON(json: any): TimeTrackingProjectCustomer {
    return TimeTrackingProjectCustomerToJSONTyped(json, false);
}

export function TimeTrackingProjectCustomerToJSONTyped(value?: TimeTrackingProjectCustomer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'number': value['number'],
        'name': value['name'],
        'isActive': value['isActive'],
        'activeProjectCount': value['activeProjectCount'],
        'totalProjectCount': value['totalProjectCount'],
    };
}

