/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TimeTrackingProjectStatus = {
    Active: 'active',
    Completed: 'completed',
    Planned: 'planned',
    Blocked: 'blocked'
} as const;
export type TimeTrackingProjectStatus = typeof TimeTrackingProjectStatus[keyof typeof TimeTrackingProjectStatus];


export function instanceOfTimeTrackingProjectStatus(value: any): boolean {
    for (const key in TimeTrackingProjectStatus) {
        if (Object.prototype.hasOwnProperty.call(TimeTrackingProjectStatus, key)) {
            if (TimeTrackingProjectStatus[key as keyof typeof TimeTrackingProjectStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TimeTrackingProjectStatusFromJSON(json: any): TimeTrackingProjectStatus {
    return TimeTrackingProjectStatusFromJSONTyped(json, false);
}

export function TimeTrackingProjectStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeTrackingProjectStatus {
    return json as TimeTrackingProjectStatus;
}

export function TimeTrackingProjectStatusToJSON(value?: TimeTrackingProjectStatus | null): any {
    return value as any;
}

export function TimeTrackingProjectStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): TimeTrackingProjectStatus {
    return value as TimeTrackingProjectStatus;
}

