/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The current time recording regulation.
 * @export
 * @interface TimeRecordingRegulationBaseData
 */
export interface TimeRecordingRegulationBaseData {
    /**
     * The title of the time recording regulation.
     * @type {string}
     * @memberof TimeRecordingRegulationBaseData
     */
    title?: string;
    /**
     * The unique key of the time recording regulation.
     * @type {string}
     * @memberof TimeRecordingRegulationBaseData
     */
    key?: string;
}

/**
 * Check if a given object implements the TimeRecordingRegulationBaseData interface.
 */
export function instanceOfTimeRecordingRegulationBaseData(value: object): value is TimeRecordingRegulationBaseData {
    return true;
}

export function TimeRecordingRegulationBaseDataFromJSON(json: any): TimeRecordingRegulationBaseData {
    return TimeRecordingRegulationBaseDataFromJSONTyped(json, false);
}

export function TimeRecordingRegulationBaseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeRecordingRegulationBaseData {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function TimeRecordingRegulationBaseDataToJSON(json: any): TimeRecordingRegulationBaseData {
    return TimeRecordingRegulationBaseDataToJSONTyped(json, false);
}

export function TimeRecordingRegulationBaseDataToJSONTyped(value?: TimeRecordingRegulationBaseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'key': value['key'],
    };
}

