/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object representing a customer
 * @export
 * @interface TimeTrackingProjectBaseCustomer
 */
export interface TimeTrackingProjectBaseCustomer {
    /**
     * The unique identifier of the customer.
     * @type {string}
     * @memberof TimeTrackingProjectBaseCustomer
     */
    id?: string;
    /**
     * The customer number.
     * @type {string}
     * @memberof TimeTrackingProjectBaseCustomer
     */
    number?: string;
    /**
     * Name of the customer.
     * @type {string}
     * @memberof TimeTrackingProjectBaseCustomer
     */
    name?: string;
    /**
     * Indicates whether the customer is currently in use.
     * @type {boolean}
     * @memberof TimeTrackingProjectBaseCustomer
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the TimeTrackingProjectBaseCustomer interface.
 */
export function instanceOfTimeTrackingProjectBaseCustomer(value: object): value is TimeTrackingProjectBaseCustomer {
    return true;
}

export function TimeTrackingProjectBaseCustomerFromJSON(json: any): TimeTrackingProjectBaseCustomer {
    return TimeTrackingProjectBaseCustomerFromJSONTyped(json, false);
}

export function TimeTrackingProjectBaseCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeTrackingProjectBaseCustomer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'number': json['number'] == null ? undefined : json['number'],
        'name': json['name'] == null ? undefined : json['name'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function TimeTrackingProjectBaseCustomerToJSON(json: any): TimeTrackingProjectBaseCustomer {
    return TimeTrackingProjectBaseCustomerToJSONTyped(json, false);
}

export function TimeTrackingProjectBaseCustomerToJSONTyped(value?: TimeTrackingProjectBaseCustomer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'number': value['number'],
        'name': value['name'],
        'isActive': value['isActive'],
    };
}

