/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * JSON object representing a time account of a person in HR WORKS
 * @export
 * @interface TimeAccount
 */
export interface TimeAccount {
    /**
     * A month-year combination in the format "YYYY-MM"
     * @type {string}
     * @memberof TimeAccount
     */
    monthYear?: string;
    /**
     * The total amount of tracked working hours for this month in minutes.
     * @type {number}
     * @memberof TimeAccount
     */
    workingHours?: number;
    /**
     * The planned working hours for this month in minutes.
     * @type {number}
     * @memberof TimeAccount
     */
    targetWorkingHours?: number;
    /**
     * The amount of time credit for this month in minutes.
     * @type {number}
     * @memberof TimeAccount
     */
    timeCredit?: number;
    /**
     * The amount of time which was transfered from the previous month to this month in minutes.
     * @type {number}
     * @memberof TimeAccount
     */
    carryoverHours?: number;
    /**
     * The total balance at the end of the month in minutes.
     * @type {number}
     * @memberof TimeAccount
     */
    totalTime?: number;
    /**
     * The total amount of time corrections for the month in minutes.
     * @type {number}
     * @memberof TimeAccount
     */
    timeCorrectionSum?: number;
}

/**
 * Check if a given object implements the TimeAccount interface.
 */
export function instanceOfTimeAccount(value: object): value is TimeAccount {
    return true;
}

export function TimeAccountFromJSON(json: any): TimeAccount {
    return TimeAccountFromJSONTyped(json, false);
}

export function TimeAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'monthYear': json['monthYear'] == null ? undefined : json['monthYear'],
        'workingHours': json['workingHours'] == null ? undefined : json['workingHours'],
        'targetWorkingHours': json['targetWorkingHours'] == null ? undefined : json['targetWorkingHours'],
        'timeCredit': json['timeCredit'] == null ? undefined : json['timeCredit'],
        'carryoverHours': json['carryoverHours'] == null ? undefined : json['carryoverHours'],
        'totalTime': json['totalTime'] == null ? undefined : json['totalTime'],
        'timeCorrectionSum': json['timeCorrectionSum'] == null ? undefined : json['timeCorrectionSum'],
    };
}

export function TimeAccountToJSON(json: any): TimeAccount {
    return TimeAccountToJSONTyped(json, false);
}

export function TimeAccountToJSONTyped(value?: TimeAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'monthYear': value['monthYear'],
        'workingHours': value['workingHours'],
        'targetWorkingHours': value['targetWorkingHours'],
        'timeCredit': value['timeCredit'],
        'carryoverHours': value['carryoverHours'],
        'totalTime': value['totalTime'],
        'timeCorrectionSum': value['timeCorrectionSum'],
    };
}

