/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CostObjective } from './CostObjective';
import {
    CostObjectiveFromJSON,
    CostObjectiveFromJSONTyped,
    CostObjectiveToJSON,
    CostObjectiveToJSONTyped,
} from './CostObjective';
import type { CostCenter } from './CostCenter';
import {
    CostCenterFromJSON,
    CostCenterFromJSONTyped,
    CostCenterToJSON,
    CostCenterToJSONTyped,
} from './CostCenter';
import type { CurrencyValue } from './CurrencyValue';
import {
    CurrencyValueFromJSON,
    CurrencyValueFromJSONTyped,
    CurrencyValueToJSON,
    CurrencyValueToJSONTyped,
} from './CurrencyValue';
import type { PersonBaseData } from './PersonBaseData';
import {
    PersonBaseDataFromJSON,
    PersonBaseDataFromJSONTyped,
    PersonBaseDataToJSON,
    PersonBaseDataToJSONTyped,
} from './PersonBaseData';
import type { TravelRequestStatus } from './TravelRequestStatus';
import {
    TravelRequestStatusFromJSON,
    TravelRequestStatusFromJSONTyped,
    TravelRequestStatusToJSON,
    TravelRequestStatusToJSONTyped,
} from './TravelRequestStatus';

/**
 * 
 * @export
 * @interface TravelRequest
 */
export interface TravelRequest {
    /**
     * The start date of the travel request. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof TravelRequest
     */
    beginDate?: Date;
    /**
     * The end date of the travel request. Date in YYYY-MM-DD format.
     * @type {Date}
     * @memberof TravelRequest
     */
    endDate?: Date;
    /**
     * 
     * @type {CostCenter}
     * @memberof TravelRequest
     */
    costCenter?: CostCenter;
    /**
     * 
     * @type {CostObjective}
     * @memberof TravelRequest
     */
    costObjective?: CostObjective;
    /**
     * The travelling destination of the travel request.
     * @type {string}
     * @memberof TravelRequest
     */
    destination?: string;
    /**
     * 
     * @type {PersonBaseData}
     * @memberof TravelRequest
     */
    person?: PersonBaseData;
    /**
     * The title of the travel request.
     * @type {string}
     * @memberof TravelRequest
     */
    name?: string;
    /**
     * A unique identifier of the travel request. Consists of the personnel number of the person associated with the travel request and the running per-person travel request number.
     * @type {string}
     * @memberof TravelRequest
     */
    number?: string;
    /**
     * The location where the business trip will start.
     * @type {string}
     * @memberof TravelRequest
     */
    startLocation?: string;
    /**
     * The status of the travel request, e.g. Checked, OK.
     * @type {string}
     * @memberof TravelRequest
     */
    status?: string;
    /**
     * 
     * @type {TravelRequestStatus}
     * @memberof TravelRequest
     */
    statusIdentifier?: TravelRequestStatus | null;
    /**
     * Comma-separated names of stopovers
     * @type {string}
     * @memberof TravelRequest
     */
    stopovers?: string;
    /**
     * 
     * @type {CurrencyValue}
     * @memberof TravelRequest
     */
    expectedCosts?: CurrencyValue;
    /**
     * Comma-separated names of all destination countries of the travel request.
     * @type {string}
     * @memberof TravelRequest
     */
    destinationCountries?: string;
    /**
     * If the travel request was converted to an expense report, this attribute contains the unique number of said expense report.
     * @type {string}
     * @memberof TravelRequest
     */
    travelExpensesReportNumber?: string;
}



/**
 * Check if a given object implements the TravelRequest interface.
 */
export function instanceOfTravelRequest(value: object): value is TravelRequest {
    return true;
}

export function TravelRequestFromJSON(json: any): TravelRequest {
    return TravelRequestFromJSONTyped(json, false);
}

export function TravelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'costCenter': json['costCenter'] == null ? undefined : CostCenterFromJSON(json['costCenter']),
        'costObjective': json['costObjective'] == null ? undefined : CostObjectiveFromJSON(json['costObjective']),
        'destination': json['destination'] == null ? undefined : json['destination'],
        'person': json['person'] == null ? undefined : PersonBaseDataFromJSON(json['person']),
        'name': json['name'] == null ? undefined : json['name'],
        'number': json['number'] == null ? undefined : json['number'],
        'startLocation': json['startLocation'] == null ? undefined : json['startLocation'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusIdentifier': json['statusIdentifier'] == null ? undefined : TravelRequestStatusFromJSON(json['statusIdentifier']),
        'stopovers': json['stopovers'] == null ? undefined : json['stopovers'],
        'expectedCosts': json['expectedCosts'] == null ? undefined : CurrencyValueFromJSON(json['expectedCosts']),
        'destinationCountries': json['destinationCountries'] == null ? undefined : json['destinationCountries'],
        'travelExpensesReportNumber': json['travelExpensesReportNumber'] == null ? undefined : json['travelExpensesReportNumber'],
    };
}

export function TravelRequestToJSON(json: any): TravelRequest {
    return TravelRequestToJSONTyped(json, false);
}

export function TravelRequestToJSONTyped(value?: TravelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'costCenter': CostCenterToJSON(value['costCenter']),
        'costObjective': CostObjectiveToJSON(value['costObjective']),
        'destination': value['destination'],
        'person': PersonBaseDataToJSON(value['person']),
        'name': value['name'],
        'number': value['number'],
        'startLocation': value['startLocation'],
        'status': value['status'],
        'statusIdentifier': TravelRequestStatusToJSON(value['statusIdentifier']),
        'stopovers': value['stopovers'],
        'expectedCosts': CurrencyValueToJSON(value['expectedCosts']),
        'destinationCountries': value['destinationCountries'],
        'travelExpensesReportNumber': value['travelExpensesReportNumber'],
    };
}

