/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TravelRequestStatus = {
    Editing: 'editing',
    Applied: 'applied',
    ValidatedOk: 'validatedOk',
    ValidatedNotOk: 'validatedNotOk'
} as const;
export type TravelRequestStatus = typeof TravelRequestStatus[keyof typeof TravelRequestStatus];


export function instanceOfTravelRequestStatus(value: any): boolean {
    for (const key in TravelRequestStatus) {
        if (Object.prototype.hasOwnProperty.call(TravelRequestStatus, key)) {
            if (TravelRequestStatus[key as keyof typeof TravelRequestStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TravelRequestStatusFromJSON(json: any): TravelRequestStatus {
    return TravelRequestStatusFromJSONTyped(json, false);
}

export function TravelRequestStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TravelRequestStatus {
    return json as TravelRequestStatus;
}

export function TravelRequestStatusToJSON(value?: TravelRequestStatus | null): any {
    return value as any;
}

export function TravelRequestStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): TravelRequestStatus {
    return value as TravelRequestStatus;
}

