/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnitValueTuple
 */
export interface UnitValueTuple {
    /**
     * The unit, e.g. km.
     * @type {string}
     * @memberof UnitValueTuple
     */
    unit?: string;
    /**
     * The value with up to 2 decimals.
     * @type {number}
     * @memberof UnitValueTuple
     */
    value?: number;
}

/**
 * Check if a given object implements the UnitValueTuple interface.
 */
export function instanceOfUnitValueTuple(value: object): value is UnitValueTuple {
    return true;
}

export function UnitValueTupleFromJSON(json: any): UnitValueTuple {
    return UnitValueTupleFromJSONTyped(json, false);
}

export function UnitValueTupleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnitValueTuple {
    if (json == null) {
        return json;
    }
    return {
        
        'unit': json['unit'] == null ? undefined : json['unit'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function UnitValueTupleToJSON(json: any): UnitValueTuple {
    return UnitValueTupleToJSONTyped(json, false);
}

export function UnitValueTupleToJSONTyped(value?: UnitValueTuple | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unit': value['unit'],
        'value': value['value'],
    };
}

