/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProportionalVacationEntitlementCalculation } from './ProportionalVacationEntitlementCalculation';
import {
    ProportionalVacationEntitlementCalculationFromJSON,
    ProportionalVacationEntitlementCalculationFromJSONTyped,
    ProportionalVacationEntitlementCalculationToJSON,
    ProportionalVacationEntitlementCalculationToJSONTyped,
} from './ProportionalVacationEntitlementCalculation';
import type { ValueAssociatedNumericalRange } from './ValueAssociatedNumericalRange';
import {
    ValueAssociatedNumericalRangeFromJSON,
    ValueAssociatedNumericalRangeFromJSONTyped,
    ValueAssociatedNumericalRangeToJSON,
    ValueAssociatedNumericalRangeToJSONTyped,
} from './ValueAssociatedNumericalRange';

/**
 * A vacation type in HR WORKS.
 * @export
 * @interface VacationType
 */
export interface VacationType {
    /**
     * The name of the vacation type.
     * @type {string}
     * @memberof VacationType
     */
    name?: string;
    /**
     * The key of the vacation type.
     * @type {string}
     * @memberof VacationType
     */
    key?: string;
    /**
     * The three-letter country code of the country that the vacation type is associated with.
     * @type {string}
     * @memberof VacationType
     */
    countryCode?: string;
    /**
     * Indicates if the vacation type is currently active.
     * @type {boolean}
     * @memberof VacationType
     */
    isActive?: boolean;
    /**
     * Indicates if the vacation type is currently assigned to a person in HR WORKS.
     * @type {boolean}
     * @memberof VacationType
     */
    isAssigned?: boolean;
    /**
     * Answer whether the kind of vacation is marked as default vacation type of the company.
     * @type {boolean}
     * @memberof VacationType
     */
    isDefault?: boolean;
    /**
     * The number of weekly working hours of the vacation type.
     * @type {number}
     * @memberof VacationType
     */
    weeklyWorkingHours?: number;
    /**
     * The minimum number of vacation days of the vacation type.
     * @type {number}
     * @memberof VacationType
     */
    minimumVacationEntitlement?: number;
    /**
     * The number of additional vacation entitlement days.
     * @type {number}
     * @memberof VacationType
     */
    additionalVacationEntitlement?: number;
    /**
     * The number of additional vacation granted to disabled persons.
     * @type {number}
     * @memberof VacationType
     */
    disabilityRelatedVacationEntitlement?: number;
    /**
     * 
     * @type {ProportionalVacationEntitlementCalculation}
     * @memberof VacationType
     */
    vacationCalculationLeaveSecondHalf?: ProportionalVacationEntitlementCalculation;
    /**
     * 
     * @type {ProportionalVacationEntitlementCalculation}
     * @memberof VacationType
     */
    vacationCalculationEntryFirstHalf?: ProportionalVacationEntitlementCalculation;
    /**
     * Specifies after how many days in the following year the vacation entitlement expires.
     * @type {number}
     * @memberof VacationType
     */
    expirationDays?: number;
    /**
     * Specifies after how many months in the following year the vacation entitlement expires.
     * @type {number}
     * @memberof VacationType
     */
    expirationMonths?: number;
    /**
     * The age dependent boni to vacation.
     * @type {Array<ValueAssociatedNumericalRange>}
     * @memberof VacationType
     */
    ageRelatedVacationEntitlement?: Array<ValueAssociatedNumericalRange>;
    /**
     * The tenure dependent boni for vacation.
     * @type {Array<ValueAssociatedNumericalRange>}
     * @memberof VacationType
     */
    tenureRelatedVacationEntitlement?: Array<ValueAssociatedNumericalRange>;
}



/**
 * Check if a given object implements the VacationType interface.
 */
export function instanceOfVacationType(value: object): value is VacationType {
    return true;
}

export function VacationTypeFromJSON(json: any): VacationType {
    return VacationTypeFromJSONTyped(json, false);
}

export function VacationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VacationType {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'key': json['key'] == null ? undefined : json['key'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'isAssigned': json['isAssigned'] == null ? undefined : json['isAssigned'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'weeklyWorkingHours': json['weeklyWorkingHours'] == null ? undefined : json['weeklyWorkingHours'],
        'minimumVacationEntitlement': json['minimumVacationEntitlement'] == null ? undefined : json['minimumVacationEntitlement'],
        'additionalVacationEntitlement': json['additionalVacationEntitlement'] == null ? undefined : json['additionalVacationEntitlement'],
        'disabilityRelatedVacationEntitlement': json['disabilityRelatedVacationEntitlement'] == null ? undefined : json['disabilityRelatedVacationEntitlement'],
        'vacationCalculationLeaveSecondHalf': json['vacationCalculationLeaveSecondHalf'] == null ? undefined : ProportionalVacationEntitlementCalculationFromJSON(json['vacationCalculationLeaveSecondHalf']),
        'vacationCalculationEntryFirstHalf': json['vacationCalculationEntryFirstHalf'] == null ? undefined : ProportionalVacationEntitlementCalculationFromJSON(json['vacationCalculationEntryFirstHalf']),
        'expirationDays': json['expirationDays'] == null ? undefined : json['expirationDays'],
        'expirationMonths': json['expirationMonths'] == null ? undefined : json['expirationMonths'],
        'ageRelatedVacationEntitlement': json['ageRelatedVacationEntitlement'] == null ? undefined : ((json['ageRelatedVacationEntitlement'] as Array<any>).map(ValueAssociatedNumericalRangeFromJSON)),
        'tenureRelatedVacationEntitlement': json['tenureRelatedVacationEntitlement'] == null ? undefined : ((json['tenureRelatedVacationEntitlement'] as Array<any>).map(ValueAssociatedNumericalRangeFromJSON)),
    };
}

export function VacationTypeToJSON(json: any): VacationType {
    return VacationTypeToJSONTyped(json, false);
}

export function VacationTypeToJSONTyped(value?: VacationType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
        'countryCode': value['countryCode'],
        'isActive': value['isActive'],
        'isAssigned': value['isAssigned'],
        'isDefault': value['isDefault'],
        'weeklyWorkingHours': value['weeklyWorkingHours'],
        'minimumVacationEntitlement': value['minimumVacationEntitlement'],
        'additionalVacationEntitlement': value['additionalVacationEntitlement'],
        'disabilityRelatedVacationEntitlement': value['disabilityRelatedVacationEntitlement'],
        'vacationCalculationLeaveSecondHalf': ProportionalVacationEntitlementCalculationToJSON(value['vacationCalculationLeaveSecondHalf']),
        'vacationCalculationEntryFirstHalf': ProportionalVacationEntitlementCalculationToJSON(value['vacationCalculationEntryFirstHalf']),
        'expirationDays': value['expirationDays'],
        'expirationMonths': value['expirationMonths'],
        'ageRelatedVacationEntitlement': value['ageRelatedVacationEntitlement'] == null ? undefined : ((value['ageRelatedVacationEntitlement'] as Array<any>).map(ValueAssociatedNumericalRangeToJSON)),
        'tenureRelatedVacationEntitlement': value['tenureRelatedVacationEntitlement'] == null ? undefined : ((value['tenureRelatedVacationEntitlement'] as Array<any>).map(ValueAssociatedNumericalRangeToJSON)),
    };
}

