/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NumericalRange } from './NumericalRange';
import {
    NumericalRangeFromJSON,
    NumericalRangeFromJSONTyped,
    NumericalRangeToJSON,
    NumericalRangeToJSONTyped,
} from './NumericalRange';

/**
 * A vacation expression in HR WORKS
 * @export
 * @interface ValueAssociatedNumericalRange
 */
export interface ValueAssociatedNumericalRange {
    /**
     * 
     * @type {NumericalRange}
     * @memberof ValueAssociatedNumericalRange
     */
    range?: NumericalRange;
    /**
     * The possible increase in value while maintaining the range limited by the upper and lower limits.
     * @type {number}
     * @memberof ValueAssociatedNumericalRange
     */
    value?: number;
}

/**
 * Check if a given object implements the ValueAssociatedNumericalRange interface.
 */
export function instanceOfValueAssociatedNumericalRange(value: object): value is ValueAssociatedNumericalRange {
    return true;
}

export function ValueAssociatedNumericalRangeFromJSON(json: any): ValueAssociatedNumericalRange {
    return ValueAssociatedNumericalRangeFromJSONTyped(json, false);
}

export function ValueAssociatedNumericalRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValueAssociatedNumericalRange {
    if (json == null) {
        return json;
    }
    return {
        
        'range': json['range'] == null ? undefined : NumericalRangeFromJSON(json['range']),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function ValueAssociatedNumericalRangeToJSON(json: any): ValueAssociatedNumericalRange {
    return ValueAssociatedNumericalRangeToJSONTyped(json, false);
}

export function ValueAssociatedNumericalRangeToJSONTyped(value?: ValueAssociatedNumericalRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'range': NumericalRangeToJSON(value['range']),
        'value': value['value'],
    };
}

