/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The action type that triggers the webhook (resourceDeactivated is only used with the person resource).
 * @export
 */
export const WebhookAction = {
    ResourceDeactivated: 'resourceDeactivated',
    ResourceCreated: 'resourceCreated',
    ResourceDeleted: 'resourceDeleted',
    ResourceUpdated: 'resourceUpdated'
} as const;
export type WebhookAction = typeof WebhookAction[keyof typeof WebhookAction];


export function instanceOfWebhookAction(value: any): boolean {
    for (const key in WebhookAction) {
        if (Object.prototype.hasOwnProperty.call(WebhookAction, key)) {
            if (WebhookAction[key as keyof typeof WebhookAction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WebhookActionFromJSON(json: any): WebhookAction {
    return WebhookActionFromJSONTyped(json, false);
}

export function WebhookActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookAction {
    return json as WebhookAction;
}

export function WebhookActionToJSON(value?: WebhookAction | null): any {
    return value as any;
}

export function WebhookActionToJSONTyped(value: any, ignoreDiscriminator: boolean): WebhookAction {
    return value as WebhookAction;
}

