/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookConfiguration
 */
export interface WebhookConfiguration {
    /**
     * The URL of the webhook.
     * @type {string}
     * @memberof WebhookConfiguration
     */
    url?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof WebhookConfiguration
     */
    headers?: { [key: string]: string; };
}

/**
 * Check if a given object implements the WebhookConfiguration interface.
 */
export function instanceOfWebhookConfiguration(value: object): value is WebhookConfiguration {
    return true;
}

export function WebhookConfigurationFromJSON(json: any): WebhookConfiguration {
    return WebhookConfigurationFromJSONTyped(json, false);
}

export function WebhookConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'headers': json['headers'] == null ? undefined : json['headers'],
    };
}

export function WebhookConfigurationToJSON(json: any): WebhookConfiguration {
    return WebhookConfigurationToJSONTyped(json, false);
}

export function WebhookConfigurationToJSONTyped(value?: WebhookConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'headers': value['headers'],
    };
}

