/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A working time object.
 * @export
 * @interface WorkingTimeData
 */
export interface WorkingTimeData {
    /**
     * The personnel number of the person. It's required to include either the personnel number or the personIdentifierForKiosk of the person.
     * @type {string}
     * @memberof WorkingTimeData
     */
    personnelNumber?: string | null;
    /**
     * Alternative way to identify the person. The personIdentifierForKiosk of the person. It's required to include either the personnel number or the personIdentifierForKiosk of the person.
     * @type {string}
     * @memberof WorkingTimeData
     */
    personIdentifierForKiosk?: string | null;
    /**
     * The begin time of the working time.
     * @type {Date}
     * @memberof WorkingTimeData
     */
    beginDateAndTime: Date;
    /**
     * The end time of the working time.
     * @type {Date}
     * @memberof WorkingTimeData
     */
    endDateAndTime?: Date | null;
    /**
     * The working time type of the working time.
     * @type {string}
     * @memberof WorkingTimeData
     */
    type?: string | null;
    /**
     * The unique number of the project
     * @type {number}
     * @memberof WorkingTimeData
     */
    projectNumber?: number | null;
    /**
     * The id of the kiosk which was used to clock in.
     * @type {number}
     * @memberof WorkingTimeData
     */
    clockInKioskId?: number | null;
    /**
     * The id of the kiosk which was used to clock out.
     * @type {number}
     * @memberof WorkingTimeData
     */
    clockOutKioskId?: number | null;
    /**
     * Comment on the working time.
     * @type {string}
     * @memberof WorkingTimeData
     */
    comment?: string | null;
}

/**
 * Check if a given object implements the WorkingTimeData interface.
 */
export function instanceOfWorkingTimeData(value: object): value is WorkingTimeData {
    if (!('beginDateAndTime' in value) || value['beginDateAndTime'] === undefined) return false;
    return true;
}

export function WorkingTimeDataFromJSON(json: any): WorkingTimeData {
    return WorkingTimeDataFromJSONTyped(json, false);
}

export function WorkingTimeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkingTimeData {
    if (json == null) {
        return json;
    }
    return {
        
        'personnelNumber': json['personnelNumber'] == null ? undefined : json['personnelNumber'],
        'personIdentifierForKiosk': json['personIdentifierForKiosk'] == null ? undefined : json['personIdentifierForKiosk'],
        'beginDateAndTime': (new Date(json['beginDateAndTime'])),
        'endDateAndTime': json['endDateAndTime'] == null ? undefined : (new Date(json['endDateAndTime'])),
        'type': json['type'] == null ? undefined : json['type'],
        'projectNumber': json['projectNumber'] == null ? undefined : json['projectNumber'],
        'clockInKioskId': json['clockInKioskId'] == null ? undefined : json['clockInKioskId'],
        'clockOutKioskId': json['clockOutKioskId'] == null ? undefined : json['clockOutKioskId'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function WorkingTimeDataToJSON(json: any): WorkingTimeData {
    return WorkingTimeDataToJSONTyped(json, false);
}

export function WorkingTimeDataToJSONTyped(value?: WorkingTimeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'personnelNumber': value['personnelNumber'],
        'personIdentifierForKiosk': value['personIdentifierForKiosk'],
        'beginDateAndTime': value['beginDateAndTime'].toISOString(),
        'endDateAndTime': value['endDateAndTime'] == null ? value['endDateAndTime'] : value['endDateAndTime'].toISOString(),
        'type': value['type'],
        'projectNumber': value['projectNumber'],
        'clockInKioskId': value['clockInKioskId'],
        'clockOutKioskId': value['clockOutKioskId'],
        'comment': value['comment'],
    };
}

