/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseTimeTrackingProject } from './BaseTimeTrackingProject';
import {
    BaseTimeTrackingProjectFromJSON,
    BaseTimeTrackingProjectFromJSONTyped,
    BaseTimeTrackingProjectToJSON,
    BaseTimeTrackingProjectToJSONTyped,
} from './BaseTimeTrackingProject';
import type { WorkingTimeType } from './WorkingTimeType';
import {
    WorkingTimeTypeFromJSON,
    WorkingTimeTypeFromJSONTyped,
    WorkingTimeTypeToJSON,
    WorkingTimeTypeToJSONTyped,
} from './WorkingTimeType';

/**
 * Object representing a single working time.
 * @export
 * @interface WorkingTime
 */
export interface WorkingTime {
    /**
     * The begin time of the working time. Formatted as YYYYMMDD"T"HHMMSS"Z".
     * @type {Date}
     * @memberof WorkingTime
     */
    beginDateAndTime?: Date;
    /**
     * The end time of the working time. Formatted as YYYYMMDD"T"HHMMSS"Z".
     * @type {Date}
     * @memberof WorkingTime
     */
    endDateAndTime?: Date;
    /**
     * The id of the kiosk if the time was started on a Kiosk.
     * @type {number}
     * @memberof WorkingTime
     */
    clockInKioskId?: number;
    /**
     * The id of the kiosk if the time was stoped on a Kiosk.
     * @type {number}
     * @memberof WorkingTime
     */
    clockOutKioskId?: number;
    /**
     * The comment referring to the WorkingTime
     * @type {string}
     * @memberof WorkingTime
     */
    comment?: string;
    /**
     * 
     * @type {WorkingTimeType}
     * @memberof WorkingTime
     */
    workingTimeType?: WorkingTimeType;
    /**
     * 
     * @type {BaseTimeTrackingProject}
     * @memberof WorkingTime
     */
    project?: BaseTimeTrackingProject;
    /**
     * The id of the working time, consisting of the person number and the beginDateAndTime. Formatted as the person number followed by an underscore '_' and concluded with the beginDateAndTime as Unix time.
     * @type {string}
     * @memberof WorkingTime
     */
    id?: string;
}

/**
 * Check if a given object implements the WorkingTime interface.
 */
export function instanceOfWorkingTime(value: object): value is WorkingTime {
    return true;
}

export function WorkingTimeFromJSON(json: any): WorkingTime {
    return WorkingTimeFromJSONTyped(json, false);
}

export function WorkingTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkingTime {
    if (json == null) {
        return json;
    }
    return {
        
        'beginDateAndTime': json['beginDateAndTime'] == null ? undefined : (new Date(json['beginDateAndTime'])),
        'endDateAndTime': json['endDateAndTime'] == null ? undefined : (new Date(json['endDateAndTime'])),
        'clockInKioskId': json['clockInKioskId'] == null ? undefined : json['clockInKioskId'],
        'clockOutKioskId': json['clockOutKioskId'] == null ? undefined : json['clockOutKioskId'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'workingTimeType': json['workingTimeType'] == null ? undefined : WorkingTimeTypeFromJSON(json['workingTimeType']),
        'project': json['project'] == null ? undefined : BaseTimeTrackingProjectFromJSON(json['project']),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function WorkingTimeToJSON(json: any): WorkingTime {
    return WorkingTimeToJSONTyped(json, false);
}

export function WorkingTimeToJSONTyped(value?: WorkingTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beginDateAndTime': value['beginDateAndTime'] == null ? value['beginDateAndTime'] : value['beginDateAndTime'].toISOString(),
        'endDateAndTime': value['endDateAndTime'] == null ? value['endDateAndTime'] : value['endDateAndTime'].toISOString(),
        'clockInKioskId': value['clockInKioskId'],
        'clockOutKioskId': value['clockOutKioskId'],
        'comment': value['comment'],
        'workingTimeType': WorkingTimeTypeToJSON(value['workingTimeType']),
        'project': BaseTimeTrackingProjectToJSON(value['project']),
        'id': value['id'],
    };
}

