/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkingTimeTypes } from './WorkingTimeTypes';
import {
    WorkingTimeTypesFromJSON,
    WorkingTimeTypesFromJSONTyped,
    WorkingTimeTypesToJSON,
    WorkingTimeTypesToJSONTyped,
} from './WorkingTimeTypes';

/**
 * A time tracking type.
 * @export
 * @interface WorkingTimeType
 */
export interface WorkingTimeType {
    /**
     * 
     * @type {string}
     * @memberof WorkingTimeType
     */
    name?: string;
    /**
     * 
     * @type {WorkingTimeTypes}
     * @memberof WorkingTimeType
     */
    type?: WorkingTimeTypes | null;
}



/**
 * Check if a given object implements the WorkingTimeType interface.
 */
export function instanceOfWorkingTimeType(value: object): value is WorkingTimeType {
    return true;
}

export function WorkingTimeTypeFromJSON(json: any): WorkingTimeType {
    return WorkingTimeTypeFromJSONTyped(json, false);
}

export function WorkingTimeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkingTimeType {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : WorkingTimeTypesFromJSON(json['type']),
    };
}

export function WorkingTimeTypeToJSON(json: any): WorkingTimeType {
    return WorkingTimeTypeToJSONTyped(json, false);
}

export function WorkingTimeTypeToJSONTyped(value?: WorkingTimeType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': WorkingTimeTypesToJSON(value['type']),
    };
}

