/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkScheduleDay } from './WorkScheduleDay';
import {
    WorkScheduleDayFromJSON,
    WorkScheduleDayFromJSONTyped,
    WorkScheduleDayToJSON,
    WorkScheduleDayToJSONTyped,
} from './WorkScheduleDay';

/**
 * A working schedule.
 * @export
 * @interface WorkSchedule
 */
export interface WorkSchedule {
    /**
     * The name of the working schedule.
     * @type {string}
     * @memberof WorkSchedule
     */
    name?: string;
    /**
     * The key of the working schedule.
     * @type {string}
     * @memberof WorkSchedule
     */
    key?: string;
    /**
     * The total working hours in a week.
     * @type {number}
     * @memberof WorkSchedule
     */
    weeklyWorkingHours?: number;
    /**
     * An array of the days in the work schedule. Each day is indexed by a sequence number (e.g. first day in the work schedule) which is mapped to a working day JSON object containing the scheduled working hours for said day and a String identifier for the weekday name (e.g. Wednesday). Thus, the day with the sequence number 1 does not necessarily have to be a Monday - it depends on the configuration of the working schedule in HR WORKS.
     * @type {Array<{ [key: string]: WorkScheduleDay; }>}
     * @memberof WorkSchedule
     */
    workingDays?: Array<{ [key: string]: WorkScheduleDay; }>;
}

/**
 * Check if a given object implements the WorkSchedule interface.
 */
export function instanceOfWorkSchedule(value: object): value is WorkSchedule {
    return true;
}

export function WorkScheduleFromJSON(json: any): WorkSchedule {
    return WorkScheduleFromJSONTyped(json, false);
}

export function WorkScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkSchedule {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'key': json['key'] == null ? undefined : json['key'],
        'weeklyWorkingHours': json['weeklyWorkingHours'] == null ? undefined : json['weeklyWorkingHours'],
        'workingDays': json['workingDays'] == null ? undefined : json['workingDays'],
    };
}

export function WorkScheduleToJSON(json: any): WorkSchedule {
    return WorkScheduleToJSONTyped(json, false);
}

export function WorkScheduleToJSONTyped(value?: WorkSchedule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
        'weeklyWorkingHours': value['weeklyWorkingHours'],
        'workingDays': value['workingDays'],
    };
}

