/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkingTime } from './WorkingTime';
import {
    WorkingTimeFromJSON,
    WorkingTimeFromJSONTyped,
    WorkingTimeToJSON,
    WorkingTimeToJSONTyped,
} from './WorkingTime';

/**
 * JSON object representing a date interval with the associated working times.
 * @export
 * @interface WorkingTimesDateIntervalData
 */
export interface WorkingTimesDateIntervalData {
    /**
     * 
     * @type {Date}
     * @memberof WorkingTimesDateIntervalData
     */
    beginDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkingTimesDateIntervalData
     */
    endDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof WorkingTimesDateIntervalData
     */
    workingTimeMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkingTimesDateIntervalData
     */
    targetWorkingTimeMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkingTimesDateIntervalData
     */
    breakDurationMinutes?: number;
    /**
     * 
     * @type {Array<WorkingTime>}
     * @memberof WorkingTimesDateIntervalData
     */
    workingTimes?: Array<WorkingTime>;
}

/**
 * Check if a given object implements the WorkingTimesDateIntervalData interface.
 */
export function instanceOfWorkingTimesDateIntervalData(value: object): value is WorkingTimesDateIntervalData {
    return true;
}

export function WorkingTimesDateIntervalDataFromJSON(json: any): WorkingTimesDateIntervalData {
    return WorkingTimesDateIntervalDataFromJSONTyped(json, false);
}

export function WorkingTimesDateIntervalDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkingTimesDateIntervalData {
    if (json == null) {
        return json;
    }
    return {
        
        'beginDate': json['beginDate'] == null ? undefined : (new Date(json['beginDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'workingTimeMinutes': json['workingTimeMinutes'] == null ? undefined : json['workingTimeMinutes'],
        'targetWorkingTimeMinutes': json['targetWorkingTimeMinutes'] == null ? undefined : json['targetWorkingTimeMinutes'],
        'breakDurationMinutes': json['breakDurationMinutes'] == null ? undefined : json['breakDurationMinutes'],
        'workingTimes': json['workingTimes'] == null ? undefined : ((json['workingTimes'] as Array<any>).map(WorkingTimeFromJSON)),
    };
}

export function WorkingTimesDateIntervalDataToJSON(json: any): WorkingTimesDateIntervalData {
    return WorkingTimesDateIntervalDataToJSONTyped(json, false);
}

export function WorkingTimesDateIntervalDataToJSONTyped(value?: WorkingTimesDateIntervalData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beginDate': value['beginDate'] == null ? value['beginDate'] : value['beginDate'].toISOString().substring(0,10),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'workingTimeMinutes': value['workingTimeMinutes'],
        'targetWorkingTimeMinutes': value['targetWorkingTimeMinutes'],
        'breakDurationMinutes': value['breakDurationMinutes'],
        'workingTimes': value['workingTimes'] == null ? undefined : ((value['workingTimes'] as Array<any>).map(WorkingTimeToJSON)),
    };
}

