/* tslint:disable */
/* eslint-disable */
/**
 * HR WORKS API v2
 * HR WORKS API v2
 *
 * The version of the OpenAPI document: 2.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataError } from './DataError';
import {
    DataErrorFromJSON,
    DataErrorFromJSONTyped,
    DataErrorToJSON,
    DataErrorToJSONTyped,
} from './DataError';
import type { ApiError } from './ApiError';
import {
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
    ApiErrorToJSONTyped,
} from './ApiError';

/**
 * A wrapper object for the result of a write (PUT/POST/DELETE) request against the HR WORKS API. Will EITHER contain one or more errors that occurred while processing the request (meaning the request failed) OR a representation of the objects manipulated/created with the call (meaning the request was successful). Successful requests might also contain warnings that occurred while processing the request, but were ignored.
 * @export
 * @interface WriteRequestResult
 */
export interface WriteRequestResult {
    /**
     * A collection of all general errors that occurred during the write request. Not included if no errors occurred.
     * @type {Array<ApiError>}
     * @memberof WriteRequestResult
     */
    generalErrors?: Array<ApiError>;
    /**
     * A collection of all object-specific errors that occurred during the write request. A write request is aborted as soon as an error occurs, so this error collection may be incomplete. Each error contains a recordId that allows matching the errors to input data.
     * @type {Array<DataError>}
     * @memberof WriteRequestResult
     */
    dataErrors?: Array<DataError>;
    /**
     * 
     * @type {string}
     * @memberof WriteRequestResult
     */
    status?: string;
}

/**
 * Check if a given object implements the WriteRequestResult interface.
 */
export function instanceOfWriteRequestResult(value: object): value is WriteRequestResult {
    return true;
}

export function WriteRequestResultFromJSON(json: any): WriteRequestResult {
    return WriteRequestResultFromJSONTyped(json, false);
}

export function WriteRequestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteRequestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'generalErrors': json['generalErrors'] == null ? undefined : ((json['generalErrors'] as Array<any>).map(ApiErrorFromJSON)),
        'dataErrors': json['dataErrors'] == null ? undefined : ((json['dataErrors'] as Array<any>).map(DataErrorFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function WriteRequestResultToJSON(json: any): WriteRequestResult {
    return WriteRequestResultToJSONTyped(json, false);
}

export function WriteRequestResultToJSONTyped(value?: WriteRequestResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generalErrors': value['generalErrors'] == null ? undefined : ((value['generalErrors'] as Array<any>).map(ApiErrorToJSON)),
        'dataErrors': value['dataErrors'] == null ? undefined : ((value['dataErrors'] as Array<any>).map(DataErrorToJSON)),
        'status': value['status'],
    };
}

